<?php
			$optionsArray = array( 'welcome' => array( 'welcomePageSkip' => true,
'welcomeItems' => array( 'expand_menu_button' => array( 'menutItem' => false ),
'collapse_button' => array( 'menutItem' => false ),
'notifications' => array( 'menutItem' => false ),
'loginform_login' => array( 'menutItem' => false ),
'username_button' => array( 'menutItem' => false ),
'logo' => array( 'menutItem' => false ),
'expand_button' => array( 'menutItem' => false ),
'menu' => array( 'menutItem' => false ),
'welcome_item5' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'escolas',
'page' => 'list' ),
'welcome_item8' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'status',
'page' => 'list' ),
'welcome_item9' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'un_med',
'page' => 'list' ),
'welcome_item1' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'cidades',
'page' => 'list' ),
'welcome_item7' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'tecnico',
'page' => 'list' ),
'welcome_item10' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'draes',
'page' => 'list' ),
'welcome_item11' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'bairros',
'page' => 'list' ),
'welcome_item12' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'alternativa',
'page' => 'list' ),
'welcome_item2' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'funcao',
'page' => 'list' ),
'welcome_item6' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'direcs',
'page' => 'list' ),
'welcome_item15' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'NP_escola',
'page' => 'list' ),
'welcome_item' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'Relatório Sintético de Escolas',
'page' => 'report' ),
'welcome_item3' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'Relatório Analítico de Escolas',
'page' => 'report' ),
'welcome_item4' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'pedidos3_noti',
'page' => 'list' ),
'welcome_item13' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'messages',
'page' => 'list' ),
'welcome_item14' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'arquivos',
'page' => 'list' ),
'welcome_item16' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'Selec_tec',
'page' => 'list' ),
'welcome_item17' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'Seleciona_drae_novo',
'page' => 'list' ) ) ),
'fields' => array( 'gridFields' => array(  ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array(  ) ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array(  ),
'supertop' => array( 'expand_menu_button',
'collapse_button',
'notifications',
'loginform_login',
'username_button' ),
'left' => array( 'logo',
'expand_button',
'menu' ),
'grid' => array( 'welcome_item5',
'welcome_item8',
'welcome_item9',
'welcome_item1',
'welcome_item7',
'welcome_item10',
'welcome_item11',
'welcome_item12',
'welcome_item2',
'welcome_item6',
'welcome_item15',
'welcome_item',
'welcome_item3',
'welcome_item4',
'welcome_item13',
'welcome_item14',
'welcome_item16',
'welcome_item17' ) ),
'formXtTags' => array( 'above-grid' => array(  ) ),
'itemForms' => array( 'expand_menu_button' => 'supertop',
'collapse_button' => 'supertop',
'notifications' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'logo' => 'left',
'expand_button' => 'left',
'menu' => 'left',
'welcome_item5' => 'grid',
'welcome_item8' => 'grid',
'welcome_item9' => 'grid',
'welcome_item1' => 'grid',
'welcome_item7' => 'grid',
'welcome_item10' => 'grid',
'welcome_item11' => 'grid',
'welcome_item12' => 'grid',
'welcome_item2' => 'grid',
'welcome_item6' => 'grid',
'welcome_item15' => 'grid',
'welcome_item' => 'grid',
'welcome_item3' => 'grid',
'welcome_item4' => 'grid',
'welcome_item13' => 'grid',
'welcome_item14' => 'grid',
'welcome_item16' => 'grid',
'welcome_item17' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array( 'expand_menu_button' => 2,
'expand_button' => 5 ) ),
'itemsByType' => array( 'welcome_item' => array( 'welcome_item5',
'welcome_item8',
'welcome_item9',
'welcome_item1',
'welcome_item7',
'welcome_item10',
'welcome_item11',
'welcome_item12',
'welcome_item2',
'welcome_item6',
'welcome_item15',
'welcome_item',
'welcome_item3',
'welcome_item4',
'welcome_item13',
'welcome_item14',
'welcome_item16',
'welcome_item17' ),
'userinfo_link' => array( 'userinfo_link' ),
'logout_link' => array( 'logout_link' ),
'adminarea_link' => array( 'adminarea_link' ),
'changepassword_link' => array( 'changepassword_link' ),
'logo' => array( 'logo' ),
'menu' => array( 'menu' ),
'username_button' => array( 'username_button' ),
'loginform_login' => array( 'loginform_login' ),
'expand_menu_button' => array( 'expand_menu_button' ),
'collapse_button' => array( 'collapse_button' ),
'notifications' => array( 'notifications' ),
'expand_button' => array( 'expand_button' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 0 ),
'page' => array( 'verticalBar' => true,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => true ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'menu',
'type' => 'menu',
'layoutId' => 'leftbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'above-grid' => array( 'modelId' => 'empty-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'supertop' => array( 'modelId' => 'menu-topbar',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'expand_menu_button',
'collapse_button' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'notifications',
'loginform_login',
'username_button' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'left' => array( 'modelId' => 'leftbar-menu',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c0' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c0' => array( 'model' => 'c0',
'items' => array( 'logo',
'expand_button' ) ),
'c1' => array( 'model' => 'c1',
'items' => array( 'menu' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'welcome',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'welcome_item5',
'welcome_item8',
'welcome_item9',
'welcome_item1',
'welcome_item7',
'welcome_item10',
'welcome_item11',
'welcome_item12',
'welcome_item2',
'welcome_item6',
'welcome_item15',
'welcome_item',
'welcome_item3',
'welcome_item4',
'welcome_item13',
'welcome_item14',
'welcome_item16',
'welcome_item17' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'welcome_item5' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'escolas',
'linkPage' => 'list',
'linkText' => array( 'table' => 'escolas',
'type' => 6 ),
'linkIcon' => array( 'glyph' => 'earphone' ),
'background' => '#E8926F',
'linkType' => 0 ),
'welcome_item8' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'status',
'linkPage' => 'list',
'linkText' => array( 'table' => 'status',
'type' => 6 ),
'background' => '#E8926F',
'linkType' => 0 ),
'welcome_item9' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'un_med',
'linkPage' => 'list',
'linkText' => array( 'type' => 0,
'text' => 'Medidas' ),
'background' => '#00C2C5',
'linkType' => 0 ),
'welcome_item1' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'cidades',
'linkPage' => 'list',
'linkText' => array( 'table' => 'cidades',
'type' => 6 ),
'linkIcon' => array( 'glyph' => 'leaf' ),
'background' => '#E8926F',
'linkType' => 0 ),
'welcome_item7' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'tecnico',
'linkPage' => 'list',
'linkText' => array( 'type' => 0,
'text' => 'Técnico' ),
'background' => '#5F9EA0',
'linkType' => 0 ),
'welcome_item10' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'draes',
'linkPage' => 'list',
'linkText' => array( 'table' => 'draes',
'type' => 6 ),
'background' => '#E67349',
'linkType' => 0 ),
'welcome_item11' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'bairros',
'linkPage' => 'list',
'linkText' => array( 'table' => 'bairros',
'type' => 6 ),
'background' => '#6B8E23',
'linkType' => 0 ),
'welcome_item12' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'alternativa',
'linkPage' => 'list',
'linkText' => array( 'table' => 'alternativa',
'type' => 6 ),
'background' => '#B22222',
'linkType' => 0 ),
'welcome_item2' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'funcao',
'linkPage' => 'list',
'linkText' => array( 'table' => 'funcao',
'type' => 6 ),
'background' => '#1E90FF',
'linkType' => 0 ),
'welcome_item6' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'direcs',
'linkPage' => 'list',
'linkText' => array( 'table' => 'direcs',
'type' => 6 ),
'background' => '#DB7093',
'linkType' => 0 ),
'userinfo_link' => array( 'type' => 'userinfo_link' ),
'logout_link' => array( 'type' => 'logout_link' ),
'adminarea_link' => array( 'type' => 'adminarea_link' ),
'changepassword_link' => array( 'type' => 'changepassword_link' ),
'logo' => array( 'type' => 'logo' ),
'menu' => array( 'type' => 'menu',
'menuId' => 'main' ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'userinfo_link',
'logout_link',
'adminarea_link',
'changepassword_link' ) ),
'loginform_login' => array( 'type' => 'loginform_login',
'popup' => false ),
'expand_menu_button' => array( 'type' => 'expand_menu_button' ),
'collapse_button' => array( 'type' => 'collapse_button' ),
'welcome_item15' => array( 'type' => 'welcome_item',
'linkTable' => 'NP_escola',
'linkPage' => 'list',
'linkText' => array( 'type' => 0,
'text' => 'Pedidos Escola' ),
'linkType' => 0 ),
'welcome_item' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'Relatório Sintético de Escolas',
'linkPage' => 'report',
'linkText' => array( 'table' => 'Relatório Sintético de Escolas',
'type' => 6 ),
'background' => '#2F4F4F',
'linkType' => 0 ),
'welcome_item3' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'Relatório Analítico de Escolas',
'linkPage' => 'report',
'linkText' => array( 'table' => 'Relatório Analítico de Escolas',
'type' => 6 ),
'background' => '#6B8E23',
'linkType' => 0 ),
'notifications' => array( 'type' => 'notifications' ),
'welcome_item4' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'pedidos3_noti',
'linkPage' => 'list',
'linkText' => array( 'table' => 'pedidos3_noti',
'type' => 6 ),
'background' => '#9ACD32',
'linkType' => 0 ),
'welcome_item13' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'messages',
'linkPage' => 'list',
'linkText' => array( 'table' => 'messages',
'type' => 6 ),
'background' => '#DC143C',
'linkType' => 0 ),
'welcome_item14' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'arquivos',
'linkPage' => 'list',
'linkText' => array( 'table' => 'arquivos',
'type' => 6 ),
'background' => '#DAA520',
'linkType' => 0 ),
'welcome_item16' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'Selec_tec',
'linkPage' => 'list',
'linkText' => array( 'table' => 'Selec_tec',
'type' => 6 ),
'background' => '#D2AF80',
'linkType' => 0 ),
'welcome_item17' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'Seleciona_drae_novo',
'linkPage' => 'list',
'linkText' => array( 'table' => 'Seleciona_drae_novo',
'type' => 6 ),
'background' => '#7B68EE',
'linkType' => 0 ),
'expand_button' => array( 'type' => 'expand_button' ) ),
'dbProps' => array(  ),
'version' => 11,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'welcomePageStay' => false );
		?>