<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'cod_escola',
'CNPJ',
'Nome',
'Endereço',
'Email',
'Telefone',
'Descrição',
'Drae',
'Bairro',
'Cidade',
'Estado',
'Direc',
'Cep',
'Obs',
'EmailDrae',
'Municipio',
'fullname' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'cod_escola' => array( 'import_field' ),
'CNPJ' => array( 'import_field1' ),
'Nome' => array( 'import_field2' ),
'Endereço' => array( 'import_field3' ),
'Email' => array( 'import_field4' ),
'Telefone' => array( 'import_field5' ),
'Descrição' => array( 'import_field6' ),
'Drae' => array( 'import_field7' ),
'Bairro' => array( 'import_field8' ),
'Cidade' => array( 'import_field9' ),
'Estado' => array( 'import_field10' ),
'Direc' => array( 'import_field13' ),
'Cep' => array( 'import_field14' ),
'Obs' => array( 'import_field17' ),
'EmailDrae' => array( 'import_field18' ),
'Municipio' => array( 'import_field19' ),
'fullname' => array( 'import_field11' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field13',
'import_field14',
'import_field17',
'import_field18',
'import_field19',
'import_field11' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field' => 'grid',
'import_field1' => 'grid',
'import_field2' => 'grid',
'import_field3' => 'grid',
'import_field4' => 'grid',
'import_field5' => 'grid',
'import_field6' => 'grid',
'import_field7' => 'grid',
'import_field8' => 'grid',
'import_field9' => 'grid',
'import_field10' => 'grid',
'import_field13' => 'grid',
'import_field14' => 'grid',
'import_field17' => 'grid',
'import_field18' => 'grid',
'import_field19' => 'grid',
'import_field11' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field13',
'import_field14',
'import_field17',
'import_field18',
'import_field19',
'import_field11' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field13',
'import_field14',
'import_field17',
'import_field18',
'import_field19',
'import_field11' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field' => array( 'field' => 'cod_escola',
'type' => 'import_field' ),
'import_field1' => array( 'field' => 'CNPJ',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 'Nome',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 'Endereço',
'type' => 'import_field' ),
'import_field4' => array( 'field' => 'Email',
'type' => 'import_field' ),
'import_field5' => array( 'field' => 'Telefone',
'type' => 'import_field' ),
'import_field6' => array( 'field' => 'Descrição',
'type' => 'import_field' ),
'import_field7' => array( 'field' => 'Drae',
'type' => 'import_field' ),
'import_field8' => array( 'field' => 'Bairro',
'type' => 'import_field' ),
'import_field9' => array( 'field' => 'Cidade',
'type' => 'import_field' ),
'import_field10' => array( 'field' => 'Estado',
'type' => 'import_field' ),
'import_field13' => array( 'field' => 'Direc',
'type' => 'import_field' ),
'import_field14' => array( 'field' => 'Cep',
'type' => 'import_field' ),
'import_field17' => array( 'field' => 'Obs',
'type' => 'import_field' ),
'import_field18' => array( 'field' => 'EmailDrae',
'type' => 'import_field' ),
'import_field19' => array( 'field' => 'Municipio',
'type' => 'import_field' ),
'import_field11' => array( 'field' => 'fullname',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 11,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right' );
		?>