<?php
			$optionsArray = array( 'totals' => array( 'cod_escola' => array( 'totalsType' => '' ),
'CNPJ' => array( 'totalsType' => '' ),
'Nome' => array( 'totalsType' => '' ),
'Endereço' => array( 'totalsType' => '' ),
'Email' => array( 'totalsType' => '' ),
'Telefone' => array( 'totalsType' => '' ),
'Descrição' => array( 'totalsType' => '' ),
'Drae' => array( 'totalsType' => '' ),
'Bairro' => array( 'totalsType' => '' ),
'Cidade' => array( 'totalsType' => '' ),
'Estado' => array( 'totalsType' => '' ),
'Lat' => array( 'totalsType' => '' ),
'Lng' => array( 'totalsType' => '' ),
'Direc' => array( 'totalsType' => '' ),
'Cep' => array( 'totalsType' => '' ),
'Tec_resp' => array( 'totalsType' => '' ),
'Arquivos' => array( 'totalsType' => '' ),
'Obs' => array( 'totalsType' => '' ),
'EmailDrae' => array( 'totalsType' => '' ),
'Municipio' => array( 'totalsType' => '' ),
'cod_fee' => array( 'totalsType' => '' ),
'fullname' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'cod_escola',
'CNPJ',
'Nome',
'Endereço',
'Email',
'Telefone',
'Descrição',
'Drae',
'Bairro',
'Cidade',
'Estado',
'Direc',
'Cep',
'Obs',
'EmailDrae',
'Municipio',
'fullname' ),
'exportFields' => array( 'cod_escola',
'CNPJ',
'Nome',
'Endereço',
'Email',
'Telefone',
'Descrição',
'Drae',
'Bairro',
'Cidade',
'Estado',
'Direc',
'Cep',
'Obs',
'EmailDrae',
'Municipio',
'fullname' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'cod_escola' => array( 'export_field' ),
'CNPJ' => array( 'export_field1' ),
'Nome' => array( 'export_field2' ),
'Endereço' => array( 'export_field3' ),
'Email' => array( 'export_field4' ),
'Telefone' => array( 'export_field5' ),
'Descrição' => array( 'export_field6' ),
'Drae' => array( 'export_field7' ),
'Bairro' => array( 'export_field8' ),
'Cidade' => array( 'export_field9' ),
'Estado' => array( 'export_field10' ),
'Direc' => array( 'export_field13' ),
'Cep' => array( 'export_field14' ),
'Obs' => array( 'export_field17' ),
'EmailDrae' => array( 'export_field18' ),
'Municipio' => array( 'export_field19' ),
'fullname' => array( 'export_field11' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field13',
'export_field14',
'export_field17',
'export_field18',
'export_field19',
'export_field11' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field' => 'grid',
'export_field1' => 'grid',
'export_field2' => 'grid',
'export_field3' => 'grid',
'export_field4' => 'grid',
'export_field5' => 'grid',
'export_field6' => 'grid',
'export_field7' => 'grid',
'export_field8' => 'grid',
'export_field9' => 'grid',
'export_field10' => 'grid',
'export_field13' => 'grid',
'export_field14' => 'grid',
'export_field17' => 'grid',
'export_field18' => 'grid',
'export_field19' => 'grid',
'export_field11' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field13',
'export_field14',
'export_field17',
'export_field18',
'export_field19',
'export_field11' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field13',
'export_field14',
'export_field17',
'export_field18',
'export_field19',
'export_field11' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field' => array( 'field' => 'cod_escola',
'type' => 'export_field' ),
'export_field1' => array( 'field' => 'CNPJ',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'Nome',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'Endereço',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 'Email',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 'Telefone',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 'Descrição',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 'Drae',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'Bairro',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 'Cidade',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 'Estado',
'type' => 'export_field' ),
'export_field13' => array( 'field' => 'Direc',
'type' => 'export_field' ),
'export_field14' => array( 'field' => 'Cep',
'type' => 'export_field' ),
'export_field17' => array( 'field' => 'Obs',
'type' => 'export_field' ),
'export_field18' => array( 'field' => 'EmailDrae',
'type' => 'export_field' ),
'export_field19' => array( 'field' => 'Municipio',
'type' => 'export_field' ),
'export_field11' => array( 'field' => 'fullname',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 11,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>