<?php
			$optionsArray = array( 'pdf' => array( 'pdfView' => false ),
'details' => array( 'np' => array( 'displayPreview' => 2,
'previewPageId' => '' ) ),
'fields' => array( 'gridFields' => array( 'CNPJ',
'Email',
'Drae',
'Estado',
'Direc',
'Municipio',
'Nome',
'Telefone',
'Bairro',
'Cep',
'Obs',
'Endereço',
'Descrição',
'EmailDrae',
'cod_escola',
'Cidade',
'fullname' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'CNPJ' => array( 'integrated_edit_field' ),
'Email' => array( 'integrated_edit_field3' ),
'Drae' => array( 'integrated_edit_field6' ),
'Estado' => array( 'integrated_edit_field9' ),
'Direc' => array( 'integrated_edit_field12' ),
'Municipio' => array( 'integrated_edit_field18' ),
'Nome' => array( 'integrated_edit_field1' ),
'Telefone' => array( 'integrated_edit_field4' ),
'Bairro' => array( 'integrated_edit_field7' ),
'Cep' => array( 'integrated_edit_field13' ),
'Obs' => array( 'integrated_edit_field16' ),
'Endereço' => array( 'integrated_edit_field2' ),
'Descrição' => array( 'integrated_edit_field5' ),
'EmailDrae' => array( 'integrated_edit_field17' ),
'cod_escola' => array( 'integrated_edit_field8' ),
'Cidade' => array( 'integrated_edit_field20' ),
'fullname' => array( 'integrated_edit_field10' ) ) ),
'pageLinks' => array( 'edit' => true,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array(  ),
'below-grid' => array( 'view_back_list',
'view_close',
'hamburger' ),
'supertop' => array( 'expand_menu_button',
'collapse_button',
'notifications',
'loginform_login',
'username_button' ),
'left' => array( 'logo',
'expand_button',
'menu' ),
'top' => array( 'view_header' ),
'grid' => array( 'tabs',
'integrated_edit_field10' ),
'section' => array( 'integrated_edit_field1',
'integrated_edit_field2',
'integrated_edit_field12',
'integrated_edit_field20',
'integrated_edit_field9',
'integrated_edit_field13',
'integrated_edit_field7',
'integrated_edit_field6',
'integrated_edit_field18',
'integrated_edit_field8',
'integrated_edit_field' ),
'section1' => array( 'integrated_edit_field16',
'integrated_edit_field3',
'integrated_edit_field17',
'integrated_edit_field4',
'integrated_edit_field5' ) ),
'formXtTags' => array( 'above-grid' => array(  ) ),
'itemForms' => array( 'view_back_list' => 'below-grid',
'view_close' => 'below-grid',
'hamburger' => 'below-grid',
'expand_menu_button' => 'supertop',
'collapse_button' => 'supertop',
'notifications' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'logo' => 'left',
'expand_button' => 'left',
'menu' => 'left',
'view_header' => 'top',
'tabs' => 'grid',
'integrated_edit_field10' => 'grid',
'integrated_edit_field1' => 'section',
'integrated_edit_field2' => 'section',
'integrated_edit_field12' => 'section',
'integrated_edit_field20' => 'section',
'integrated_edit_field9' => 'section',
'integrated_edit_field13' => 'section',
'integrated_edit_field7' => 'section',
'integrated_edit_field6' => 'section',
'integrated_edit_field18' => 'section',
'integrated_edit_field8' => 'section',
'integrated_edit_field' => 'section',
'integrated_edit_field16' => 'section1',
'integrated_edit_field3' => 'section1',
'integrated_edit_field17' => 'section1',
'integrated_edit_field4' => 'section1',
'integrated_edit_field5' => 'section1' ),
'itemLocations' => array( 'tabs' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field10' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field1' => array( 'location' => 'section',
'cellId' => 'c' ),
'integrated_edit_field2' => array( 'location' => 'section',
'cellId' => 'c2' ),
'integrated_edit_field12' => array( 'location' => 'section',
'cellId' => 'c5' ),
'integrated_edit_field20' => array( 'location' => 'section',
'cellId' => 'c6' ),
'integrated_edit_field9' => array( 'location' => 'section',
'cellId' => 'c7' ),
'integrated_edit_field13' => array( 'location' => 'section',
'cellId' => 'c8' ),
'integrated_edit_field7' => array( 'location' => 'section',
'cellId' => 'c9' ),
'integrated_edit_field6' => array( 'location' => 'section',
'cellId' => 'c10' ),
'integrated_edit_field18' => array( 'location' => 'section',
'cellId' => 'c13' ),
'integrated_edit_field8' => array( 'location' => 'section',
'cellId' => 'c15' ),
'integrated_edit_field' => array( 'location' => 'section',
'cellId' => 'c15' ),
'integrated_edit_field16' => array( 'location' => 'section1',
'cellId' => 'c1' ),
'integrated_edit_field3' => array( 'location' => 'section1',
'cellId' => 'c' ),
'integrated_edit_field17' => array( 'location' => 'section1',
'cellId' => 'c6' ),
'integrated_edit_field4' => array( 'location' => 'section1',
'cellId' => 'c7' ),
'integrated_edit_field5' => array( 'location' => 'section1',
'cellId' => 'c8' ) ),
'itemVisiblity' => array( 'expand_menu_button' => 2,
'expand_button' => 5 ) ),
'itemsByType' => array( 'view_header' => array( 'view_header' ),
'view_back_list' => array( 'view_back_list' ),
'view_close' => array( 'view_close' ),
'hamburger' => array( 'hamburger' ),
'view_edit' => array( 'view_edit' ),
'integrated_edit_field' => array( 'integrated_edit_field',
'integrated_edit_field3',
'integrated_edit_field6',
'integrated_edit_field9',
'integrated_edit_field12',
'integrated_edit_field18',
'integrated_edit_field1',
'integrated_edit_field4',
'integrated_edit_field7',
'integrated_edit_field13',
'integrated_edit_field16',
'integrated_edit_field2',
'integrated_edit_field5',
'integrated_edit_field17',
'integrated_edit_field8',
'integrated_edit_field20',
'integrated_edit_field10' ),
'logo' => array( 'logo' ),
'menu' => array( 'menu' ),
'username_button' => array( 'username_button' ),
'loginform_login' => array( 'loginform_login' ),
'userinfo_link' => array( 'userinfo_link' ),
'logout_link' => array( 'logout_link' ),
'expand_menu_button' => array( 'expand_menu_button' ),
'collapse_button' => array( 'collapse_button' ),
'tabs' => array( 'tabs' ),
'changepassword_link' => array( 'changepassword_link' ),
'notifications' => array( 'notifications' ),
'expand_button' => array( 'expand_button' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c3' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'tabs',
'integrated_edit_field10' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section' => array( 'cells' => array( 'c15' => array( 'cols' => array( 0,
1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field8',
'integrated_edit_field' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 2,
3 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c1' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 1,
2 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c9' => array( 'cols' => array( 3 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field7' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c13' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field18' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c7' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field9' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c8' => array( 'cols' => array( 2 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field13' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c10' => array( 'cols' => array( 3 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field6' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c5' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field12' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c6' => array( 'cols' => array( 1 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field20' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c14' => array( 'cols' => array( 2 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c11' => array( 'cols' => array( 3 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 4,
'height' => 4 ),
'section1' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field16' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field3' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c8' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field5' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c6' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field17' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c9' => array( 'cols' => array( 2 ),
'rows' => array( 1,
2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c7' => array( 'cols' => array( 0 ),
'rows' => array( 2,
3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field4' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c5' => array( 'cols' => array( 1 ),
'rows' => array( 2,
3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c3' => array( 'cols' => array( 2 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 3,
'height' => 4 ) ) ),
'loginForm' => array( 'loginForm' => 0 ),
'page' => array( 'verticalBar' => true,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => true ),
'misc' => array( 'type' => 'view',
'breadcrumb' => false,
'nextPrev' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'view',
'type' => 'view',
'layoutId' => 'leftbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'above-grid' => array( 'modelId' => 'view-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1',
'colspan' => 2 ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'view-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'view_back_list',
'view_close' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'hamburger' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'supertop' => array( 'modelId' => 'leftbar-top-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'expand_menu_button',
'collapse_button' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'notifications',
'loginform_login',
'username_button' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'left' => array( 'modelId' => 'leftbar-menu',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c0' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c0' => array( 'model' => 'c0',
'items' => array( 'logo',
'expand_button' ) ),
'c1' => array( 'model' => 'c1',
'items' => array( 'menu' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'view-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'view_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c3' ) ),
'section' => '' ) ),
'cells' => array( 'c3' => array( 'model' => 'c3',
'items' => array( 'tabs',
'integrated_edit_field10' ),
'useFullWidth' => true ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c15',
'colspan' => 2 ),
array( 'cell' => 'c',
'colspan' => 2 ) ) ),
array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2',
'colspan' => 2 ),
array( 'cell' => 'c9' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c13' ),
array( 'cell' => 'c7' ),
array( 'cell' => 'c8' ),
array( 'cell' => 'c10' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c5' ),
array( 'cell' => 'c6' ),
array( 'cell' => 'c14' ),
array( 'cell' => 'c11' ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'orientation' => 'horizontal' ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field1' ),
'orientation' => 'horizontal',
'nowrap' => true,
'useFullWidth' => true ),
'c2' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field2' ),
'orientation' => 'horizontal' ),
'c5' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field12' ),
'orientation' => 'horizontal' ),
'c6' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field20' ),
'orientation' => 'horizontal' ),
'c7' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field9' ),
'orientation' => 'horizontal' ),
'c8' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field13' ),
'orientation' => 'horizontal' ),
'c9' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field7' ) ),
'c10' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field6' ) ),
'c11' => array( 'model' => 'c1',
'items' => array(  ) ),
'c13' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field18' ),
'orientation' => 'horizontal' ),
'c14' => array( 'model' => 'c1',
'items' => array(  ),
'orientation' => 'horizontal' ),
'c15' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field8',
'integrated_edit_field' ),
'orientation' => 'horizontal',
'nowrap' => true,
'useFullWidth' => true ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section1' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ),
array( 'cell' => 'c' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c8' ),
array( 'cell' => 'c6' ),
array( 'cell' => 'c9',
'rowspan' => 2 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c7',
'rowspan' => 2 ),
array( 'cell' => 'c5',
'rowspan' => 2 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c3' ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field16' ),
'orientation' => 'horizontal' ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field3' ),
'orientation' => 'horizontal' ),
'c2' => array( 'model' => 'c1',
'items' => array(  ),
'orientation' => 'horizontal' ),
'c3' => array( 'model' => 'c1',
'items' => array(  ),
'orientation' => 'horizontal' ),
'c5' => array( 'model' => 'c1',
'items' => array(  ),
'orientation' => 'horizontal' ),
'c6' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field17' ),
'orientation' => 'horizontal' ),
'c7' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field4' ),
'orientation' => 'horizontal' ),
'c8' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field5' ),
'orientation' => 'horizontal' ),
'c9' => array( 'model' => 'c1',
'items' => array(  ),
'orientation' => 'horizontal' ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ) ),
'items' => array( 'view_header' => array( 'type' => 'view_header' ),
'view_back_list' => array( 'type' => 'view_back_list' ),
'view_close' => array( 'type' => 'view_close' ),
'hamburger' => array( 'type' => 'hamburger',
'items' => array( 'view_edit' ) ),
'view_edit' => array( 'type' => 'view_edit' ),
'integrated_edit_field' => array( 'field' => 'CNPJ',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field3' => array( 'field' => 'Email',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field6' => array( 'field' => 'Drae',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field9' => array( 'field' => 'Estado',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field12' => array( 'field' => 'Direc',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field18' => array( 'field' => 'Municipio',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field1' => array( 'field' => 'Nome',
'type' => 'integrated_edit_field',
'orientation' => 0,
'nowrap' => true ),
'integrated_edit_field4' => array( 'field' => 'Telefone',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field7' => array( 'field' => 'Bairro',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field13' => array( 'field' => 'Cep',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field16' => array( 'field' => 'Obs',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field2' => array( 'field' => 'Endereço',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field5' => array( 'field' => 'Descrição',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field17' => array( 'field' => 'EmailDrae',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'logo' => array( 'type' => 'logo' ),
'menu' => array( 'type' => 'menu',
'menuId' => 'main' ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'userinfo_link',
'logout_link',
'changepassword_link' ) ),
'loginform_login' => array( 'type' => 'loginform_login' ),
'userinfo_link' => array( 'type' => 'userinfo_link' ),
'logout_link' => array( 'type' => 'logout_link' ),
'expand_menu_button' => array( 'type' => 'expand_menu_button' ),
'collapse_button' => array( 'type' => 'collapse_button' ),
'tabs' => array( 'type' => 'tabs',
'titles' => array( array( 'text' => 'Identificação',
'type' => 0 ),
array( 'text' => 'Outros',
'type' => 0 ) ),
'locations' => array( 'section',
'section1' ),
'bsStyle' => 'default',
'panelType' => 2 ),
'integrated_edit_field8' => array( 'field' => 'cod_escola',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'cod_escola',
'table' => 'escolas',
'type' => 3 ) ),
'integrated_edit_field20' => array( 'field' => 'Cidade',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'changepassword_link' => array( 'type' => 'changepassword_link' ),
'notifications' => array( 'type' => 'notifications' ),
'integrated_edit_field10' => array( 'field' => 'fullname',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'expand_button' => array( 'type' => 'expand_button' ) ),
'dbProps' => array(  ),
'version' => 11,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right' );
		?>