<?php
			$optionsArray = array( 'pdf' => array( 'pdfView' => false ),
'master' => array( 'pedidos_view' => array( 'preview' => true ) ),
'totals' => array( 'cod' => array( 'totalsType' => '' ),
'cod_ped' => array( 'totalsType' => '' ),
'genero' => array( 'totalsType' => '' ),
'qtd' => array( 'totalsType' => '' ),
'valor' => array( 'totalsType' => '' ),
'total' => array( 'totalsType' => 'TOTAL' ),
'cod_np' => array( 'totalsType' => '' ),
'Nome' => array( 'totalsType' => '' ),
'Und' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'qtd',
'valor',
'total',
'genero',
'Und' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'qtd' => array( 'simple_grid_field3',
'simple_grid_field11' ),
'valor' => array( 'simple_grid_field4',
'simple_grid_field13' ),
'total' => array( 'simple_grid_field5',
'simple_grid_field14',
'simple_grid_field15' ),
'genero' => array( 'grid_field',
'grid_field_label' ),
'Und' => array( 'grid_field1',
'grid_field_label1' ) ),
'hideEmptyFields' => array(  ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array( 'print_pages',
'grid_inline_cancel',
'inline_add' ),
'below-grid' => array(  ),
'top' => array( 'print_header',
'print_subheader',
'master_info',
'image' ),
'grid' => array( 'simple_grid_field11',
'simple_grid_field3',
'grid_field_label1',
'grid_field1',
'simple_grid_field13',
'simple_grid_field4',
'grid_field_label',
'grid_field',
'simple_grid_field14',
'simple_grid_field5',
'simple_grid_field15',
'image1' ) ),
'formXtTags' => array( 'above-grid' => array( 'print_pages',
'inline_cancel',
'inlineadd_link' ),
'below-grid' => array(  ) ),
'itemForms' => array( 'print_pages' => 'above-grid',
'grid_inline_cancel' => 'above-grid',
'inline_add' => 'above-grid',
'print_header' => 'top',
'print_subheader' => 'top',
'master_info' => 'top',
'image' => 'top',
'simple_grid_field11' => 'grid',
'simple_grid_field3' => 'grid',
'grid_field_label1' => 'grid',
'grid_field1' => 'grid',
'simple_grid_field13' => 'grid',
'simple_grid_field4' => 'grid',
'grid_field_label' => 'grid',
'grid_field' => 'grid',
'simple_grid_field14' => 'grid',
'simple_grid_field5' => 'grid',
'simple_grid_field15' => 'grid',
'image1' => 'grid' ),
'itemLocations' => array( 'simple_grid_field11' => array( 'location' => 'grid',
'cellId' => 'headcell_field4' ),
'simple_grid_field3' => array( 'location' => 'grid',
'cellId' => 'cell_field4' ),
'grid_field_label1' => array( 'location' => 'grid',
'cellId' => 'headcell_field5' ),
'grid_field1' => array( 'location' => 'grid',
'cellId' => 'cell_field5' ),
'simple_grid_field13' => array( 'location' => 'grid',
'cellId' => 'headcell_field6' ),
'simple_grid_field4' => array( 'location' => 'grid',
'cellId' => 'cell_field6' ),
'grid_field_label' => array( 'location' => 'grid',
'cellId' => 'cell_field7' ),
'grid_field' => array( 'location' => 'grid',
'cellId' => 'cell_field8' ),
'simple_grid_field14' => array( 'location' => 'grid',
'cellId' => 'footcell_field22' ),
'simple_grid_field5' => array( 'location' => 'grid',
'cellId' => 'footcell_field23' ),
'simple_grid_field15' => array( 'location' => 'grid',
'cellId' => 'footcell_field25' ),
'image1' => array( 'location' => 'grid',
'cellId' => 'footcell_field12' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'print_header' => array( 'print_header' ),
'print_subheader' => array( 'print_subheader' ),
'print_pages' => array( 'print_pages' ),
'grid_field' => array( 'simple_grid_field3',
'simple_grid_field4',
'simple_grid_field5',
'grid_field',
'grid_field1' ),
'master_info' => array( 'master_info' ),
'grid_field_label' => array( 'simple_grid_field11',
'simple_grid_field13',
'simple_grid_field14',
'grid_field_label',
'grid_field_label1' ),
'grid_field_totals' => array( 'simple_grid_field15' ),
'image' => array( 'image',
'image1' ),
'inline_add' => array( 'inline_add' ),
'grid_inline_cancel' => array( 'grid_inline_cancel' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'cell_field7' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array( 'genero_fieldheadercolumn' ),
'items' => array( 'grid_field_label' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field4' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array( 'qtd_fieldheadercolumn' ),
'items' => array( 'simple_grid_field11' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field5' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array( 'Und_fieldheadercolumn' ),
'items' => array( 'grid_field_label1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field6' => array( 'cols' => array( 3 ),
'rows' => array( 0 ),
'tags' => array( 'valor_fieldheadercolumn' ),
'items' => array( 'simple_grid_field13' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field22' => array( 'cols' => array( 4 ),
'rows' => array( 0 ),
'tags' => array( 'total_fieldheadercolumn' ),
'items' => array( 'simple_grid_field14' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field' => array( 'cols' => array( 5 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field8' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array( 'genero_fieldcolumn' ),
'items' => array( 'grid_field' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field4' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array( 'qtd_fieldcolumn' ),
'items' => array( 'simple_grid_field3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field5' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array( 'Und_fieldcolumn' ),
'items' => array( 'grid_field1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field6' => array( 'cols' => array( 3 ),
'rows' => array( 1 ),
'tags' => array( 'valor_fieldcolumn' ),
'items' => array( 'simple_grid_field4' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field23' => array( 'cols' => array( 4 ),
'rows' => array( 1 ),
'tags' => array( 'total_fieldcolumn' ),
'items' => array( 'simple_grid_field5' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field' => array( 'cols' => array( 5 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field9' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field4' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field5' => array( 'cols' => array( 2 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field6' => array( 'cols' => array( 3 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field25' => array( 'cols' => array( 4 ),
'rows' => array( 2 ),
'tags' => array( 'total_fieldfootercolumn' ),
'items' => array( 'simple_grid_field15' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field1' => array( 'cols' => array( 5 ),
'rows' => array( 2,
3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field18' => array( 'cols' => array( 0,
1,
2,
3 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field27' => array( 'cols' => array( 4 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field14' => array( 'cols' => array( 0 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field15' => array( 'cols' => array( 1,
2 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field17' => array( 'cols' => array( 3 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field26' => array( 'cols' => array( 4 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field2' => array( 'cols' => array( 5 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field10' => array( 'cols' => array( 0 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field13' => array( 'cols' => array( 1 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field12' => array( 'cols' => array( 2,
3,
4 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array( 'image1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'footcell_field3' => array( 'cols' => array( 5 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field' => array( 'cols' => array( 0,
1 ),
'rows' => array( 6 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field8' => array( 'cols' => array( 2 ),
'rows' => array( 6 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field9' => array( 'cols' => array( 3,
4 ),
'rows' => array( 6 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field11' => array( 'cols' => array( 5 ),
'rows' => array( 6 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 6,
'height' => 7 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array( 'print_pages' => array( 'tag' => 'PRINT_PAGES',
'type' => 2 ) ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'gridType' => 0,
'recsPerRow' => 1,
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false ),
'misc' => array( 'type' => 'print',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'dataGrid' => array( 'groupFields' => array(  ) ) );
			$pageArray = array( 'id' => 'print',
'type' => 'print',
'layoutId' => 'basic',
'disabled' => 0,
'default' => 0,
'forms' => array( 'above-grid' => array( 'modelId' => 'print-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'print_pages',
'grid_inline_cancel',
'inline_add' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'print-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'print-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c2',
'colspan' => 2 ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c' ),
array( 'cell' => 'c1' ) ) ),
array( 'cells' => array( array( 'cell' => 'c4',
'colspan' => 2 ) ),
'section' => '' ) ),
'cells' => array( 'c2' => array( 'model' => 'c2',
'items' => array( 'print_header',
'print_subheader' ) ),
'c4' => array( 'model' => 'c4',
'items' => array( 'master_info' ) ),
'c' => array( 'model' => 'c4',
'items' => array(  ) ),
'c1' => array( 'model' => 'c4',
'items' => array( 'image' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'horizontal-grid',
'grid' => array( array( 'section' => 'head',
'cells' => array( array( 'cell' => 'cell_field7' ),
array( 'cell' => 'headcell_field4' ),
array( 'cell' => 'headcell_field5' ),
array( 'cell' => 'headcell_field6' ),
array( 'cell' => 'footcell_field22' ),
array( 'cell' => 'headcell_field' ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_field8' ),
array( 'cell' => 'cell_field4' ),
array( 'cell' => 'cell_field5' ),
array( 'cell' => 'cell_field6' ),
array( 'cell' => 'footcell_field23' ),
array( 'cell' => 'cell_field' ) ) ),
array( 'section' => 'foot',
'cells' => array( array( 'cell' => 'cell_field9' ),
array( 'cell' => 'footcell_field4' ),
array( 'cell' => 'footcell_field5' ),
array( 'cell' => 'footcell_field6' ),
array( 'cell' => 'footcell_field25' ),
array( 'cell' => 'footcell_field1',
'rowspan' => 2 ) ) ),
array( 'section' => 'foot',
'cells' => array( array( 'cell' => 'footcell_field18',
'colspan' => 4 ),
array( 'cell' => 'footcell_field27' ) ) ),
array( 'section' => 'foot',
'cells' => array( array( 'cell' => 'footcell_field14' ),
array( 'cell' => 'footcell_field15',
'colspan' => 2 ),
array( 'cell' => 'footcell_field17' ),
array( 'cell' => 'footcell_field26' ),
array( 'cell' => 'footcell_field2' ) ) ),
array( 'section' => 'foot',
'cells' => array( array( 'cell' => 'footcell_field10' ),
array( 'cell' => 'footcell_field13' ),
array( 'cell' => 'footcell_field12',
'colspan' => 3 ),
array( 'cell' => 'footcell_field3' ) ) ),
array( 'section' => 'foot',
'cells' => array( array( 'cell' => 'footcell_field',
'colspan' => 2 ),
array( 'cell' => 'footcell_field8' ),
array( 'cell' => 'footcell_field9',
'colspan' => 2 ),
array( 'cell' => 'footcell_field11' ) ) ) ),
'cells' => array( 'headcell_field4' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field11' ),
'align' => 'left',
'field' => 'qtd',
'columnName' => 'field' ),
'cell_field4' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field3' ),
'align' => 'left',
'field' => 'qtd',
'columnName' => 'field' ),
'footcell_field4' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field5' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label1' ),
'align' => 'left',
'field' => 'Und',
'columnName' => 'field' ),
'cell_field5' => array( 'model' => 'cell_field',
'items' => array( 'grid_field1' ),
'align' => 'left',
'field' => 'Und',
'columnName' => 'field' ),
'footcell_field5' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field6' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field13' ),
'align' => 'left',
'field' => 'valor',
'columnName' => 'field' ),
'cell_field6' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field4' ),
'align' => 'left',
'field' => 'valor',
'columnName' => 'field' ),
'footcell_field6' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'cell_field7' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label' ),
'align' => 'left',
'field' => 'genero',
'columnName' => 'field' ),
'cell_field8' => array( 'model' => 'cell_field',
'items' => array( 'grid_field' ),
'align' => 'left',
'field' => 'genero',
'columnName' => 'field' ),
'cell_field9' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'footcell_field' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'footcell_field8' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'footcell_field9' => array( 'model' => 'footcell_field',
'items' => array(  ),
'align' => 'right' ),
'footcell_field10' => array( 'model' => 'footcell_field',
'items' => array(  ),
'align' => 'center' ),
'footcell_field11' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'footcell_field14' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'footcell_field15' => array( 'model' => 'footcell_field',
'items' => array(  ),
'align' => 'center' ),
'footcell_field17' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'footcell_field18' => array( 'model' => 'footcell_field',
'items' => array(  ),
'align' => 'right' ),
'footcell_field22' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field14' ),
'align' => 'left',
'field' => 'total',
'columnName' => 'field' ),
'footcell_field23' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field5' ),
'align' => 'left',
'field' => 'total',
'columnName' => 'field' ),
'footcell_field25' => array( 'model' => 'footcell_field',
'items' => array( 'simple_grid_field15' ),
'align' => 'left',
'field' => 'total',
'columnName' => 'field' ),
'footcell_field26' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field' => array( 'model' => 'headcell_field',
'items' => array(  ) ),
'cell_field' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'footcell_field1' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'footcell_field2' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'footcell_field3' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'footcell_field12' => array( 'model' => 'footcell_field',
'items' => array( 'image1' ),
'align' => 'center' ),
'footcell_field13' => array( 'model' => 'footcell_field',
'items' => array(  ),
'align' => 'center' ),
'footcell_field27' => array( 'model' => 'footcell_field',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'print_header' => array( 'type' => 'print_header',
'title' => array( 'page' => 'print',
'table' => 'itens_view',
'type' => 7 ),
'color' => '#ffffff' ),
'print_subheader' => array( 'type' => 'print_subheader' ),
'print_pages' => array( 'type' => 'print_pages' ),
'simple_grid_field3' => array( 'field' => 'qtd',
'type' => 'grid_field' ),
'simple_grid_field4' => array( 'field' => 'valor',
'type' => 'grid_field' ),
'simple_grid_field5' => array( 'field' => 'total',
'type' => 'grid_field' ),
'master_info' => array( 'type' => 'master_info',
'tables' => array( 'pedidos_view' => 'true' ) ),
'simple_grid_field11' => array( 'type' => 'grid_field_label',
'field' => 'qtd' ),
'simple_grid_field13' => array( 'type' => 'grid_field_label',
'field' => 'valor' ),
'simple_grid_field14' => array( 'type' => 'grid_field_label',
'field' => 'total' ),
'simple_grid_field15' => array( 'type' => 'grid_field_totals',
'field' => 'total',
'totals' => 'TOTAL' ),
'grid_field' => array( 'field' => 'genero',
'type' => 'grid_field' ),
'grid_field_label' => array( 'type' => 'grid_field_label',
'field' => 'genero' ),
'image' => array( 'type' => 'image',
'image' => array( 'image' => 'brasao.png',
'source' => 2 ) ),
'image1' => array( 'type' => 'image',
'image' => array( 'image' => 'certifico2.png',
'source' => 2 ) ),
'grid_field1' => array( 'field' => 'Und',
'type' => 'grid_field' ),
'grid_field_label1' => array( 'type' => 'grid_field_label',
'field' => 'Und' ),
'inline_add' => array( 'type' => 'inline_add',
'detailsOnly' => true ),
'grid_inline_cancel' => array( 'type' => 'grid_inline_cancel' ) ),
'dbProps' => array(  ),
'version' => 11,
'pageWidth' => 'standard',
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right' );
		?>