<?php
			$optionsArray = array( 'list' => array( 'inlineAdd' => false,
'detailsAdd' => false,
'inlineEdit' => false,
'spreadsheetMode' => false,
'reorderRows' => false,
'addToBottom' => false,
'delete' => true,
'updateSelected' => false,
'addInPopup' => false,
'editInPopup' => false,
'viewInPopup' => null,
'clickSort' => true,
'sortDropdown' => false,
'showHideFields' => false,
'reorderFields' => false ),
'allDetails' => array( 'linkType' => 1 ),
'details' => array( 'Pedidos_escola' => array( 'displayPreview' => 2,
'previewPageId' => '',
'showCount' => true,
'hideEmptyChild' => false,
'hideEmptyPreview' => null,
'showProceedLink' => null,
'printDetails' => false ) ),
'listSearch' => array( 'alwaysOnPanelFields' => array(  ),
'searchPanel' => true,
'fixedSearchPanel' => false,
'simpleSearchOptions' => false,
'searchSaving' => false ),
'totals' => array( 'Cod_NP' => array( 'totalsType' => '' ),
'Parcela' => array( 'totalsType' => '' ),
'Data' => array( 'totalsType' => '' ),
'Valor' => array( 'totalsType' => 'TOTAL' ),
'Saldo' => array( 'totalsType' => '' ),
'Escola' => array( 'totalsType' => '' ),
'Num_NP' => array( 'totalsType' => '' ),
'Execício' => array( 'totalsType' => '' ),
'Debito' => array( 'totalsType' => 'TOTAL' ),
'Nome' => array( 'totalsType' => '' ),
'saldo1' => array( 'totalsType' => 'TOTAL' ),
'agf' => array( 'totalsType' => 'TOTAL' ),
'Endereço' => array( 'totalsType' => '' ),
'Bairro' => array( 'totalsType' => '' ),
'Municipio' => array( 'totalsType' => '' ),
'Direc' => array( 'totalsType' => '' ),
'Drae' => array( 'totalsType' => '' ),
'Sd_ant' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'Num_NP',
'Parcela',
'Data',
'Execício',
'Sd_ant',
'Saldo',
'Valor',
'agf',
'Debito',
'saldo1' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array( 'agf',
'Saldo',
'Sd_ant',
'Drae',
'Direc',
'Municipio',
'Bairro',
'Endereço',
'saldo1',
'Nome',
'Valor',
'Parcela',
'Num_NP',
'Execício',
'Escola',
'Data' ),
'filterFields' => array(  ),
'inlineAddFields' => array(  ),
'inlineEditFields' => array(  ),
'fieldItems' => array( 'Parcela' => array( 'grid_field_label1',
'grid_field1' ),
'agf' => array( 'grid_field6',
'grid_field_label6',
'grid_field_totals' ),
'Debito' => array( 'grid_field8',
'grid_field_label8',
'grid_field_totals1' ),
'Valor' => array( 'grid_field_totals2',
'grid_field3',
'grid_field_label3' ),
'Execício' => array( 'grid_field7',
'grid_field_label7' ),
'Data' => array( 'grid_field2',
'grid_field_label2' ),
'saldo1' => array( 'grid_field4',
'grid_field_label4',
'grid_field_totals3' ),
'Num_NP' => array( 'grid_field5',
'grid_field_label5' ),
'Sd_ant' => array( 'grid_field',
'grid_field_label' ),
'Saldo' => array( 'grid_field9',
'grid_field_label9' ) ),
'hideEmptyFields' => array(  ) ),
'pageLinks' => array( 'edit' => true,
'add' => true,
'view' => false,
'print' => true ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array( 'add',
'delete',
'details_found',
'page_size',
'print_panel',
'text' ),
'below-grid' => array( 'pagination' ),
'left' => array( 'logo',
'expand_button',
'menu',
'search_panel' ),
'supertop' => array( 'expand_menu_button',
'collapse_button',
'simple_search',
'list_options',
'notifications',
'loginform_login',
'username_button' ),
'grid' => array( 'grid_field_label2',
'grid_field2',
'grid_field_totals1',
'grid_field_label7',
'grid_field7',
'grid_checkbox_head',
'grid_checkbox',
'grid_edit',
'grid_details_link',
'grid_details_link1',
'grid_field_label3',
'grid_field3',
'grid_field_totals2',
'grid_field_totals',
'grid_field_label6',
'grid_field6',
'grid_field_label8',
'grid_field8',
'grid_field_label4',
'grid_field4',
'grid_field_totals3',
'grid_field1',
'grid_field_label1',
'grid_field_label',
'grid_field',
'grid_field_label9',
'grid_field9',
'grid_field_label5',
'grid_field5' ),
'top' => array(  ) ),
'formXtTags' => array( 'below-grid' => array( 'pagination' ),
'top' => array(  ) ),
'itemForms' => array( 'add' => 'above-grid',
'delete' => 'above-grid',
'details_found' => 'above-grid',
'page_size' => 'above-grid',
'print_panel' => 'above-grid',
'text' => 'above-grid',
'pagination' => 'below-grid',
'logo' => 'left',
'expand_button' => 'left',
'menu' => 'left',
'search_panel' => 'left',
'expand_menu_button' => 'supertop',
'collapse_button' => 'supertop',
'simple_search' => 'supertop',
'list_options' => 'supertop',
'notifications' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'grid_field_label2' => 'grid',
'grid_field2' => 'grid',
'grid_field_totals1' => 'grid',
'grid_field_label7' => 'grid',
'grid_field7' => 'grid',
'grid_checkbox_head' => 'grid',
'grid_checkbox' => 'grid',
'grid_edit' => 'grid',
'grid_details_link' => 'grid',
'grid_details_link1' => 'grid',
'grid_field_label3' => 'grid',
'grid_field3' => 'grid',
'grid_field_totals2' => 'grid',
'grid_field_totals' => 'grid',
'grid_field_label6' => 'grid',
'grid_field6' => 'grid',
'grid_field_label8' => 'grid',
'grid_field8' => 'grid',
'grid_field_label4' => 'grid',
'grid_field4' => 'grid',
'grid_field_totals3' => 'grid',
'grid_field1' => 'grid',
'grid_field_label1' => 'grid',
'grid_field_label' => 'grid',
'grid_field' => 'grid',
'grid_field_label9' => 'grid',
'grid_field9' => 'grid',
'grid_field_label5' => 'grid',
'grid_field5' => 'grid' ),
'itemLocations' => array( 'grid_field_label2' => array( 'location' => 'grid',
'cellId' => 'headcell_field2' ),
'grid_field2' => array( 'location' => 'grid',
'cellId' => 'cell_field2' ),
'grid_field_totals1' => array( 'location' => 'grid',
'cellId' => 'footcell_field3' ),
'grid_field_label7' => array( 'location' => 'grid',
'cellId' => 'headcell_field5' ),
'grid_field7' => array( 'location' => 'grid',
'cellId' => 'cell_field5' ),
'grid_checkbox_head' => array( 'location' => 'grid',
'cellId' => 'headcell_checkbox' ),
'grid_checkbox' => array( 'location' => 'grid',
'cellId' => 'cell_checkbox' ),
'grid_edit' => array( 'location' => 'grid',
'cellId' => 'cell_icons' ),
'grid_details_link' => array( 'location' => 'grid',
'cellId' => 'cell_details' ),
'grid_details_link1' => array( 'location' => 'grid',
'cellId' => 'cell_details' ),
'grid_field_label3' => array( 'location' => 'grid',
'cellId' => 'headcell_field7' ),
'grid_field3' => array( 'location' => 'grid',
'cellId' => 'cell_field7' ),
'grid_field_totals2' => array( 'location' => 'grid',
'cellId' => 'footcell_field7' ),
'grid_field_totals' => array( 'location' => 'grid',
'cellId' => 'footcell_field' ),
'grid_field_label6' => array( 'location' => 'grid',
'cellId' => 'headcell_field10' ),
'grid_field6' => array( 'location' => 'grid',
'cellId' => 'cell_field10' ),
'grid_field_label8' => array( 'location' => 'grid',
'cellId' => 'headcell_field' ),
'grid_field8' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'grid_field_label4' => array( 'location' => 'grid',
'cellId' => 'headcell_field4' ),
'grid_field4' => array( 'location' => 'grid',
'cellId' => 'cell_field4' ),
'grid_field_totals3' => array( 'location' => 'grid',
'cellId' => 'footcell_field16' ),
'grid_field1' => array( 'location' => 'grid',
'cellId' => 'cell_field12' ),
'grid_field_label1' => array( 'location' => 'grid',
'cellId' => 'headcell_field12' ),
'grid_field_label' => array( 'location' => 'grid',
'cellId' => 'headcell_field8' ),
'grid_field' => array( 'location' => 'grid',
'cellId' => 'headcell_field9' ),
'grid_field_label9' => array( 'location' => 'grid',
'cellId' => 'headcell_field14' ),
'grid_field9' => array( 'location' => 'grid',
'cellId' => 'headcell_field15' ),
'grid_field_label5' => array( 'location' => 'grid',
'cellId' => 'headcell_field18' ),
'grid_field5' => array( 'location' => 'grid',
'cellId' => 'headcell_field19' ) ),
'itemVisiblity' => array( 'expand_menu_button' => 2,
'print_panel' => 2,
'expand_button' => 5 ) ),
'itemsByType' => array( 'page_size' => array( 'page_size' ),
'details_found' => array( 'details_found' ),
'logo' => array( 'logo' ),
'menu' => array( 'menu' ),
'simple_search' => array( 'simple_search' ),
'pagination' => array( 'pagination' ),
'search_panel' => array( 'search_panel' ),
'list_options' => array( 'list_options' ),
'show_search_panel' => array( 'show_search_panel' ),
'hide_search_panel' => array( 'hide_search_panel' ),
'search_panel_field' => array( 'search_panel_field1',
'search_panel_field3',
'search_panel_field4',
'search_panel_field5',
'search_panel_field6',
'search_panel_field8',
'search_panel_field9',
'search_panel_field10',
'search_panel_field11',
'search_panel_field',
'search_panel_field2',
'search_panel_field7',
'search_panel_field12',
'search_panel_field13',
'search_panel_field14',
'search_panel_field15' ),
'username_button' => array( 'username_button' ),
'loginform_login' => array( 'loginform_login' ),
'userinfo_link' => array( 'userinfo_link' ),
'logout_link' => array( 'logout_link' ),
'adminarea_link' => array( 'adminarea_link' ),
'changepassword_link' => array( 'changepassword_link' ),
'expand_menu_button' => array( 'expand_menu_button' ),
'collapse_button' => array( 'collapse_button' ),
'add' => array( 'add' ),
'print_panel' => array( 'print_panel' ),
'print_scope' => array( 'print_scope' ),
'print_button' => array( 'print_button' ),
'print_records' => array( 'print_records' ),
'export' => array( 'export' ),
'-' => array( '-',
'-1',
'-2',
'-3' ),
'export_selected' => array( 'export_selected' ),
'delete' => array( 'delete' ),
'delete_selected' => array( 'delete_selected' ),
'advsearch_link' => array( 'advsearch_link' ),
'grid_field_label' => array( 'grid_field_label1',
'grid_field_label6',
'grid_field_label8',
'grid_field_label3',
'grid_field_label7',
'grid_field_label2',
'grid_field_label4',
'grid_field_label5',
'grid_field_label',
'grid_field_label9' ),
'grid_field' => array( 'grid_field1',
'grid_field6',
'grid_field8',
'grid_field3',
'grid_field7',
'grid_field2',
'grid_field4',
'grid_field5',
'grid_field',
'grid_field9' ),
'print_details' => array( 'print_details' ),
'grid_field_totals' => array( 'grid_field_totals1',
'grid_field_totals2',
'grid_field_totals',
'grid_field_totals3' ),
'grid_edit' => array( 'grid_edit' ),
'grid_details_link' => array( 'grid_details_link',
'grid_details_link1' ),
'grid_checkbox' => array( 'grid_checkbox' ),
'grid_checkbox_head' => array( 'grid_checkbox_head' ),
'text' => array( 'text' ),
'notifications' => array( 'notifications' ),
'expand_button' => array( 'expand_button' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'headcell_icons' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_checkbox' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array( 'checkbox_column' ),
'items' => array( 'grid_checkbox_head' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_details' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field18' => array( 'cols' => array( 3 ),
'rows' => array( 0 ),
'tags' => array( 'Num_NP_fieldheadercolumn' ),
'items' => array( 'grid_field_label5' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field12' => array( 'cols' => array( 4 ),
'rows' => array( 0 ),
'tags' => array( 'Parcela_fieldheadercolumn' ),
'items' => array( 'grid_field_label1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field2' => array( 'cols' => array( 5 ),
'rows' => array( 0 ),
'tags' => array( 'Data_fieldheadercolumn' ),
'items' => array( 'grid_field_label2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field5' => array( 'cols' => array( 6 ),
'rows' => array( 0 ),
'tags' => array( 'Exec_cio_fieldheadercolumn' ),
'items' => array( 'grid_field_label7' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field8' => array( 'cols' => array( 7 ),
'rows' => array( 0 ),
'tags' => array( 'Sd_ant_fieldheadercolumn' ),
'items' => array( 'grid_field_label' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field14' => array( 'cols' => array( 8 ),
'rows' => array( 0 ),
'tags' => array( 'Saldo_fieldheadercolumn' ),
'items' => array( 'grid_field_label9' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field7' => array( 'cols' => array( 9 ),
'rows' => array( 0 ),
'tags' => array( 'Valor_fieldheadercolumn' ),
'items' => array( 'grid_field_label3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field10' => array( 'cols' => array( 10 ),
'rows' => array( 0 ),
'tags' => array( 'agf_fieldheadercolumn' ),
'items' => array( 'grid_field_label6' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field' => array( 'cols' => array( 11 ),
'rows' => array( 0 ),
'tags' => array( 'Debito_fieldheadercolumn' ),
'items' => array( 'grid_field_label8' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field4' => array( 'cols' => array( 12 ),
'rows' => array( 0 ),
'tags' => array( 'saldo1_fieldheadercolumn' ),
'items' => array( 'grid_field_label4' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_icons' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array( 'edit_column' ),
'items' => array( 'grid_edit' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_checkbox' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array( 'checkbox_column' ),
'items' => array( 'grid_checkbox' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_details' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'grid_details_link',
'grid_details_link1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'headcell_field19' => array( 'cols' => array( 3 ),
'rows' => array( 1 ),
'tags' => array( 'Num_NP_fieldcolumn' ),
'items' => array( 'grid_field5' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field12' => array( 'cols' => array( 4 ),
'rows' => array( 1 ),
'tags' => array( 'Parcela_fieldcolumn' ),
'items' => array( 'grid_field1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field2' => array( 'cols' => array( 5 ),
'rows' => array( 1 ),
'tags' => array( 'Data_fieldcolumn' ),
'items' => array( 'grid_field2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field5' => array( 'cols' => array( 6 ),
'rows' => array( 1 ),
'tags' => array( 'Exec_cio_fieldcolumn' ),
'items' => array( 'grid_field7' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field9' => array( 'cols' => array( 7 ),
'rows' => array( 1 ),
'tags' => array( 'Sd_ant_fieldcolumn' ),
'items' => array( 'grid_field' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field15' => array( 'cols' => array( 8 ),
'rows' => array( 1 ),
'tags' => array( 'Saldo_fieldcolumn' ),
'items' => array( 'grid_field9' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field7' => array( 'cols' => array( 9 ),
'rows' => array( 1 ),
'tags' => array( 'Valor_fieldcolumn' ),
'items' => array( 'grid_field3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field10' => array( 'cols' => array( 10 ),
'rows' => array( 1 ),
'tags' => array( 'agf_fieldcolumn' ),
'items' => array( 'grid_field6' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field' => array( 'cols' => array( 11 ),
'rows' => array( 1 ),
'tags' => array( 'Debito_fieldcolumn' ),
'items' => array( 'grid_field8' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field4' => array( 'cols' => array( 12 ),
'rows' => array( 1 ),
'tags' => array( 'saldo1_fieldcolumn' ),
'items' => array( 'grid_field4' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_icons' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_checkbox' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_details' => array( 'cols' => array( 2 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field20' => array( 'cols' => array( 3 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field1' => array( 'cols' => array( 4 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field2' => array( 'cols' => array( 5 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field5' => array( 'cols' => array( 6 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field11' => array( 'cols' => array( 7 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field16' => array( 'cols' => array( 8 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field7' => array( 'cols' => array( 9 ),
'rows' => array( 2 ),
'tags' => array( 'Valor_fieldfootercolumn' ),
'items' => array( 'grid_field_totals2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field' => array( 'cols' => array( 10 ),
'rows' => array( 2 ),
'tags' => array( 'agf_fieldfootercolumn' ),
'items' => array( 'grid_field_totals' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field3' => array( 'cols' => array( 11 ),
'rows' => array( 2 ),
'tags' => array( 'Debito_fieldfootercolumn' ),
'items' => array( 'grid_field_totals1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field16' => array( 'cols' => array( 12 ),
'rows' => array( 2 ),
'tags' => array( 'saldo1_fieldfootercolumn' ),
'items' => array( 'grid_field_totals3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field9' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field10' => array( 'cols' => array( 1 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field11' => array( 'cols' => array( 2 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field21' => array( 'cols' => array( 3 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field13' => array( 'cols' => array( 4 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field14' => array( 'cols' => array( 5 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field17' => array( 'cols' => array( 6 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field13' => array( 'cols' => array( 7 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field17' => array( 'cols' => array( 8 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field19' => array( 'cols' => array( 9 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field20' => array( 'cols' => array( 10 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field12' => array( 'cols' => array( 11 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field18' => array( 'cols' => array( 12 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 13,
'height' => 4 ) ) ),
'loginForm' => array( 'loginForm' => 0 ),
'page' => array( 'verticalBar' => true,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array( 'details_found' => array( 'tag' => 'DISPLAYING',
'type' => 2 ) ) ),
'gridType' => 0,
'recsPerRow' => 1,
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => true ),
'misc' => array( 'type' => 'list',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'dataGrid' => array( 'groupFields' => array(  ) ) );
			$pageArray = array( 'id' => 'list',
'type' => 'list',
'layoutId' => 'leftbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'above-grid' => array( 'modelId' => 'list-above-grid',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c',
'colspan' => 2 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c4',
'colspan' => 2 ) ) ),
array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c3',
'colspan' => 2 ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'add',
'delete' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'details_found',
'page_size',
'print_panel' ) ),
'c' => array( 'model' => 'c1',
'items' => array(  ),
'align' => 'center' ),
'c4' => array( 'model' => 'c1',
'items' => array(  ) ),
'c3' => array( 'model' => 'c1',
'items' => array( 'text' ),
'align' => 'center' ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'list-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'pagination' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'left' => array( 'modelId' => 'leftbar-menu',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c0' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c0' => array( 'model' => 'c0',
'items' => array( 'logo',
'expand_button' ) ),
'c1' => array( 'model' => 'c1',
'items' => array( 'menu',
'search_panel' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'supertop' => array( 'modelId' => 'leftbar-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c',
'colspan' => 2 ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'expand_menu_button',
'collapse_button' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'simple_search',
'list_options',
'notifications',
'loginform_login',
'username_button' ) ),
'c' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'horizontal-grid',
'grid' => array( array( 'section' => 'head',
'cells' => array( array( 'cell' => 'headcell_icons' ),
array( 'cell' => 'headcell_checkbox' ),
array( 'cell' => 'headcell_details' ),
array( 'cell' => 'headcell_field18' ),
array( 'cell' => 'headcell_field12' ),
array( 'cell' => 'headcell_field2' ),
array( 'cell' => 'headcell_field5' ),
array( 'cell' => 'headcell_field8' ),
array( 'cell' => 'headcell_field14' ),
array( 'cell' => 'headcell_field7' ),
array( 'cell' => 'headcell_field10' ),
array( 'cell' => 'headcell_field' ),
array( 'cell' => 'headcell_field4' ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_icons' ),
array( 'cell' => 'cell_checkbox' ),
array( 'cell' => 'cell_details' ),
array( 'cell' => 'headcell_field19' ),
array( 'cell' => 'cell_field12' ),
array( 'cell' => 'cell_field2' ),
array( 'cell' => 'cell_field5' ),
array( 'cell' => 'headcell_field9' ),
array( 'cell' => 'headcell_field15' ),
array( 'cell' => 'cell_field7' ),
array( 'cell' => 'cell_field10' ),
array( 'cell' => 'cell_field' ),
array( 'cell' => 'cell_field4' ) ) ),
array( 'section' => 'foot',
'cells' => array( array( 'cell' => 'footcell_icons' ),
array( 'cell' => 'footcell_checkbox' ),
array( 'cell' => 'footcell_details' ),
array( 'cell' => 'headcell_field20' ),
array( 'cell' => 'footcell_field1' ),
array( 'cell' => 'footcell_field2' ),
array( 'cell' => 'footcell_field5' ),
array( 'cell' => 'headcell_field11' ),
array( 'cell' => 'headcell_field16' ),
array( 'cell' => 'footcell_field7' ),
array( 'cell' => 'footcell_field' ),
array( 'cell' => 'footcell_field3' ),
array( 'cell' => 'footcell_field16' ) ) ),
array( 'section' => 'foot',
'cells' => array( array( 'cell' => 'footcell_field9' ),
array( 'cell' => 'footcell_field10' ),
array( 'cell' => 'footcell_field11' ),
array( 'cell' => 'headcell_field21' ),
array( 'cell' => 'footcell_field13' ),
array( 'cell' => 'footcell_field14' ),
array( 'cell' => 'footcell_field17' ),
array( 'cell' => 'headcell_field13' ),
array( 'cell' => 'headcell_field17' ),
array( 'cell' => 'footcell_field19' ),
array( 'cell' => 'footcell_field20' ),
array( 'cell' => 'footcell_field12' ),
array( 'cell' => 'footcell_field18' ) ) ) ),
'cells' => array( 'footcell_field1' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field2' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label2' ),
'align' => 'center',
'background' => '#fbfbfb',
'field' => 'Data',
'columnName' => 'field' ),
'cell_field2' => array( 'model' => 'cell_field',
'items' => array( 'grid_field2' ),
'align' => 'center',
'field' => 'Data',
'columnName' => 'field' ),
'footcell_field2' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'footcell_field3' => array( 'model' => 'footcell_field',
'items' => array( 'grid_field_totals1' ),
'field' => 'Debito',
'columnName' => 'field' ),
'headcell_field5' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label7' ),
'align' => 'center',
'background' => '#fbfbfb',
'field' => 'Execício',
'columnName' => 'field' ),
'cell_field5' => array( 'model' => 'cell_field',
'items' => array( 'grid_field7' ),
'align' => 'center',
'field' => 'Execício',
'columnName' => 'field' ),
'footcell_field5' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_checkbox' => array( 'model' => 'headcell_checkbox',
'items' => array( 'grid_checkbox_head' ),
'align' => 'center',
'background' => '#fbfbfb' ),
'cell_checkbox' => array( 'model' => 'cell_checkbox',
'items' => array( 'grid_checkbox' ) ),
'footcell_checkbox' => array( 'model' => 'footcell_checkbox',
'items' => array(  ) ),
'headcell_icons' => array( 'model' => 'headcell_icons',
'items' => array(  ),
'align' => 'center',
'background' => '#fbfbfb' ),
'cell_icons' => array( 'model' => 'cell_icons',
'items' => array( 'grid_edit' ) ),
'footcell_icons' => array( 'model' => 'footcell_icons',
'items' => array(  ) ),
'headcell_details' => array( 'model' => 'headcell_details',
'items' => array(  ),
'align' => 'center',
'background' => '#fbfbfb' ),
'cell_details' => array( 'model' => 'cell_details',
'items' => array( 'grid_details_link',
'grid_details_link1' ) ),
'footcell_details' => array( 'model' => 'footcell_details',
'items' => array(  ) ),
'headcell_field7' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label3' ),
'align' => 'center',
'background' => '#fbfbfb',
'field' => 'Valor',
'columnName' => 'field' ),
'cell_field7' => array( 'model' => 'cell_field',
'items' => array( 'grid_field3' ),
'align' => 'center',
'field' => 'Valor',
'columnName' => 'field' ),
'footcell_field7' => array( 'model' => 'footcell_field',
'items' => array( 'grid_field_totals2' ),
'align' => 'left',
'field' => 'Valor',
'columnName' => 'field' ),
'footcell_field9' => array( 'model' => 'footcell_icons',
'items' => array(  ) ),
'footcell_field10' => array( 'model' => 'footcell_checkbox',
'items' => array(  ) ),
'footcell_field11' => array( 'model' => 'footcell_details',
'items' => array(  ) ),
'footcell_field13' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'footcell_field14' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'footcell_field17' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'footcell_field19' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'footcell_field20' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'footcell_field' => array( 'model' => 'footcell_field',
'items' => array( 'grid_field_totals' ),
'align' => 'left',
'field' => 'agf',
'columnName' => 'field' ),
'headcell_field10' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label6' ),
'align' => 'center',
'background' => '#fbfbfb',
'field' => 'agf',
'columnName' => 'field' ),
'cell_field10' => array( 'model' => 'cell_field',
'items' => array( 'grid_field6' ),
'align' => 'center',
'field' => 'agf',
'columnName' => 'field' ),
'headcell_field' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label8' ),
'align' => 'center',
'background' => '#fbfbfb',
'field' => 'Debito',
'columnName' => 'field' ),
'cell_field' => array( 'model' => 'cell_field',
'items' => array( 'grid_field8' ),
'align' => 'center',
'field' => 'Debito',
'columnName' => 'field' ),
'footcell_field12' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field4' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label4' ),
'align' => 'center',
'background' => '#fbfbfb',
'field' => 'saldo1',
'columnName' => 'field' ),
'cell_field4' => array( 'model' => 'cell_field',
'items' => array( 'grid_field4' ),
'align' => 'center',
'field' => 'saldo1',
'columnName' => 'field' ),
'footcell_field16' => array( 'model' => 'footcell_field',
'items' => array( 'grid_field_totals3' ),
'field' => 'saldo1',
'columnName' => 'field' ),
'footcell_field18' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'cell_field12' => array( 'model' => 'cell_field',
'items' => array( 'grid_field1' ),
'align' => 'center',
'field' => 'Parcela',
'columnName' => 'field' ),
'headcell_field12' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label1' ),
'align' => 'center',
'background' => '#fbfbfb',
'field' => 'Parcela',
'columnName' => 'field' ),
'headcell_field8' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label' ),
'align' => 'center',
'background' => '#fbfbfb',
'field' => 'Sd_ant',
'columnName' => 'field' ),
'headcell_field9' => array( 'model' => 'cell_field',
'items' => array( 'grid_field' ),
'align' => 'center',
'field' => 'Sd_ant',
'columnName' => 'field' ),
'headcell_field11' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field13' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field14' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label9' ),
'background' => '#fbfbfb',
'field' => 'Saldo',
'columnName' => 'field' ),
'headcell_field15' => array( 'model' => 'cell_field',
'items' => array( 'grid_field9' ),
'field' => 'Saldo',
'columnName' => 'field' ),
'headcell_field16' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field17' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field18' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label5' ),
'background' => '#fbfbfb',
'align' => 'center',
'field' => 'Num_NP',
'columnName' => 'field' ),
'headcell_field19' => array( 'model' => 'cell_field',
'items' => array( 'grid_field5' ),
'field' => 'Num_NP',
'columnName' => 'field' ),
'headcell_field20' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field21' => array( 'model' => 'footcell_field',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'list-sidebar-top',
'grid' => array(  ),
'cells' => array(  ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'page_size' => array( 'type' => 'page_size' ),
'details_found' => array( 'type' => 'details_found' ),
'logo' => array( 'type' => 'logo' ),
'menu' => array( 'type' => 'menu',
'menuId' => 'main' ),
'simple_search' => array( 'type' => 'simple_search' ),
'pagination' => array( 'type' => 'pagination' ),
'search_panel' => array( 'type' => 'search_panel',
'items' => array( 'search_panel_field11',
'search_panel_field15',
'search_panel_field14',
'search_panel_field13',
'search_panel_field12',
'search_panel_field7',
'search_panel_field2',
'search_panel_field',
'search_panel_field10',
'search_panel_field9',
'search_panel_field8',
'search_panel_field6',
'search_panel_field5',
'search_panel_field4',
'search_panel_field3',
'search_panel_field1' ) ),
'list_options' => array( 'type' => 'list_options',
'items' => array( 'export_selected',
'delete_selected',
'-3',
'advsearch_link',
'show_search_panel',
'hide_search_panel',
'-1',
'export' ) ),
'show_search_panel' => array( 'type' => 'show_search_panel' ),
'hide_search_panel' => array( 'type' => 'hide_search_panel' ),
'search_panel_field1' => array( 'field' => 'Data',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field3' => array( 'field' => 'Escola',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field4' => array( 'field' => 'Execício',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field5' => array( 'field' => 'Num_NP',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field6' => array( 'field' => 'Parcela',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field8' => array( 'field' => 'Valor',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'userinfo_link',
'logout_link',
'adminarea_link',
'changepassword_link' ) ),
'loginform_login' => array( 'type' => 'loginform_login',
'popup' => false ),
'userinfo_link' => array( 'type' => 'userinfo_link' ),
'logout_link' => array( 'type' => 'logout_link' ),
'adminarea_link' => array( 'type' => 'adminarea_link' ),
'changepassword_link' => array( 'type' => 'changepassword_link' ),
'expand_menu_button' => array( 'type' => 'expand_menu_button' ),
'collapse_button' => array( 'type' => 'collapse_button' ),
'add' => array( 'type' => 'add',
'popup' => false,
'label' => array( 'type' => 0,
'text' => 'Cadastrar Nova  NP' ),
'tooltip' => array( 'type' => 0,
'text' => 'Cadastrar nova NP' ),
'buttonStyle' => 'info' ),
'print_panel' => array( 'type' => 'print_panel',
'items' => array( 'print_scope',
'print_details',
'print_records',
'print_button' ),
'mobileDisplay' => 'mobile' ),
'print_scope' => array( 'type' => 'print_scope' ),
'print_button' => array( 'type' => 'print_button' ),
'print_records' => array( 'type' => 'print_records' ),
'export' => array( 'type' => 'export' ),
'-' => array( 'type' => '-' ),
'export_selected' => array( 'type' => 'export_selected' ),
'-1' => array( 'type' => '-' ),
'-2' => array( 'type' => '-' ),
'delete' => array( 'type' => 'delete',
'buttonStyle' => 'link-button' ),
'delete_selected' => array( 'type' => 'delete_selected' ),
'advsearch_link' => array( 'type' => 'advsearch_link' ),
'-3' => array( 'type' => '-' ),
'grid_field_label1' => array( 'type' => 'grid_field_label',
'field' => 'Parcela',
'clickSort' => true,
'bold' => false ),
'grid_field1' => array( 'field' => 'Parcela',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'bold' => true,
'color' => '#b8902c',
'font-size' => '14px',
'nowrap' => true ),
'print_details' => array( 'type' => 'print_details',
'tables' => array( 'pedidos_view1' => true ) ),
'grid_field6' => array( 'field' => 'agf',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field_label6' => array( 'type' => 'grid_field_label',
'field' => 'agf',
'clickSort' => true,
'bold' => false ),
'grid_field8' => array( 'field' => 'Debito',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'bold' => true,
'nowrap' => true ),
'grid_field_label8' => array( 'type' => 'grid_field_label',
'field' => 'Debito',
'clickSort' => true,
'bold' => false ),
'grid_field_totals1' => array( 'type' => 'grid_field_totals',
'field' => 'Debito',
'totals' => 'TOTAL',
'bold' => true,
'nowrap' => true ),
'grid_field_totals2' => array( 'type' => 'grid_field_totals',
'field' => 'Valor',
'totals' => 'TOTAL',
'bold' => true,
'nowrap' => true ),
'grid_field3' => array( 'field' => 'Valor',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'bold' => true,
'nowrap' => true ),
'grid_edit' => array( 'type' => 'grid_edit',
'popup' => false ),
'grid_field_label3' => array( 'type' => 'grid_field_label',
'field' => 'Valor',
'clickSort' => true,
'bold' => false ),
'grid_details_link' => array( 'type' => 'grid_details_link',
'table' => 'pedidos',
'badge' => true,
'hideIfNone' => false,
'showCount' => true ),
'grid_checkbox' => array( 'type' => 'grid_checkbox' ),
'grid_checkbox_head' => array( 'type' => 'grid_checkbox_head' ),
'grid_field7' => array( 'field' => 'Execício',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'nowrap' => true ),
'grid_field_label7' => array( 'type' => 'grid_field_label',
'field' => 'Execício',
'clickSort' => true,
'bold' => false ),
'grid_field2' => array( 'field' => 'Data',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'nowrap' => true ),
'grid_field_label2' => array( 'type' => 'grid_field_label',
'field' => 'Data',
'clickSort' => true,
'bold' => false ),
'search_panel_field9' => array( 'field' => 'Nome',
'type' => 'search_panel_field',
'required' => false ),
'grid_field4' => array( 'field' => 'saldo1',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'bold' => false,
'nowrap' => true ),
'grid_field_label4' => array( 'type' => 'grid_field_label',
'field' => 'saldo1',
'clickSort' => true,
'bold' => false ),
'search_panel_field10' => array( 'field' => 'saldo1',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'grid_field5' => array( 'field' => 'Num_NP',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field_label5' => array( 'type' => 'grid_field_label',
'field' => 'Num_NP',
'clickSort' => true,
'bold' => false ),
'search_panel_field11' => array( 'field' => 'agf',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'grid_field_totals' => array( 'type' => 'grid_field_totals',
'field' => 'agf',
'totals' => 'TOTAL',
'nowrap' => true ),
'grid_field_totals3' => array( 'type' => 'grid_field_totals',
'field' => 'saldo1',
'totals' => 'TOTAL',
'nowrap' => true ),
'grid_details_link1' => array( 'type' => 'grid_details_link',
'table' => 'Pedidos_escola',
'badge' => false,
'showCount' => true,
'hideIfNone' => false ),
'text' => array( 'type' => 'text',
'label' => array( 'type' => 0,
'text' => 'Gestão de Parcelas' ),
'editedByRte' => false,
'bold' => true,
'font-size' => '24px' ),
'notifications' => array( 'type' => 'notifications' ),
'search_panel_field' => array( 'field' => 'Endereço',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field2' => array( 'field' => 'Bairro',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field7' => array( 'field' => 'Municipio',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field12' => array( 'field' => 'Direc',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field13' => array( 'field' => 'Drae',
'type' => 'search_panel_field',
'required' => false ),
'grid_field' => array( 'field' => 'Sd_ant',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field_label' => array( 'type' => 'grid_field_label',
'field' => 'Sd_ant',
'clickSort' => true,
'bold' => false ),
'search_panel_field14' => array( 'field' => 'Sd_ant',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'grid_field9' => array( 'field' => 'Saldo',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field_label9' => array( 'type' => 'grid_field_label',
'field' => 'Saldo' ),
'search_panel_field15' => array( 'field' => 'Saldo',
'type' => 'search_panel_field',
'alwaysOnPanel' => false,
'required' => false ),
'expand_button' => array( 'type' => 'expand_button' ) ),
'dbProps' => array(  ),
'spreadsheetGrid' => false,
'version' => 11,
'pageWidth' => 'compact',
'reorderRows' => false,
'reorderRowsField' => '',
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right' );
		?>