<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'Nome',
'Endereço',
'Bairro',
'Municipio' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'Nome' => array( 'grid_field',
'grid_field_label' ),
'Endereço' => array( 'grid_field1',
'grid_field_label1' ),
'Bairro' => array( 'grid_field2',
'grid_field_label2' ),
'Municipio' => array( 'grid_field3',
'grid_field_label3' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array( 'image' ),
'below-grid' => array(  ),
'top' => array(  ),
'grid' => array( 'grid_field2',
'grid_field_label',
'grid_field',
'grid_field_label2',
'grid_field_label3',
'grid_field_label1',
'grid_field1',
'grid_field3' ) ),
'formXtTags' => array( 'below-grid' => array(  ),
'top' => array(  ) ),
'itemForms' => array( 'image' => 'above-grid',
'grid_field2' => 'grid',
'grid_field_label' => 'grid',
'grid_field' => 'grid',
'grid_field_label2' => 'grid',
'grid_field_label3' => 'grid',
'grid_field_label1' => 'grid',
'grid_field1' => 'grid',
'grid_field3' => 'grid' ),
'itemLocations' => array( 'grid_field2' => array( 'location' => 'grid',
'cellId' => 'headcell_field' ),
'grid_field_label' => array( 'location' => 'grid',
'cellId' => 'headcell_field9' ),
'grid_field' => array( 'location' => 'grid',
'cellId' => 'headcell_field10' ),
'grid_field_label2' => array( 'location' => 'grid',
'cellId' => 'headcell_field12' ),
'grid_field_label3' => array( 'location' => 'grid',
'cellId' => 'headcell_field14' ),
'grid_field_label1' => array( 'location' => 'grid',
'cellId' => 'headcell_field15' ),
'grid_field1' => array( 'location' => 'grid',
'cellId' => 'headcell_field17' ),
'grid_field3' => array( 'location' => 'grid',
'cellId' => 'headcell_field1' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'grid_field' => array( 'grid_field',
'grid_field1',
'grid_field2',
'grid_field3' ),
'grid_field_label' => array( 'grid_field_label',
'grid_field_label1',
'grid_field_label2',
'grid_field_label3' ),
'image' => array( 'image' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'headcell_field9' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array( 'Nome_fieldheadercolumn' ),
'items' => array( 'grid_field_label' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field15' => array( 'cols' => array( 1,
2 ),
'rows' => array( 0 ),
'tags' => array( 'Endere_o_fieldheadercolumn' ),
'items' => array( 'grid_field_label1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field10' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array( 'Nome_fieldcolumn' ),
'items' => array( 'grid_field' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field17' => array( 'cols' => array( 1,
2 ),
'rows' => array( 1 ),
'tags' => array( 'Endere_o_fieldcolumn' ),
'items' => array( 'grid_field1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field12' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array( 'Bairro_fieldheadercolumn' ),
'items' => array( 'grid_field_label2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field14' => array( 'cols' => array( 1,
2 ),
'rows' => array( 2 ),
'tags' => array( 'Municipio_fieldheadercolumn' ),
'items' => array( 'grid_field_label3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array( 'Bairro_fieldcolumn' ),
'items' => array( 'grid_field2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field1' => array( 'cols' => array( 1,
2 ),
'rows' => array( 3 ),
'tags' => array( 'Municipio_fieldcolumn' ),
'items' => array( 'grid_field3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field2' => array( 'cols' => array( 0,
1,
2 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field11' => array( 'cols' => array( 0,
1 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field' => array( 'cols' => array( 2 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 3,
'height' => 6 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'gridType' => 0,
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false ),
'misc' => array( 'type' => 'masterprint',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'masterprint',
'type' => 'masterprint',
'layoutId' => 'masterprint',
'disabled' => 0,
'default' => 0,
'forms' => array( 'above-grid' => array( 'modelId' => 'empty-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'image' ),
'align' => 'center' ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'empty-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'masterlist-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'align' => 'center' ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'horizontal-grid',
'grid' => array( array( 'section' => 'head',
'cells' => array( array( 'cell' => 'headcell_field9',
'colspan' => 1 ),
array( 'cell' => 'headcell_field15',
'colspan' => 2 ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'headcell_field10',
'colspan' => 1 ),
array( 'cell' => 'headcell_field17',
'colspan' => 2 ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'headcell_field12',
'colspan' => 1 ),
array( 'cell' => 'headcell_field14',
'colspan' => 2 ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'headcell_field',
'colspan' => 1 ),
array( 'cell' => 'headcell_field1',
'colspan' => 2 ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'headcell_field2',
'colspan' => 3 ) ) ),
array( 'section' => 'foot',
'cells' => array( array( 'cell' => 'headcell_field11',
'colspan' => 2 ),
array( 'cell' => 'footcell_field',
'colspan' => 1 ) ) ) ),
'cells' => array( 'headcell_field' => array( 'model' => 'cell_field',
'items' => array( 'grid_field2' ),
'field' => 'Bairro',
'columnName' => 'field' ),
'footcell_field' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field9' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label' ),
'field' => 'Nome',
'columnName' => 'field' ),
'headcell_field10' => array( 'model' => 'cell_field',
'items' => array( 'grid_field' ),
'nowrap' => true,
'width' => '250px',
'field' => 'Nome',
'columnName' => 'field' ),
'headcell_field11' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field12' => array( 'model' => 'cell_field',
'items' => array( 'grid_field_label2' ),
'field' => 'Bairro',
'columnName' => 'field' ),
'headcell_field14' => array( 'model' => 'cell_field',
'items' => array( 'grid_field_label3' ),
'field' => 'Municipio',
'columnName' => 'field' ),
'headcell_field15' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label1' ),
'field' => 'Endereço',
'columnName' => 'field' ),
'headcell_field17' => array( 'model' => 'cell_field',
'items' => array( 'grid_field1' ),
'nowrap' => true,
'field' => 'Endereço',
'columnName' => 'field' ),
'headcell_field1' => array( 'model' => 'cell_field',
'items' => array( 'grid_field3' ),
'field' => 'Municipio',
'columnName' => 'field' ),
'headcell_field2' => array( 'model' => 'cell_field',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'grid_field' => array( 'field' => 'Nome',
'type' => 'grid_field',
'nowrap' => true,
'width' => '250px' ),
'grid_field_label' => array( 'type' => 'grid_field_label',
'field' => 'Nome' ),
'grid_field1' => array( 'field' => 'Endereço',
'type' => 'grid_field' ),
'grid_field_label1' => array( 'type' => 'grid_field_label',
'field' => 'Endereço' ),
'grid_field2' => array( 'field' => 'Bairro',
'type' => 'grid_field',
'width' => '250px' ),
'grid_field_label2' => array( 'type' => 'grid_field_label',
'field' => 'Bairro' ),
'grid_field3' => array( 'field' => 'Municipio',
'type' => 'grid_field' ),
'grid_field_label3' => array( 'type' => 'grid_field_label',
'field' => 'Municipio' ),
'image' => array( 'type' => 'image',
'image' => array( 'image' => 'logo_gov_resized.png',
'source' => 2 ) ) ),
'dbProps' => array(  ),
'version' => 11,
'pageWidth' => 'standard',
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right' );
		?>