<?php
			$optionsArray = array( 'list' => array( 'inlineAdd' => false,
'detailsAdd' => true,
'inlineEdit' => true,
'spreadsheetMode' => false,
'reorderRows' => false,
'addToBottom' => false,
'delete' => true,
'updateSelected' => false,
'addInPopup' => false,
'editInPopup' => null,
'viewInPopup' => null,
'clickSort' => true,
'sortDropdown' => false,
'showHideFields' => true,
'reorderFields' => false ),
'allDetails' => array( 'linkType' => 1 ),
'details' => array( 'pedidos' => array( 'displayPreview' => 1,
'previewPageId' => 'list',
'showCount' => true,
'hideEmptyChild' => false,
'hideEmptyPreview' => false,
'showProceedLink' => false,
'printDetails' => true ) ),
'master' => array( 'escolas' => array( 'preview' => false ) ),
'listSearch' => array( 'alwaysOnPanelFields' => array( 'Drae',
'Direc' ),
'searchPanel' => true,
'fixedSearchPanel' => false,
'simpleSearchOptions' => false,
'searchSaving' => false ),
'totals' => array( 'Cod_NP' => array( 'totalsType' => '' ),
'Parcela' => array( 'totalsType' => '' ),
'Data' => array( 'totalsType' => '' ),
'Valor' => array( 'totalsType' => 'TOTAL' ),
'Saldo' => array( 'totalsType' => '' ),
'Escola' => array( 'totalsType' => '' ),
'Num_NP' => array( 'totalsType' => '' ),
'Execício' => array( 'totalsType' => '' ),
'Debito' => array( 'totalsType' => 'TOTAL' ),
'saldo1' => array( 'totalsType' => 'TOTAL' ),
'Nome' => array( 'totalsType' => '' ),
'agf' => array( 'totalsType' => 'TOTAL' ),
'Tec_resp' => array( 'totalsType' => '' ),
'Drae' => array( 'totalsType' => '' ),
'Bairro' => array( 'totalsType' => '' ),
'Direc' => array( 'totalsType' => '' ),
'Municipio' => array( 'totalsType' => '' ),
'fullname' => array( 'totalsType' => '' ),
'Sd_ant' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'Nome',
'Parcela',
'Sd_ant',
'Saldo',
'Valor',
'agf',
'Debito',
'saldo1',
'Drae',
'Direc',
'fullname' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array( 'Valor',
'Parcela',
'Sd_ant',
'fullname',
'Municipio',
'Direc',
'Bairro',
'Drae',
'saldo1',
'Debito',
'Execício',
'Saldo',
'Nome' ),
'filterFields' => array( 'fullname' ),
'inlineAddFields' => array(  ),
'inlineEditFields' => array( 'Parcela',
'Valor',
'Sd_ant',
'Saldo' ),
'fieldItems' => array( 'Parcela' => array( 'grid_field1',
'grid_field_label1' ),
'Drae' => array( 'grid_field2',
'grid_field_label2' ),
'Valor' => array( 'grid_field3',
'grid_field_label3',
'grid_field_totals2' ),
'saldo1' => array( 'grid_field4',
'grid_field_label4',
'grid_field_totals' ),
'Direc' => array( 'grid_field7',
'grid_field_label7' ),
'Debito' => array( 'grid_field8',
'grid_field_label8',
'grid_field_totals1' ),
'agf' => array( 'grid_field',
'grid_field_label',
'grid_field_totals3' ),
'Nome' => array( 'grid_field5',
'grid_field_label5' ),
'fullname' => array( 'grid_field6',
'grid_field_label6' ),
'Sd_ant' => array( 'grid_field9',
'grid_field_label9' ),
'Saldo' => array( 'grid_field10',
'grid_field_label10' ) ),
'hideEmptyFields' => array(  ) ),
'pageLinks' => array( 'edit' => false,
'add' => true,
'view' => false,
'print' => true ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array( 'add',
'inline_add',
'inline_save_all',
'inline_cancel_all',
'delete',
'details_found',
'page_size',
'print_panel',
'columns_control',
'text' ),
'below-grid' => array( 'pagination' ),
'left' => array( 'logo',
'expand_button',
'menu',
'search_panel',
'filter_panel' ),
'supertop' => array( 'expand_menu_button',
'collapse_button',
'simple_search',
'list_options',
'notifications',
'loginform_login',
'username_button' ),
'grid' => array( 'grid_checkbox_head',
'grid_checkbox',
'grid_inline_edit',
'grid_inline_save',
'grid_inline_cancel',
'grid_details_link',
'grid_field_label9',
'grid_field9',
'grid_field_label4',
'grid_field4',
'grid_field_totals',
'grid_field_label',
'grid_field',
'grid_field_totals3',
'grid_field_label5',
'grid_field5',
'grid_field_totals1',
'grid_field_label8',
'grid_field8',
'grid_field_label2',
'grid_field2',
'grid_field1',
'grid_field_label1',
'details_preview',
'grid_field_label7',
'grid_field7',
'grid_field_label6',
'grid_field6',
'grid_field3',
'grid_field_label3',
'grid_field_totals2',
'grid_field10',
'grid_field_label10' ),
'top' => array(  ) ),
'formXtTags' => array( 'below-grid' => array( 'pagination' ),
'top' => array(  ) ),
'itemForms' => array( 'add' => 'above-grid',
'inline_add' => 'above-grid',
'inline_save_all' => 'above-grid',
'inline_cancel_all' => 'above-grid',
'delete' => 'above-grid',
'details_found' => 'above-grid',
'page_size' => 'above-grid',
'print_panel' => 'above-grid',
'columns_control' => 'above-grid',
'text' => 'above-grid',
'pagination' => 'below-grid',
'logo' => 'left',
'expand_button' => 'left',
'menu' => 'left',
'search_panel' => 'left',
'filter_panel' => 'left',
'expand_menu_button' => 'supertop',
'collapse_button' => 'supertop',
'simple_search' => 'supertop',
'list_options' => 'supertop',
'notifications' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'grid_checkbox_head' => 'grid',
'grid_checkbox' => 'grid',
'grid_inline_edit' => 'grid',
'grid_inline_save' => 'grid',
'grid_inline_cancel' => 'grid',
'grid_details_link' => 'grid',
'grid_field_label9' => 'grid',
'grid_field9' => 'grid',
'grid_field_label4' => 'grid',
'grid_field4' => 'grid',
'grid_field_totals' => 'grid',
'grid_field_label' => 'grid',
'grid_field' => 'grid',
'grid_field_totals3' => 'grid',
'grid_field_label5' => 'grid',
'grid_field5' => 'grid',
'grid_field_totals1' => 'grid',
'grid_field_label8' => 'grid',
'grid_field8' => 'grid',
'grid_field_label2' => 'grid',
'grid_field2' => 'grid',
'grid_field1' => 'grid',
'grid_field_label1' => 'grid',
'details_preview' => 'grid',
'grid_field_label7' => 'grid',
'grid_field7' => 'grid',
'grid_field_label6' => 'grid',
'grid_field6' => 'grid',
'grid_field3' => 'grid',
'grid_field_label3' => 'grid',
'grid_field_totals2' => 'grid',
'grid_field10' => 'grid',
'grid_field_label10' => 'grid' ),
'itemLocations' => array( 'grid_checkbox_head' => array( 'location' => 'grid',
'cellId' => 'headcell_checkbox' ),
'grid_checkbox' => array( 'location' => 'grid',
'cellId' => 'cell_checkbox' ),
'grid_inline_edit' => array( 'location' => 'grid',
'cellId' => 'cell_icons' ),
'grid_inline_save' => array( 'location' => 'grid',
'cellId' => 'cell_icons' ),
'grid_inline_cancel' => array( 'location' => 'grid',
'cellId' => 'cell_icons' ),
'grid_details_link' => array( 'location' => 'grid',
'cellId' => 'cell_details' ),
'grid_field_label9' => array( 'location' => 'grid',
'cellId' => 'headcell_field7' ),
'grid_field9' => array( 'location' => 'grid',
'cellId' => 'cell_field7' ),
'grid_field_label4' => array( 'location' => 'grid',
'cellId' => 'headcell_field4' ),
'grid_field4' => array( 'location' => 'grid',
'cellId' => 'cell_field4' ),
'grid_field_totals' => array( 'location' => 'grid',
'cellId' => 'footcell_field4' ),
'grid_field_label' => array( 'location' => 'grid',
'cellId' => 'headcell_field8' ),
'grid_field' => array( 'location' => 'grid',
'cellId' => 'cell_field8' ),
'grid_field_totals3' => array( 'location' => 'grid',
'cellId' => 'footcell_field8' ),
'grid_field_label5' => array( 'location' => 'grid',
'cellId' => 'headcell_field9' ),
'grid_field5' => array( 'location' => 'grid',
'cellId' => 'cell_field9' ),
'grid_field_totals1' => array( 'location' => 'grid',
'cellId' => 'footcell_field' ),
'grid_field_label8' => array( 'location' => 'grid',
'cellId' => 'headcell_field10' ),
'grid_field8' => array( 'location' => 'grid',
'cellId' => 'cell_field10' ),
'grid_field_label2' => array( 'location' => 'grid',
'cellId' => 'headcell_field' ),
'grid_field2' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'grid_field1' => array( 'location' => 'grid',
'cellId' => 'cell_field11' ),
'grid_field_label1' => array( 'location' => 'grid',
'cellId' => 'headcell_field11' ),
'details_preview' => array( 'location' => 'grid',
'cellId' => 'cell_dpreview' ),
'grid_field_label7' => array( 'location' => 'grid',
'cellId' => 'headcell_field3' ),
'grid_field7' => array( 'location' => 'grid',
'cellId' => 'cell_field3' ),
'grid_field_label6' => array( 'location' => 'grid',
'cellId' => 'headcell_field1' ),
'grid_field6' => array( 'location' => 'grid',
'cellId' => 'cell_field1' ),
'grid_field3' => array( 'location' => 'grid',
'cellId' => 'cell_field12' ),
'grid_field_label3' => array( 'location' => 'grid',
'cellId' => 'headcell_field12' ),
'grid_field_totals2' => array( 'location' => 'grid',
'cellId' => 'footcell_field18' ),
'grid_field10' => array( 'location' => 'grid',
'cellId' => 'cell_field13' ),
'grid_field_label10' => array( 'location' => 'grid',
'cellId' => 'headcell_field13' ) ),
'itemVisiblity' => array( 'expand_menu_button' => 2,
'print_panel' => 5,
'expand_button' => 5 ) ),
'itemsByType' => array( 'page_size' => array( 'page_size' ),
'details_found' => array( 'details_found' ),
'logo' => array( 'logo' ),
'menu' => array( 'menu' ),
'simple_search' => array( 'simple_search' ),
'pagination' => array( 'pagination' ),
'grid_checkbox' => array( 'grid_checkbox' ),
'grid_checkbox_head' => array( 'grid_checkbox_head' ),
'search_panel' => array( 'search_panel' ),
'list_options' => array( 'list_options' ),
'show_search_panel' => array( 'show_search_panel' ),
'hide_search_panel' => array( 'hide_search_panel' ),
'search_panel_field' => array( 'search_panel_field2',
'search_panel_field6',
'search_panel_field7',
'search_panel_field',
'search_panel_field1',
'search_panel_field3',
'search_panel_field4',
'search_panel_field5',
'search_panel_field8',
'search_panel_field10',
'search_panel_field11',
'search_panel_field9',
'search_panel_field12' ),
'expand_menu_button' => array( 'expand_menu_button' ),
'collapse_button' => array( 'collapse_button' ),
'add' => array( 'add' ),
'print_panel' => array( 'print_panel' ),
'print_scope' => array( 'print_scope' ),
'print_button' => array( 'print_button' ),
'print_records' => array( 'print_records' ),
'-' => array( '-',
'-1',
'-2',
'-3',
'-4',
'-5',
'-6' ),
'delete' => array( 'delete' ),
'delete_selected' => array( 'delete_selected' ),
'advsearch_link' => array( 'advsearch_link' ),
'grid_details_link' => array( 'grid_details_link' ),
'grid_field' => array( 'grid_field1',
'grid_field2',
'grid_field3',
'grid_field4',
'grid_field7',
'grid_field8',
'grid_field',
'grid_field5',
'grid_field6',
'grid_field9',
'grid_field10' ),
'grid_field_label' => array( 'grid_field_label1',
'grid_field_label2',
'grid_field_label3',
'grid_field_label4',
'grid_field_label7',
'grid_field_label8',
'grid_field_label',
'grid_field_label5',
'grid_field_label6',
'grid_field_label9',
'grid_field_label10' ),
'text' => array( 'text' ),
'username_button' => array( 'username_button' ),
'changepassword_link' => array( 'changepassword_link' ),
'adminarea_link' => array( 'adminarea_link' ),
'loginform_login' => array( 'loginform_login' ),
'userinfo_link' => array( 'userinfo_link' ),
'logout_link' => array( 'logout_link' ),
'grid_field_totals' => array( 'grid_field_totals',
'grid_field_totals1',
'grid_field_totals2',
'grid_field_totals3' ),
'export' => array( 'export' ),
'export_selected' => array( 'export_selected' ),
'import' => array( 'import' ),
'filter_panel' => array( 'filter_panel' ),
'notifications' => array( 'notifications' ),
'edit_selected' => array( 'edit_selected' ),
'grid_inline_edit' => array( 'grid_inline_edit' ),
'grid_inline_save' => array( 'grid_inline_save' ),
'grid_inline_cancel' => array( 'grid_inline_cancel' ),
'inline_save_all' => array( 'inline_save_all' ),
'inline_cancel_all' => array( 'inline_cancel_all' ),
'print_details' => array( 'print_details' ),
'details_preview' => array( 'details_preview' ),
'filter_panel_field' => array( 'filter_panel_field' ),
'columns_control' => array( 'columns_control' ),
'expand_button' => array( 'expand_button' ),
'inline_add' => array( 'inline_add' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'headcell_icons' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_checkbox' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array( 'checkbox_column' ),
'items' => array( 'grid_checkbox_head' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_details' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field9' => array( 'cols' => array( 3 ),
'rows' => array( 0 ),
'tags' => array( 'Nome_fieldheadercolumn' ),
'items' => array( 'grid_field_label5' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field11' => array( 'cols' => array( 4 ),
'rows' => array( 0 ),
'tags' => array( 'Parcela_fieldheadercolumn' ),
'items' => array( 'grid_field_label1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field7' => array( 'cols' => array( 5 ),
'rows' => array( 0 ),
'tags' => array( 'Sd_ant_fieldheadercolumn' ),
'items' => array( 'grid_field_label9' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field13' => array( 'cols' => array( 6 ),
'rows' => array( 0 ),
'tags' => array( 'Saldo_fieldheadercolumn' ),
'items' => array( 'grid_field_label10' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field12' => array( 'cols' => array( 7 ),
'rows' => array( 0 ),
'tags' => array( 'Valor_fieldheadercolumn' ),
'items' => array( 'grid_field_label3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field8' => array( 'cols' => array( 8 ),
'rows' => array( 0 ),
'tags' => array( 'agf_fieldheadercolumn' ),
'items' => array( 'grid_field_label' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field10' => array( 'cols' => array( 9 ),
'rows' => array( 0 ),
'tags' => array( 'Debito_fieldheadercolumn' ),
'items' => array( 'grid_field_label8' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field4' => array( 'cols' => array( 10 ),
'rows' => array( 0 ),
'tags' => array( 'saldo1_fieldheadercolumn' ),
'items' => array( 'grid_field_label4' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field' => array( 'cols' => array( 11 ),
'rows' => array( 0 ),
'tags' => array( 'Drae_fieldheadercolumn' ),
'items' => array( 'grid_field_label2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field3' => array( 'cols' => array( 12 ),
'rows' => array( 0 ),
'tags' => array( 'Direc_fieldheadercolumn' ),
'items' => array( 'grid_field_label7' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field1' => array( 'cols' => array( 13 ),
'rows' => array( 0 ),
'tags' => array( 'fullname_fieldheadercolumn' ),
'items' => array( 'grid_field_label6' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_icons' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array( 'inlineedit_column',
'inline_save',
'inline_cancel' ),
'items' => array( 'grid_inline_edit',
'grid_inline_save',
'grid_inline_cancel' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_checkbox' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array( 'checkbox_column' ),
'items' => array( 'grid_checkbox' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_details' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'grid_details_link' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'cell_field9' => array( 'cols' => array( 3 ),
'rows' => array( 1 ),
'tags' => array( 'Nome_fieldcolumn' ),
'items' => array( 'grid_field5' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field11' => array( 'cols' => array( 4 ),
'rows' => array( 1 ),
'tags' => array( 'Parcela_fieldcolumn' ),
'items' => array( 'grid_field1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field7' => array( 'cols' => array( 5 ),
'rows' => array( 1 ),
'tags' => array( 'Sd_ant_fieldcolumn' ),
'items' => array( 'grid_field9' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field13' => array( 'cols' => array( 6 ),
'rows' => array( 1 ),
'tags' => array( 'Saldo_fieldcolumn' ),
'items' => array( 'grid_field10' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field12' => array( 'cols' => array( 7 ),
'rows' => array( 1 ),
'tags' => array( 'Valor_fieldcolumn' ),
'items' => array( 'grid_field3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field8' => array( 'cols' => array( 8 ),
'rows' => array( 1 ),
'tags' => array( 'agf_fieldcolumn' ),
'items' => array( 'grid_field' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field10' => array( 'cols' => array( 9 ),
'rows' => array( 1 ),
'tags' => array( 'Debito_fieldcolumn' ),
'items' => array( 'grid_field8' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field4' => array( 'cols' => array( 10 ),
'rows' => array( 1 ),
'tags' => array( 'saldo1_fieldcolumn' ),
'items' => array( 'grid_field4' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field' => array( 'cols' => array( 11 ),
'rows' => array( 1 ),
'tags' => array( 'Drae_fieldcolumn' ),
'items' => array( 'grid_field2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field3' => array( 'cols' => array( 12 ),
'rows' => array( 1 ),
'tags' => array( 'Direc_fieldcolumn' ),
'items' => array( 'grid_field7' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field1' => array( 'cols' => array( 13 ),
'rows' => array( 1 ),
'tags' => array( 'fullname_fieldcolumn' ),
'items' => array( 'grid_field6' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_dpreview' => array( 'cols' => array( 0,
1,
2,
3,
4,
5,
6,
7,
8,
9,
10,
11,
12,
13 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'details_preview' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'footcell_icons' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_checkbox' => array( 'cols' => array( 1 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_details' => array( 'cols' => array( 2 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field1' => array( 'cols' => array( 3,
4 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field7' => array( 'cols' => array( 5,
6 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field18' => array( 'cols' => array( 7 ),
'rows' => array( 3 ),
'tags' => array( 'Valor_fieldfootercolumn' ),
'items' => array( 'grid_field_totals2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field8' => array( 'cols' => array( 8 ),
'rows' => array( 3 ),
'tags' => array( 'agf_fieldfootercolumn' ),
'items' => array( 'grid_field_totals3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field' => array( 'cols' => array( 9 ),
'rows' => array( 3 ),
'tags' => array( 'Debito_fieldfootercolumn' ),
'items' => array( 'grid_field_totals1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field4' => array( 'cols' => array( 10 ),
'rows' => array( 3 ),
'tags' => array( 'saldo1_fieldfootercolumn' ),
'items' => array( 'grid_field_totals' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field2' => array( 'cols' => array( 11 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field14' => array( 'cols' => array( 12 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field5' => array( 'cols' => array( 13 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field9' => array( 'cols' => array( 0 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field10' => array( 'cols' => array( 1 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field11' => array( 'cols' => array( 2 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field13' => array( 'cols' => array( 3,
4 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field19' => array( 'cols' => array( 5,
6,
7 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field20' => array( 'cols' => array( 8,
9 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field16' => array( 'cols' => array( 10 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field3' => array( 'cols' => array( 11 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field17' => array( 'cols' => array( 12 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field6' => array( 'cols' => array( 13 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 14,
'height' => 5 ) ) ),
'loginForm' => array( 'loginForm' => 0 ),
'page' => array( 'verticalBar' => true,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array( 'details_found' => array( 'tag' => 'DISPLAYING',
'type' => 2 ) ) ),
'gridType' => 0,
'recsPerRow' => 1,
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => true ),
'misc' => array( 'type' => 'list',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'dataGrid' => array( 'groupFields' => array(  ) ) );
			$pageArray = array( 'id' => 'list',
'type' => 'list',
'layoutId' => 'leftbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'above-grid' => array( 'modelId' => 'list-above-grid',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c',
'colspan' => 2 ) ) ),
array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'add',
'inline_add',
'inline_save_all',
'inline_cancel_all',
'delete' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'details_found',
'page_size',
'print_panel',
'columns_control' ) ),
'c' => array( 'model' => 'c1',
'items' => array( 'text' ),
'align' => 'center' ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'list-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'pagination' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'left' => array( 'modelId' => 'leftbar-menu',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c0' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c0' => array( 'model' => 'c0',
'items' => array( 'logo',
'expand_button' ) ),
'c1' => array( 'model' => 'c1',
'items' => array( 'menu',
'search_panel',
'filter_panel' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'supertop' => array( 'modelId' => 'leftbar-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'expand_menu_button',
'collapse_button' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'simple_search',
'list_options',
'notifications',
'loginform_login',
'username_button' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'horizontal-grid',
'grid' => array( array( 'section' => 'head',
'cells' => array( array( 'cell' => 'headcell_icons' ),
array( 'cell' => 'headcell_checkbox' ),
array( 'cell' => 'headcell_details' ),
array( 'cell' => 'headcell_field9' ),
array( 'cell' => 'headcell_field11' ),
array( 'cell' => 'headcell_field7' ),
array( 'cell' => 'headcell_field13' ),
array( 'cell' => 'headcell_field12' ),
array( 'cell' => 'headcell_field8' ),
array( 'cell' => 'headcell_field10' ),
array( 'cell' => 'headcell_field4' ),
array( 'cell' => 'headcell_field' ),
array( 'cell' => 'headcell_field3' ),
array( 'cell' => 'headcell_field1' ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_icons' ),
array( 'cell' => 'cell_checkbox' ),
array( 'cell' => 'cell_details' ),
array( 'cell' => 'cell_field9' ),
array( 'cell' => 'cell_field11' ),
array( 'cell' => 'cell_field7' ),
array( 'cell' => 'cell_field13' ),
array( 'cell' => 'cell_field12' ),
array( 'cell' => 'cell_field8' ),
array( 'cell' => 'cell_field10' ),
array( 'cell' => 'cell_field4' ),
array( 'cell' => 'cell_field' ),
array( 'cell' => 'cell_field3' ),
array( 'cell' => 'cell_field1' ) ) ),
array( 'cells' => array( array( 'cell' => 'cell_dpreview',
'colspan' => 14 ) ),
'section' => 'body' ),
array( 'section' => 'foot',
'cells' => array( array( 'cell' => 'footcell_icons' ),
array( 'cell' => 'footcell_checkbox' ),
array( 'cell' => 'footcell_details' ),
array( 'cell' => 'footcell_field1',
'colspan' => 2 ),
array( 'cell' => 'footcell_field7',
'colspan' => 2 ),
array( 'cell' => 'footcell_field18' ),
array( 'cell' => 'footcell_field8' ),
array( 'cell' => 'footcell_field' ),
array( 'cell' => 'footcell_field4' ),
array( 'cell' => 'footcell_field2' ),
array( 'cell' => 'footcell_field14' ),
array( 'cell' => 'footcell_field5' ) ) ),
array( 'section' => 'foot',
'cells' => array( array( 'cell' => 'footcell_field9' ),
array( 'cell' => 'footcell_field10' ),
array( 'cell' => 'footcell_field11' ),
array( 'cell' => 'footcell_field13',
'colspan' => 2 ),
array( 'cell' => 'footcell_field19',
'colspan' => 3 ),
array( 'cell' => 'footcell_field20',
'colspan' => 2 ),
array( 'cell' => 'footcell_field16' ),
array( 'cell' => 'footcell_field3' ),
array( 'cell' => 'footcell_field17' ),
array( 'cell' => 'footcell_field6' ) ) ) ),
'cells' => array( 'footcell_field1' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'footcell_field2' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'footcell_field3' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_checkbox' => array( 'model' => 'headcell_checkbox',
'items' => array( 'grid_checkbox_head' ) ),
'cell_checkbox' => array( 'model' => 'cell_checkbox',
'items' => array( 'grid_checkbox' ) ),
'footcell_checkbox' => array( 'model' => 'footcell_checkbox',
'items' => array(  ) ),
'headcell_icons' => array( 'model' => 'headcell_icons',
'items' => array(  ) ),
'cell_icons' => array( 'model' => 'cell_icons',
'items' => array( 'grid_inline_edit',
'grid_inline_save',
'grid_inline_cancel' ) ),
'footcell_icons' => array( 'model' => 'footcell_icons',
'items' => array(  ) ),
'headcell_details' => array( 'model' => 'headcell_details',
'items' => array(  ) ),
'cell_details' => array( 'model' => 'cell_details',
'items' => array( 'grid_details_link' ) ),
'footcell_details' => array( 'model' => 'footcell_details',
'items' => array(  ) ),
'headcell_field7' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label9' ),
'align' => 'center',
'field' => 'Sd_ant',
'columnName' => 'field' ),
'cell_field7' => array( 'model' => 'cell_field',
'items' => array( 'grid_field9' ),
'align' => 'center',
'field' => 'Sd_ant',
'columnName' => 'field' ),
'headcell_field4' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label4' ),
'align' => 'center',
'field' => 'saldo1',
'columnName' => 'field' ),
'cell_field4' => array( 'model' => 'cell_field',
'items' => array( 'grid_field4' ),
'align' => 'center',
'field' => 'saldo1',
'columnName' => 'field' ),
'footcell_field4' => array( 'model' => 'footcell_field',
'items' => array( 'grid_field_totals' ),
'align' => 'right',
'field' => 'saldo1',
'columnName' => 'field' ),
'headcell_field8' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label' ),
'align' => 'center',
'field' => 'agf',
'columnName' => 'field' ),
'cell_field8' => array( 'model' => 'cell_field',
'items' => array( 'grid_field' ),
'align' => 'center',
'field' => 'agf',
'columnName' => 'field' ),
'footcell_field7' => array( 'model' => 'footcell_field',
'items' => array(  ),
'align' => 'left' ),
'footcell_field8' => array( 'model' => 'footcell_field',
'items' => array( 'grid_field_totals3' ),
'align' => 'left',
'field' => 'agf',
'columnName' => 'field' ),
'footcell_field9' => array( 'model' => 'footcell_icons',
'items' => array(  ) ),
'footcell_field10' => array( 'model' => 'footcell_checkbox',
'items' => array(  ) ),
'footcell_field11' => array( 'model' => 'footcell_details',
'items' => array(  ) ),
'footcell_field13' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'footcell_field14' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'footcell_field16' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'footcell_field17' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'footcell_field19' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'footcell_field20' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field9' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label5' ),
'align' => 'center',
'field' => 'Nome',
'columnName' => 'field' ),
'cell_field9' => array( 'model' => 'cell_field',
'items' => array( 'grid_field5' ),
'align' => 'left',
'field' => 'Nome',
'columnName' => 'field' ),
'footcell_field' => array( 'model' => 'footcell_field',
'items' => array( 'grid_field_totals1' ),
'align' => 'left',
'field' => 'Debito',
'columnName' => 'field' ),
'headcell_field10' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label8' ),
'align' => 'center',
'field' => 'Debito',
'columnName' => 'field' ),
'cell_field10' => array( 'model' => 'cell_field',
'items' => array( 'grid_field8' ),
'align' => 'center',
'field' => 'Debito',
'columnName' => 'field' ),
'headcell_field' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label2' ),
'align' => 'center',
'field' => 'Drae',
'columnName' => 'field' ),
'cell_field' => array( 'model' => 'cell_field',
'items' => array( 'grid_field2' ),
'nowrap' => true,
'field' => 'Drae',
'columnName' => 'field' ),
'cell_field11' => array( 'model' => 'cell_field',
'items' => array( 'grid_field1' ),
'align' => 'center',
'field' => 'Parcela',
'columnName' => 'field' ),
'headcell_field11' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label1' ),
'align' => 'center',
'field' => 'Parcela',
'columnName' => 'field' ),
'cell_dpreview' => array( 'model' => 'cell_dpreview',
'items' => array( 'details_preview' ) ),
'headcell_field3' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label7' ),
'align' => 'center',
'field' => 'Direc',
'columnName' => 'field' ),
'cell_field3' => array( 'model' => 'cell_field',
'items' => array( 'grid_field7' ),
'nowrap' => true,
'field' => 'Direc',
'columnName' => 'field' ),
'headcell_field1' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label6' ),
'align' => 'center',
'field' => 'fullname',
'columnName' => 'field' ),
'cell_field1' => array( 'model' => 'cell_field',
'items' => array( 'grid_field6' ),
'nowrap' => true,
'field' => 'fullname',
'columnName' => 'field' ),
'footcell_field5' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'footcell_field6' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'cell_field12' => array( 'model' => 'cell_field',
'items' => array( 'grid_field3' ),
'align' => 'center',
'field' => 'Valor',
'columnName' => 'field' ),
'headcell_field12' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label3' ),
'align' => 'center',
'field' => 'Valor',
'columnName' => 'field' ),
'footcell_field18' => array( 'model' => 'footcell_field',
'items' => array( 'grid_field_totals2' ),
'align' => 'left',
'field' => 'Valor',
'columnName' => 'field' ),
'cell_field13' => array( 'model' => 'cell_field',
'items' => array( 'grid_field10' ),
'align' => 'center',
'nowrap' => true,
'field' => 'Saldo',
'columnName' => 'field' ),
'headcell_field13' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label10' ),
'align' => 'center',
'nowrap' => true,
'field' => 'Saldo',
'columnName' => 'field' ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'list-sidebar-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c2' => array( 'model' => 'c2',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'page_size' => array( 'type' => 'page_size' ),
'details_found' => array( 'type' => 'details_found' ),
'logo' => array( 'type' => 'logo' ),
'menu' => array( 'type' => 'menu',
'menuId' => 'main' ),
'simple_search' => array( 'type' => 'simple_search' ),
'pagination' => array( 'type' => 'pagination' ),
'grid_checkbox' => array( 'type' => 'grid_checkbox' ),
'grid_checkbox_head' => array( 'type' => 'grid_checkbox_head' ),
'search_panel' => array( 'type' => 'search_panel',
'items' => array( 'search_panel_field6',
'search_panel_field12',
'search_panel_field9',
'search_panel_field11',
'search_panel_field10',
'search_panel_field8',
'search_panel_field5',
'search_panel_field2',
'search_panel_field4',
'search_panel_field3',
'search_panel_field1',
'search_panel_field',
'search_panel_field7' ),
'_flexiblePanel' => true ),
'list_options' => array( 'type' => 'list_options',
'items' => array( 'edit_selected',
'export_selected',
'delete_selected',
'-4',
'advsearch_link',
'show_search_panel',
'hide_search_panel',
'-5',
'export',
'-6',
'import' ) ),
'show_search_panel' => array( 'type' => 'show_search_panel' ),
'hide_search_panel' => array( 'type' => 'hide_search_panel' ),
'search_panel_field2' => array( 'field' => 'Drae',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => true ),
'search_panel_field6' => array( 'field' => 'Valor',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'expand_menu_button' => array( 'type' => 'expand_menu_button' ),
'collapse_button' => array( 'type' => 'collapse_button' ),
'add' => array( 'type' => 'add',
'popupWidth' => '750px',
'popupHeight' => '500px',
'label' => array( 'type' => 0,
'text' => 'Cadastrar Nova NP' ),
'popup' => false,
'page' => 'add' ),
'print_panel' => array( 'type' => 'print_panel',
'items' => array( 'print_scope',
'print_details',
'print_records',
'print_button' ) ),
'print_scope' => array( 'type' => 'print_scope' ),
'print_button' => array( 'type' => 'print_button' ),
'print_records' => array( 'type' => 'print_records' ),
'-' => array( 'type' => '-' ),
'-1' => array( 'type' => '-' ),
'-2' => array( 'type' => '-' ),
'delete' => array( 'type' => 'delete' ),
'delete_selected' => array( 'type' => 'delete_selected' ),
'advsearch_link' => array( 'type' => 'advsearch_link' ),
'-3' => array( 'type' => '-' ),
'grid_details_link' => array( 'type' => 'grid_details_link',
'table' => 'pedidos',
'badge' => false,
'hideIfNone' => false,
'showCount' => true ),
'grid_field1' => array( 'field' => 'Parcela',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => true,
'bold' => true,
'color' => '#e33f29',
'font-size' => '14px' ),
'grid_field_label1' => array( 'type' => 'grid_field_label',
'field' => 'Parcela',
'clickSort' => true,
'color' => '#e33f29',
'bold' => true,
'font-size' => '16px' ),
'grid_field2' => array( 'field' => 'Drae',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field_label2' => array( 'type' => 'grid_field_label',
'field' => 'Drae',
'clickSort' => true,
'bold' => true,
'font-size' => '16px' ),
'-4' => array( 'type' => '-' ),
'text' => array( 'type' => 'text',
'label' => array( 'type' => 0,
'text' => 'Gestão de Pedidos' ),
'editedByRte' => false,
'font-size' => '20px',
'nowrap' => true,
'bold' => true ),
'grid_field3' => array( 'field' => 'Valor',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => true,
'bold' => true,
'nowrap' => true ),
'grid_field_label3' => array( 'type' => 'grid_field_label',
'field' => 'Valor',
'clickSort' => true,
'bold' => true,
'font-size' => '16px' ),
'grid_field4' => array( 'field' => 'saldo1',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'bold' => true,
'nowrap' => true ),
'grid_field_label4' => array( 'type' => 'grid_field_label',
'field' => 'saldo1',
'clickSort' => true,
'bold' => true,
'font-size' => '16px' ),
'grid_field7' => array( 'field' => 'Direc',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field_label7' => array( 'type' => 'grid_field_label',
'field' => 'Direc',
'clickSort' => true,
'bold' => true,
'font-size' => '16px' ),
'grid_field8' => array( 'field' => 'Debito',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'bold' => true,
'nowrap' => true ),
'grid_field_label8' => array( 'type' => 'grid_field_label',
'field' => 'Debito',
'clickSort' => true,
'bold' => true,
'font-size' => '16px' ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'userinfo_link',
'logout_link',
'adminarea_link',
'changepassword_link' ) ),
'changepassword_link' => array( 'type' => 'changepassword_link' ),
'adminarea_link' => array( 'type' => 'adminarea_link' ),
'loginform_login' => array( 'type' => 'loginform_login',
'popup' => false ),
'userinfo_link' => array( 'type' => 'userinfo_link' ),
'logout_link' => array( 'type' => 'logout_link' ),
'search_panel_field7' => array( 'field' => 'Nome',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'grid_field_totals' => array( 'type' => 'grid_field_totals',
'field' => 'saldo1',
'totals' => 'TOTAL',
'bold' => true ),
'grid_field_totals1' => array( 'type' => 'grid_field_totals',
'field' => 'Debito',
'totals' => 'TOTAL',
'bold' => true ),
'grid_field_totals2' => array( 'type' => 'grid_field_totals',
'field' => 'Valor',
'totals' => 'TOTAL',
'bold' => true ),
'export' => array( 'type' => 'export' ),
'-5' => array( 'type' => '-' ),
'export_selected' => array( 'type' => 'export_selected' ),
'import' => array( 'type' => 'import' ),
'-6' => array( 'type' => '-' ),
'grid_field' => array( 'field' => 'agf',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'bold' => true,
'nowrap' => true ),
'grid_field_label' => array( 'type' => 'grid_field_label',
'field' => 'agf',
'clickSort' => true,
'label' => array( 'field' => 'agf',
'table' => 'np',
'type' => 3 ),
'bold' => true,
'font-size' => '16px' ),
'grid_field_totals3' => array( 'type' => 'grid_field_totals',
'field' => 'agf',
'totals' => 'TOTAL',
'bold' => true ),
'grid_field5' => array( 'field' => 'Nome',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'nowrap' => true ),
'grid_field_label5' => array( 'type' => 'grid_field_label',
'field' => 'Nome',
'clickSort' => true,
'bold' => true,
'font-size' => '16px' ),
'filter_panel' => array( 'type' => 'filter_panel',
'items' => array( 'filter_panel_field' ) ),
'notifications' => array( 'type' => 'notifications' ),
'edit_selected' => array( 'type' => 'edit_selected' ),
'grid_inline_edit' => array( 'type' => 'grid_inline_edit' ),
'grid_inline_save' => array( 'type' => 'grid_inline_save' ),
'grid_inline_cancel' => array( 'type' => 'grid_inline_cancel' ),
'inline_save_all' => array( 'type' => 'inline_save_all' ),
'inline_cancel_all' => array( 'type' => 'inline_cancel_all' ),
'print_details' => array( 'type' => 'print_details',
'tables' => array( 'pedidos' => true ) ),
'details_preview' => array( 'type' => 'details_preview',
'table' => 'pedidos',
'items' => array(  ),
'popup' => false,
'hideEmptyPreview' => false,
'proceedLink' => false,
'pageId' => 'list' ),
'search_panel_field' => array( 'field' => 'Saldo',
'type' => 'search_panel_field',
'alwaysOnPanel' => false,
'required' => false ),
'search_panel_field1' => array( 'field' => 'Execício',
'type' => 'search_panel_field',
'alwaysOnPanel' => false,
'required' => false ),
'search_panel_field3' => array( 'field' => 'Debito',
'type' => 'search_panel_field',
'alwaysOnPanel' => false,
'required' => false ),
'search_panel_field4' => array( 'field' => 'saldo1',
'type' => 'search_panel_field',
'alwaysOnPanel' => false,
'required' => false ),
'search_panel_field5' => array( 'field' => 'Bairro',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field8' => array( 'field' => 'Direc',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => true ),
'search_panel_field10' => array( 'field' => 'Municipio',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'grid_field6' => array( 'field' => 'fullname',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field_label6' => array( 'type' => 'grid_field_label',
'field' => 'fullname',
'clickSort' => true,
'bold' => true,
'font-size' => '16px' ),
'search_panel_field11' => array( 'field' => 'fullname',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'filter_panel_field' => array( 'field' => 'fullname',
'type' => 'filter_panel_field' ),
'grid_field9' => array( 'field' => 'Sd_ant',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => true,
'width' => '120px' ),
'grid_field_label9' => array( 'type' => 'grid_field_label',
'field' => 'Sd_ant',
'clickSort' => true,
'bold' => true,
'font-size' => '16px' ),
'search_panel_field9' => array( 'field' => 'Sd_ant',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'grid_field10' => array( 'field' => 'Saldo',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => true,
'nowrap' => true,
'placeholder' => array( 'field' => 'Saldo',
'table' => 'np',
'type' => 5 ) ),
'grid_field_label10' => array( 'type' => 'grid_field_label',
'field' => 'Saldo',
'clickSort' => true,
'bold' => true,
'font-size' => '16px' ),
'search_panel_field12' => array( 'field' => 'Parcela',
'type' => 'search_panel_field' ),
'columns_control' => array( 'type' => 'columns_control',
'showHide' => true,
'reorder' => false ),
'expand_button' => array( 'type' => 'expand_button' ),
'inline_add' => array( 'type' => 'inline_add',
'detailsOnly' => true ) ),
'dbProps' => array(  ),
'spreadsheetGrid' => false,
'version' => 11,
'pageWidth' => 'full',
'reorderRows' => false,
'reorderRowsField' => '',
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right' );
		?>