<?php
			$optionsArray = array( 'pdf' => array( 'pdfView' => true,
'orientation' => 'landscape',
'scale' => 100 ),
'details' => array( 'pedidos' => array( 'displayPreview' => 1,
'previewPageId' => 'print1' ) ),
'master' => array( 'escolas' => array( 'preview' => true ) ),
'totals' => array( 'Cod_NP' => array( 'totalsType' => '' ),
'Parcela' => array( 'totalsType' => '' ),
'Data' => array( 'totalsType' => '' ),
'Valor' => array( 'totalsType' => 'TOTAL' ),
'Saldo' => array( 'totalsType' => 'TOTAL' ),
'Escola' => array( 'totalsType' => '' ),
'Num_NP' => array( 'totalsType' => '' ),
'Execício' => array( 'totalsType' => '' ),
'Debito' => array( 'totalsType' => 'TOTAL' ),
'saldo1' => array( 'totalsType' => 'TOTAL' ),
'Nome' => array( 'totalsType' => '' ),
'agf' => array( 'totalsType' => 'TOTAL' ),
'Tec_resp' => array( 'totalsType' => '' ),
'Drae' => array( 'totalsType' => '' ),
'Bairro' => array( 'totalsType' => '' ),
'Direc' => array( 'totalsType' => '' ),
'Municipio' => array( 'totalsType' => '' ),
'fullname' => array( 'totalsType' => '' ),
'Sd_ant' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'Parcela',
'agf',
'saldo1',
'Nome',
'Drae',
'Direc',
'Valor',
'Debito',
'fullname',
'Sd_ant',
'Saldo' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'Parcela' => array( 'simple_grid_field1',
'simple_grid_field' ),
'agf' => array( 'grid_field',
'grid_field_label',
'grid_field_totals1' ),
'saldo1' => array( 'grid_field1',
'grid_field_label1',
'grid_field_totals3' ),
'Nome' => array( 'grid_field2',
'grid_field_label2' ),
'Drae' => array( 'grid_field4',
'grid_field_label4' ),
'Direc' => array( 'grid_field6',
'grid_field_label6' ),
'Valor' => array( 'grid_field8',
'grid_field_label8',
'grid_field_totals' ),
'Debito' => array( 'grid_field3',
'grid_field_label3',
'grid_field_totals2' ),
'fullname' => array( 'grid_field5',
'grid_field_label5' ),
'Sd_ant' => array( 'grid_field7',
'grid_field_label7' ),
'Saldo' => array( 'grid_field9',
'grid_field_label9',
'grid_field_totals4' ) ),
'hideEmptyFields' => array(  ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array( 'print_pages',
'grid_inline_cancel',
'inline_add' ),
'below-grid' => array(  ),
'top' => array( 'print_header',
'print_subheader',
'master_info',
'print_pdf',
'image' ),
'grid' => array( 'simple_grid_field',
'simple_grid_field1',
'grid_field_label7',
'grid_field7',
'grid_field_label',
'grid_field_label1',
'grid_field1',
'grid_field_totals3',
'grid_field_label2',
'grid_field2',
'details_preview',
'grid_field',
'grid_field_label6',
'grid_field6',
'grid_field_totals1',
'grid_field_label4',
'grid_field4',
'grid_field_label3',
'grid_field3',
'grid_field_totals2',
'grid_field_label5',
'grid_field5',
'grid_field_label9',
'grid_field9',
'grid_field_totals4',
'grid_field_label8',
'grid_field8',
'grid_field_totals' ) ),
'formXtTags' => array( 'above-grid' => array( 'print_pages',
'inline_cancel',
'inlineadd_link' ),
'below-grid' => array(  ) ),
'itemForms' => array( 'print_pages' => 'above-grid',
'grid_inline_cancel' => 'above-grid',
'inline_add' => 'above-grid',
'print_header' => 'top',
'print_subheader' => 'top',
'master_info' => 'top',
'print_pdf' => 'top',
'image' => 'top',
'simple_grid_field' => 'grid',
'simple_grid_field1' => 'grid',
'grid_field_label7' => 'grid',
'grid_field7' => 'grid',
'grid_field_label' => 'grid',
'grid_field_label1' => 'grid',
'grid_field1' => 'grid',
'grid_field_totals3' => 'grid',
'grid_field_label2' => 'grid',
'grid_field2' => 'grid',
'details_preview' => 'grid',
'grid_field' => 'grid',
'grid_field_label6' => 'grid',
'grid_field6' => 'grid',
'grid_field_totals1' => 'grid',
'grid_field_label4' => 'grid',
'grid_field4' => 'grid',
'grid_field_label3' => 'grid',
'grid_field3' => 'grid',
'grid_field_totals2' => 'grid',
'grid_field_label5' => 'grid',
'grid_field5' => 'grid',
'grid_field_label9' => 'grid',
'grid_field9' => 'grid',
'grid_field_totals4' => 'grid',
'grid_field_label8' => 'grid',
'grid_field8' => 'grid',
'grid_field_totals' => 'grid' ),
'itemLocations' => array( 'simple_grid_field' => array( 'location' => 'grid',
'cellId' => 'headcell_field' ),
'simple_grid_field1' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'grid_field_label7' => array( 'location' => 'grid',
'cellId' => 'headcell_field1' ),
'grid_field7' => array( 'location' => 'grid',
'cellId' => 'cell_field1' ),
'grid_field_label' => array( 'location' => 'grid',
'cellId' => 'cell_field4' ),
'grid_field_label1' => array( 'location' => 'grid',
'cellId' => 'headcell_field5' ),
'grid_field1' => array( 'location' => 'grid',
'cellId' => 'cell_field10' ),
'grid_field_totals3' => array( 'location' => 'grid',
'cellId' => 'footcell_field5' ),
'grid_field_label2' => array( 'location' => 'grid',
'cellId' => 'cell_field14' ),
'grid_field2' => array( 'location' => 'grid',
'cellId' => 'cell_field15' ),
'details_preview' => array( 'location' => 'grid',
'cellId' => 'cell_field16' ),
'grid_field' => array( 'location' => 'grid',
'cellId' => 'cell_field7' ),
'grid_field_label6' => array( 'location' => 'grid',
'cellId' => 'headcell_field6' ),
'grid_field6' => array( 'location' => 'grid',
'cellId' => 'cell_field9' ),
'grid_field_totals1' => array( 'location' => 'grid',
'cellId' => 'cell_field18' ),
'grid_field_label4' => array( 'location' => 'grid',
'cellId' => 'headcell_field8' ),
'grid_field4' => array( 'location' => 'grid',
'cellId' => 'cell_field19' ),
'grid_field_label3' => array( 'location' => 'grid',
'cellId' => 'headcell_field7' ),
'grid_field3' => array( 'location' => 'grid',
'cellId' => 'headcell_field9' ),
'grid_field_totals2' => array( 'location' => 'grid',
'cellId' => 'headcell_field11' ),
'grid_field_label5' => array( 'location' => 'grid',
'cellId' => 'headcell_field2' ),
'grid_field5' => array( 'location' => 'grid',
'cellId' => 'cell_field2' ),
'grid_field_label9' => array( 'location' => 'grid',
'cellId' => 'cell_field23' ),
'grid_field9' => array( 'location' => 'grid',
'cellId' => 'cell_field24' ),
'grid_field_totals4' => array( 'location' => 'grid',
'cellId' => 'cell_field26' ),
'grid_field_label8' => array( 'location' => 'grid',
'cellId' => 'cell_field27' ),
'grid_field8' => array( 'location' => 'grid',
'cellId' => 'cell_field28' ),
'grid_field_totals' => array( 'location' => 'grid',
'cellId' => 'cell_field30' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'print_header' => array( 'print_header' ),
'print_subheader' => array( 'print_subheader' ),
'print_pages' => array( 'print_pages' ),
'grid_field' => array( 'simple_grid_field1',
'grid_field',
'grid_field1',
'grid_field2',
'grid_field4',
'grid_field6',
'grid_field8',
'grid_field3',
'grid_field5',
'grid_field7',
'grid_field9' ),
'grid_field_label' => array( 'simple_grid_field',
'grid_field_label',
'grid_field_label1',
'grid_field_label2',
'grid_field_label4',
'grid_field_label6',
'grid_field_label8',
'grid_field_label3',
'grid_field_label5',
'grid_field_label7',
'grid_field_label9' ),
'master_info' => array( 'master_info' ),
'print_pdf' => array( 'print_pdf' ),
'details_preview' => array( 'details_preview' ),
'image' => array( 'image' ),
'grid_field_totals' => array( 'grid_field_totals',
'grid_field_totals1',
'grid_field_totals2',
'grid_field_totals3',
'grid_field_totals4' ),
'inline_add' => array( 'inline_add' ),
'grid_inline_cancel' => array( 'grid_inline_cancel' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'cell_field5' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field14' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array( 'Nome_fieldheadercolumn' ),
'items' => array( 'grid_field_label2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array( 'Parcela_fieldheadercolumn' ),
'items' => array( 'simple_grid_field' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field1' => array( 'cols' => array( 3 ),
'rows' => array( 0 ),
'tags' => array( 'Sd_ant_fieldheadercolumn' ),
'items' => array( 'grid_field_label7' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field23' => array( 'cols' => array( 4 ),
'rows' => array( 0 ),
'tags' => array( 'Saldo_fieldheadercolumn' ),
'items' => array( 'grid_field_label9' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field27' => array( 'cols' => array( 5 ),
'rows' => array( 0 ),
'tags' => array( 'Valor_fieldheadercolumn' ),
'items' => array( 'grid_field_label8' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field4' => array( 'cols' => array( 6 ),
'rows' => array( 0 ),
'tags' => array( 'agf_fieldheadercolumn' ),
'items' => array( 'grid_field_label' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field7' => array( 'cols' => array( 7 ),
'rows' => array( 0 ),
'tags' => array( 'Debito_fieldheadercolumn' ),
'items' => array( 'grid_field_label3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field5' => array( 'cols' => array( 8 ),
'rows' => array( 0 ),
'tags' => array( 'saldo1_fieldheadercolumn' ),
'items' => array( 'grid_field_label1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field6' => array( 'cols' => array( 9 ),
'rows' => array( 0 ),
'tags' => array( 'Direc_fieldheadercolumn' ),
'items' => array( 'grid_field_label6' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field8' => array( 'cols' => array( 10 ),
'rows' => array( 0 ),
'tags' => array( 'Drae_fieldheadercolumn' ),
'items' => array( 'grid_field_label4' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field2' => array( 'cols' => array( 11 ),
'rows' => array( 0 ),
'tags' => array( 'fullname_fieldheadercolumn' ),
'items' => array( 'grid_field_label5' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field3' => array( 'cols' => array( 12 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field6' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field15' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array( 'Nome_fieldcolumn' ),
'items' => array( 'grid_field2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array( 'Parcela_fieldcolumn' ),
'items' => array( 'simple_grid_field1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field1' => array( 'cols' => array( 3 ),
'rows' => array( 1 ),
'tags' => array( 'Sd_ant_fieldcolumn' ),
'items' => array( 'grid_field7' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field24' => array( 'cols' => array( 4 ),
'rows' => array( 1 ),
'tags' => array( 'Saldo_fieldcolumn' ),
'items' => array( 'grid_field9' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field28' => array( 'cols' => array( 5 ),
'rows' => array( 1 ),
'tags' => array( 'Valor_fieldcolumn' ),
'items' => array( 'grid_field8' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field7' => array( 'cols' => array( 6 ),
'rows' => array( 1 ),
'tags' => array( 'agf_fieldcolumn' ),
'items' => array( 'grid_field' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field9' => array( 'cols' => array( 7 ),
'rows' => array( 1 ),
'tags' => array( 'Debito_fieldcolumn' ),
'items' => array( 'grid_field3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field10' => array( 'cols' => array( 8 ),
'rows' => array( 1 ),
'tags' => array( 'saldo1_fieldcolumn' ),
'items' => array( 'grid_field1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field9' => array( 'cols' => array( 9 ),
'rows' => array( 1 ),
'tags' => array( 'Direc_fieldcolumn' ),
'items' => array( 'grid_field6' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field19' => array( 'cols' => array( 10 ),
'rows' => array( 1 ),
'tags' => array( 'Drae_fieldcolumn' ),
'items' => array( 'grid_field4' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field2' => array( 'cols' => array( 11 ),
'rows' => array( 1 ),
'tags' => array( 'fullname_fieldcolumn' ),
'items' => array( 'grid_field5' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field21' => array( 'cols' => array( 12 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field16' => array( 'cols' => array( 0,
1,
2,
3 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'details_preview' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'cell_field25' => array( 'cols' => array( 4 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field29' => array( 'cols' => array( 5 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field13' => array( 'cols' => array( 6 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field10' => array( 'cols' => array( 7 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field11' => array( 'cols' => array( 8 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field12' => array( 'cols' => array( 9 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field20' => array( 'cols' => array( 10 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field3' => array( 'cols' => array( 11 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field22' => array( 'cols' => array( 12 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field8' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field17' => array( 'cols' => array( 1 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field' => array( 'cols' => array( 2 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field1' => array( 'cols' => array( 3 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field26' => array( 'cols' => array( 4 ),
'rows' => array( 3 ),
'tags' => array( 'Saldo_fieldfootercolumn' ),
'items' => array( 'grid_field_totals4' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field30' => array( 'cols' => array( 5 ),
'rows' => array( 3 ),
'tags' => array( 'Valor_fieldfootercolumn' ),
'items' => array( 'grid_field_totals' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field18' => array( 'cols' => array( 6 ),
'rows' => array( 3 ),
'tags' => array( 'agf_fieldfootercolumn' ),
'items' => array( 'grid_field_totals1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field11' => array( 'cols' => array( 7 ),
'rows' => array( 3 ),
'tags' => array( 'Debito_fieldfootercolumn' ),
'items' => array( 'grid_field_totals2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field5' => array( 'cols' => array( 8 ),
'rows' => array( 3 ),
'tags' => array( 'saldo1_fieldfootercolumn' ),
'items' => array( 'grid_field_totals3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field6' => array( 'cols' => array( 9 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field8' => array( 'cols' => array( 10 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field2' => array( 'cols' => array( 11 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field3' => array( 'cols' => array( 12 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 13,
'height' => 4 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array( 'print_pages' => array( 'tag' => 'PRINT_PAGES',
'type' => 2 ) ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'gridType' => 0,
'recsPerRow' => 1,
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false ),
'misc' => array( 'type' => 'print',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'dataGrid' => array( 'groupFields' => array( 'fullname' ) ) );
			$pageArray = array( 'id' => 'print',
'type' => 'print',
'layoutId' => 'basic',
'disabled' => 0,
'default' => 0,
'forms' => array( 'above-grid' => array( 'modelId' => 'print-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'print_pages',
'grid_inline_cancel',
'inline_add' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'print-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'print-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c' ) ) ),
array( 'cells' => array( array( 'cell' => 'c2' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c4' ) ),
'section' => '' ) ),
'cells' => array( 'c2' => array( 'model' => 'c2',
'items' => array( 'print_header',
'print_subheader' ) ),
'c4' => array( 'model' => 'c4',
'items' => array( 'master_info' ) ),
'c1' => array( 'model' => 'c1',
'items' => array( 'print_pdf' ) ),
'c' => array( 'model' => 'c2',
'items' => array( 'image' ),
'align' => 'center',
'orientation' => 'horizontal' ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'horizontal-grid',
'grid' => array( array( 'section' => 'head',
'cells' => array( array( 'cell' => 'cell_field5' ),
array( 'cell' => 'cell_field14' ),
array( 'cell' => 'headcell_field' ),
array( 'cell' => 'headcell_field1' ),
array( 'cell' => 'cell_field23' ),
array( 'cell' => 'cell_field27' ),
array( 'cell' => 'cell_field4' ),
array( 'cell' => 'headcell_field7' ),
array( 'cell' => 'headcell_field5' ),
array( 'cell' => 'headcell_field6' ),
array( 'cell' => 'headcell_field8' ),
array( 'cell' => 'headcell_field2' ),
array( 'cell' => 'headcell_field3' ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_field6' ),
array( 'cell' => 'cell_field15' ),
array( 'cell' => 'cell_field' ),
array( 'cell' => 'cell_field1' ),
array( 'cell' => 'cell_field24' ),
array( 'cell' => 'cell_field28' ),
array( 'cell' => 'cell_field7' ),
array( 'cell' => 'headcell_field9' ),
array( 'cell' => 'cell_field10' ),
array( 'cell' => 'cell_field9' ),
array( 'cell' => 'cell_field19' ),
array( 'cell' => 'cell_field2' ),
array( 'cell' => 'cell_field21' ) ) ),
array( 'cells' => array( array( 'cell' => 'cell_field16',
'colspan' => 4 ),
array( 'cell' => 'cell_field25' ),
array( 'cell' => 'cell_field29' ),
array( 'cell' => 'cell_field13' ),
array( 'cell' => 'headcell_field10' ),
array( 'cell' => 'cell_field11' ),
array( 'cell' => 'cell_field12' ),
array( 'cell' => 'cell_field20' ),
array( 'cell' => 'cell_field3' ),
array( 'cell' => 'cell_field22' ) ),
'section' => 'body' ),
array( 'section' => 'foot',
'cells' => array( array( 'cell' => 'cell_field8' ),
array( 'cell' => 'cell_field17' ),
array( 'cell' => 'footcell_field' ),
array( 'cell' => 'footcell_field1' ),
array( 'cell' => 'cell_field26' ),
array( 'cell' => 'cell_field30' ),
array( 'cell' => 'cell_field18' ),
array( 'cell' => 'headcell_field11' ),
array( 'cell' => 'footcell_field5' ),
array( 'cell' => 'footcell_field6' ),
array( 'cell' => 'footcell_field8' ),
array( 'cell' => 'footcell_field2' ),
array( 'cell' => 'footcell_field3' ) ) ) ),
'cells' => array( 'headcell_field' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field' ),
'align' => 'center',
'field' => 'Parcela',
'columnName' => 'field' ),
'cell_field' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field1' ),
'align' => 'center',
'field' => 'Parcela',
'columnName' => 'field' ),
'footcell_field' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field1' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label7' ),
'align' => 'center',
'field' => 'Sd_ant',
'columnName' => 'field' ),
'cell_field1' => array( 'model' => 'cell_field',
'items' => array( 'grid_field7' ),
'align' => 'center',
'field' => 'Sd_ant',
'columnName' => 'field' ),
'footcell_field1' => array( 'model' => 'footcell_field',
'items' => array(  ),
'align' => 'center' ),
'cell_field4' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label' ),
'align' => 'center',
'field' => 'agf',
'columnName' => 'field' ),
'cell_field5' => array( 'model' => 'headcell_field',
'items' => array(  ) ),
'cell_field6' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'cell_field8' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field5' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label1' ),
'align' => 'center',
'field' => 'saldo1',
'columnName' => 'field' ),
'cell_field10' => array( 'model' => 'cell_field',
'items' => array( 'grid_field1' ),
'align' => 'center',
'field' => 'saldo1',
'columnName' => 'field' ),
'cell_field11' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'footcell_field5' => array( 'model' => 'footcell_field',
'items' => array( 'grid_field_totals3' ),
'align' => 'center',
'field' => 'saldo1',
'columnName' => 'field' ),
'cell_field14' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label2' ),
'field' => 'Nome',
'columnName' => 'field' ),
'cell_field15' => array( 'model' => 'cell_field',
'items' => array( 'grid_field2' ),
'nowrap' => true,
'width' => '350px',
'field' => 'Nome',
'columnName' => 'field' ),
'cell_field16' => array( 'model' => 'cell_dpreview',
'items' => array( 'details_preview' ) ),
'cell_field17' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'cell_field7' => array( 'model' => 'cell_field',
'items' => array( 'grid_field' ),
'align' => 'center',
'field' => 'agf',
'columnName' => 'field' ),
'headcell_field6' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label6' ),
'align' => 'center',
'field' => 'Direc',
'columnName' => 'field' ),
'cell_field9' => array( 'model' => 'cell_field',
'items' => array( 'grid_field6' ),
'align' => 'center',
'field' => 'Direc',
'columnName' => 'field' ),
'cell_field12' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'footcell_field6' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'cell_field13' => array( 'model' => 'cell_dpreview',
'items' => array(  ) ),
'cell_field18' => array( 'model' => 'footcell_field',
'items' => array( 'grid_field_totals1' ),
'align' => 'center',
'field' => 'agf',
'columnName' => 'field' ),
'headcell_field8' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label4' ),
'align' => 'center',
'field' => 'Drae',
'columnName' => 'field' ),
'cell_field19' => array( 'model' => 'cell_field',
'items' => array( 'grid_field4' ),
'align' => 'center',
'field' => 'Drae',
'columnName' => 'field' ),
'cell_field20' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'footcell_field8' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field7' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label3' ),
'align' => 'center',
'field' => 'Debito',
'columnName' => 'field' ),
'headcell_field9' => array( 'model' => 'cell_field',
'items' => array( 'grid_field3' ),
'align' => 'center',
'field' => 'Debito',
'columnName' => 'field' ),
'headcell_field10' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'headcell_field11' => array( 'model' => 'footcell_field',
'items' => array( 'grid_field_totals2' ),
'align' => 'center',
'field' => 'Debito',
'columnName' => 'field' ),
'headcell_field2' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label5' ),
'field' => 'fullname',
'columnName' => 'field' ),
'cell_field2' => array( 'model' => 'cell_field',
'items' => array( 'grid_field5' ),
'field' => 'fullname',
'columnName' => 'field' ),
'cell_field3' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'footcell_field2' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field3' => array( 'model' => 'headcell_field',
'items' => array(  ) ),
'cell_field21' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'cell_field22' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'footcell_field3' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'cell_field23' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label9' ),
'field' => 'Saldo',
'columnName' => 'field' ),
'cell_field24' => array( 'model' => 'cell_field',
'items' => array( 'grid_field9' ),
'field' => 'Saldo',
'columnName' => 'field' ),
'cell_field25' => array( 'model' => 'cell_dpreview',
'items' => array(  ) ),
'cell_field26' => array( 'model' => 'footcell_field',
'items' => array( 'grid_field_totals4' ),
'field' => 'Saldo',
'columnName' => 'field' ),
'cell_field27' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label8' ),
'field' => 'Valor',
'columnName' => 'field' ),
'cell_field28' => array( 'model' => 'cell_field',
'items' => array( 'grid_field8' ),
'field' => 'Valor',
'columnName' => 'field' ),
'cell_field29' => array( 'model' => 'cell_dpreview',
'items' => array(  ) ),
'cell_field30' => array( 'model' => 'footcell_field',
'items' => array( 'grid_field_totals' ),
'field' => 'Valor',
'columnName' => 'field' ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'print_header' => array( 'type' => 'print_header',
'title' => array( 'page' => 'print',
'table' => 'np',
'type' => 7 ) ),
'print_subheader' => array( 'type' => 'print_subheader' ),
'print_pages' => array( 'type' => 'print_pages' ),
'simple_grid_field1' => array( 'field' => 'Parcela',
'type' => 'grid_field' ),
'simple_grid_field' => array( 'type' => 'grid_field_label',
'field' => 'Parcela' ),
'grid_field' => array( 'field' => 'agf',
'type' => 'grid_field' ),
'grid_field_label' => array( 'type' => 'grid_field_label',
'field' => 'agf' ),
'grid_field1' => array( 'field' => 'saldo1',
'type' => 'grid_field' ),
'grid_field_label1' => array( 'type' => 'grid_field_label',
'field' => 'saldo1' ),
'grid_field2' => array( 'field' => 'Nome',
'type' => 'grid_field',
'nowrap' => true,
'width' => '350px' ),
'grid_field_label2' => array( 'type' => 'grid_field_label',
'field' => 'Nome' ),
'master_info' => array( 'type' => 'master_info',
'tables' => array( 'escolas' => 'true' ) ),
'print_pdf' => array( 'type' => 'print_pdf',
'targetPages' => array(  ),
'splitModes' => array(  ),
'scopes' => array(  ),
'pageSize' => 'A4',
'label' => array( 'type' => 0,
'text' => 'Baixar PDF' ),
'orientation' => 'landscape' ),
'details_preview' => array( 'type' => 'details_preview',
'table' => 'pedidos',
'items' => array(  ),
'popup' => false,
'pageId' => 'print1' ),
'grid_field4' => array( 'field' => 'Drae',
'type' => 'grid_field' ),
'grid_field_label4' => array( 'type' => 'grid_field_label',
'field' => 'Drae' ),
'grid_field6' => array( 'field' => 'Direc',
'type' => 'grid_field' ),
'grid_field_label6' => array( 'type' => 'grid_field_label',
'field' => 'Direc' ),
'grid_field8' => array( 'field' => 'Valor',
'type' => 'grid_field' ),
'grid_field_label8' => array( 'type' => 'grid_field_label',
'field' => 'Valor' ),
'grid_field3' => array( 'field' => 'Debito',
'type' => 'grid_field' ),
'grid_field_label3' => array( 'type' => 'grid_field_label',
'field' => 'Debito' ),
'image' => array( 'type' => 'image',
'image' => array( 'image' => 'logo_gov_resized.png',
'source' => 2 ) ),
'grid_field5' => array( 'field' => 'fullname',
'type' => 'grid_field',
'group_by' => true ),
'grid_field_label5' => array( 'type' => 'grid_field_label',
'field' => 'fullname' ),
'grid_field7' => array( 'field' => 'Sd_ant',
'type' => 'grid_field' ),
'grid_field_label7' => array( 'type' => 'grid_field_label',
'field' => 'Sd_ant' ),
'grid_field9' => array( 'field' => 'Saldo',
'type' => 'grid_field' ),
'grid_field_label9' => array( 'type' => 'grid_field_label',
'field' => 'Saldo' ),
'grid_field_totals' => array( 'type' => 'grid_field_totals',
'field' => 'Valor',
'totals' => 'TOTAL',
'bold' => true ),
'grid_field_totals1' => array( 'type' => 'grid_field_totals',
'field' => 'agf',
'totals' => 'TOTAL',
'bold' => true ),
'grid_field_totals2' => array( 'type' => 'grid_field_totals',
'field' => 'Debito',
'totals' => 'TOTAL',
'bold' => true ),
'grid_field_totals3' => array( 'type' => 'grid_field_totals',
'field' => 'saldo1',
'totals' => 'TOTAL',
'bold' => true ),
'grid_field_totals4' => array( 'type' => 'grid_field_totals',
'field' => 'Saldo',
'totals' => 'TOTAL',
'bold' => true ),
'inline_add' => array( 'type' => 'inline_add',
'detailsOnly' => true ),
'grid_inline_cancel' => array( 'type' => 'grid_inline_cancel' ) ),
'dbProps' => array(  ),
'version' => 11,
'pageWidth' => 'full',
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right' );
		?>