<?php
			$optionsArray = array( 'details' => array( 'itens' => array( 'displayPreview' => 2,
'previewPageId' => '' ) ),
'master' => array( 'np' => array( 'preview' => false ) ),
'captcha' => array( 'captcha' => false ),
'fields' => array( 'gridFields' => array( 'cnpj_fornecedor',
'status',
'Data_cad',
'Exercicio' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'cnpj_fornecedor' => array( 'integrated_edit_field2',
'edit_field_label',
'edit_field_tooltip' ),
'status' => array( 'integrated_edit_field1',
'edit_field_label2',
'edit_field_tooltip2' ),
'Data_cad' => array( 'integrated_edit_field',
'edit_field_label1',
'edit_field_tooltip1' ),
'Exercicio' => array( 'integrated_edit_field3' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array( 'add_message' ),
'below-grid' => array( 'add_save',
'add_reset',
'add_back_list',
'add_cancel' ),
'supertop' => array( 'expand_menu_button',
'collapse_button',
'notifications',
'loginform_login',
'username_button' ),
'left' => array( 'logo',
'expand_button',
'menu' ),
'top' => array( 'add_header' ),
'grid' => array( 'edit_field_label1',
'integrated_edit_field',
'edit_field_tooltip1',
'edit_field_label',
'integrated_edit_field2',
'edit_field_tooltip',
'integrated_edit_field3',
'edit_field_label2',
'integrated_edit_field1',
'edit_field_tooltip2' ) ),
'formXtTags' => array( 'above-grid' => array( 'message_block' ) ),
'itemForms' => array( 'add_message' => 'above-grid',
'add_save' => 'below-grid',
'add_reset' => 'below-grid',
'add_back_list' => 'below-grid',
'add_cancel' => 'below-grid',
'expand_menu_button' => 'supertop',
'collapse_button' => 'supertop',
'notifications' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'logo' => 'left',
'expand_button' => 'left',
'menu' => 'left',
'add_header' => 'top',
'edit_field_label1' => 'grid',
'integrated_edit_field' => 'grid',
'edit_field_tooltip1' => 'grid',
'edit_field_label' => 'grid',
'integrated_edit_field2' => 'grid',
'edit_field_tooltip' => 'grid',
'integrated_edit_field3' => 'grid',
'edit_field_label2' => 'grid',
'integrated_edit_field1' => 'grid',
'edit_field_tooltip2' => 'grid' ),
'itemLocations' => array( 'edit_field_label1' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'edit_field_tooltip1' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'edit_field_label' => array( 'location' => 'grid',
'cellId' => 'c6' ),
'integrated_edit_field2' => array( 'location' => 'grid',
'cellId' => 'c6' ),
'edit_field_tooltip' => array( 'location' => 'grid',
'cellId' => 'c6' ),
'integrated_edit_field3' => array( 'location' => 'grid',
'cellId' => 'c4' ),
'edit_field_label2' => array( 'location' => 'grid',
'cellId' => 'c8' ),
'integrated_edit_field1' => array( 'location' => 'grid',
'cellId' => 'c8' ),
'edit_field_tooltip2' => array( 'location' => 'grid',
'cellId' => 'c8' ) ),
'itemVisiblity' => array( 'expand_menu_button' => 2,
'expand_button' => 5 ) ),
'itemsByType' => array( 'add_header' => array( 'add_header' ),
'add_message' => array( 'add_message' ),
'add_save' => array( 'add_save' ),
'add_reset' => array( 'add_reset' ),
'add_back_list' => array( 'add_back_list' ),
'add_cancel' => array( 'add_cancel' ),
'edit_field' => array( 'integrated_edit_field2',
'integrated_edit_field1',
'integrated_edit_field' ),
'logo' => array( 'logo' ),
'menu' => array( 'menu' ),
'expand_menu_button' => array( 'expand_menu_button' ),
'collapse_button' => array( 'collapse_button' ),
'edit_field_label' => array( 'edit_field_label',
'edit_field_label1',
'edit_field_label2' ),
'edit_field_tooltip' => array( 'edit_field_tooltip',
'edit_field_tooltip1',
'edit_field_tooltip2' ),
'username_button' => array( 'username_button' ),
'changepassword_link' => array( 'changepassword_link' ),
'adminarea_link' => array( 'adminarea_link' ),
'loginform_login' => array( 'loginform_login' ),
'userinfo_link' => array( 'userinfo_link' ),
'logout_link' => array( 'logout_link' ),
'integrated_edit_field' => array( 'integrated_edit_field3' ),
'notifications' => array( 'notifications' ),
'expand_button' => array( 'expand_button' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c8' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'edit_field_label2',
'integrated_edit_field1',
'edit_field_tooltip2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c6' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'edit_field_label',
'integrated_edit_field2',
'edit_field_tooltip' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c3' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'edit_field_label1',
'integrated_edit_field',
'edit_field_tooltip1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c5' => array( 'cols' => array( 0 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c4' => array( 'cols' => array( 0 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field3' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 6 ) ) ),
'loginForm' => array( 'loginForm' => 0 ),
'page' => array( 'verticalBar' => true,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => true ),
'misc' => array( 'type' => 'add',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'add',
'type' => 'add',
'layoutId' => 'leftbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'above-grid' => array( 'modelId' => 'add-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'add_message' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'add-below-grid',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c' ) ) ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'add_save',
'add_reset',
'add_back_list',
'add_cancel' ) ),
'c' => array( 'model' => 'c1',
'items' => array(  ),
'align' => 'right' ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'supertop' => array( 'modelId' => 'leftbar-top-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'expand_menu_button',
'collapse_button' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'notifications',
'loginform_login',
'username_button' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'left' => array( 'modelId' => 'leftbar-menu',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c0' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c0' => array( 'model' => 'c0',
'items' => array( 'logo',
'expand_button' ) ),
'c1' => array( 'model' => 'c1',
'items' => array( 'menu' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'add-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'add_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c8' ) ) ),
array( 'cells' => array( array( 'cell' => 'c6' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c' ) ) ),
array( 'cells' => array( array( 'cell' => 'c3',
'colspan' => 1 ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c5' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c4' ) ) ) ),
'cells' => array( 'c3' => array( 'model' => 'c3',
'items' => array( 'edit_field_label1',
'integrated_edit_field',
'edit_field_tooltip1' ),
'align' => 'left',
'orientation' => 'horizontal' ),
'c6' => array( 'model' => 'c3',
'items' => array( 'edit_field_label',
'integrated_edit_field2',
'edit_field_tooltip' ),
'orientation' => 'vertical',
'align' => 'center' ),
'c' => array( 'model' => 'c3',
'items' => array(  ) ),
'c4' => array( 'model' => 'c2',
'items' => array( 'integrated_edit_field3' ),
'align' => 'left',
'orientation' => 'horizontal' ),
'c5' => array( 'model' => 'c3',
'items' => array(  ),
'align' => 'left',
'orientation' => 'horizontal' ),
'c8' => array( 'model' => 'c3',
'items' => array( 'edit_field_label2',
'integrated_edit_field1',
'edit_field_tooltip2' ),
'orientation' => 'horizontal',
'align' => 'right' ) ),
'deferredItems' => array(  ),
'columnCount' => 3,
'inlineLabels' => false,
'separateLabels' => false ) ),
'items' => array( 'add_header' => array( 'type' => 'add_header' ),
'add_message' => array( 'type' => 'add_message' ),
'add_save' => array( 'type' => 'add_save' ),
'add_reset' => array( 'type' => 'add_reset' ),
'add_back_list' => array( 'type' => 'add_back_list' ),
'add_cancel' => array( 'type' => 'add_cancel' ),
'integrated_edit_field2' => array( 'field' => 'cnpj_fornecedor',
'type' => 'edit_field',
'orientation' => 0,
'tooltip' => array( 'field' => 'cnpj_fornecedor',
'table' => 'pedidos',
'type' => 4 ),
'label' => array( 'field' => 'cnpj_fornecedor',
'table' => 'pedidos',
'type' => 3 ),
'nowrap' => true,
'joined' => false,
'separated' => true,
'width' => '500px' ),
'logo' => array( 'type' => 'logo' ),
'menu' => array( 'type' => 'menu',
'menuId' => 'main' ),
'expand_menu_button' => array( 'type' => 'expand_menu_button' ),
'collapse_button' => array( 'type' => 'collapse_button' ),
'integrated_edit_field1' => array( 'field' => 'status',
'type' => 'edit_field',
'orientation' => 0,
'color' => '#ffffff',
'joined' => false,
'separated' => true ),
'integrated_edit_field' => array( 'field' => 'Data_cad',
'type' => 'edit_field',
'orientation' => 0,
'color' => '#ffffff',
'joined' => false,
'separated' => true ),
'edit_field_label' => array( 'type' => 'edit_field_label',
'field' => 'cnpj_fornecedor',
'separated' => true,
'label' => array( 'field' => 'cnpj_fornecedor',
'table' => 'pedidos',
'type' => 3 ),
'nowrap' => true,
'bold' => true,
'font-size' => '20px' ),
'edit_field_tooltip' => array( 'type' => 'edit_field_tooltip',
'field' => 'cnpj_fornecedor',
'separated' => true,
'tooltip' => array( 'field' => 'cnpj_fornecedor',
'table' => null,
'type' => 4 ) ),
'edit_field_label1' => array( 'type' => 'edit_field_label',
'field' => 'Data_cad',
'separated' => true,
'color' => '#ffffff' ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'userinfo_link',
'logout_link',
'adminarea_link',
'changepassword_link' ) ),
'changepassword_link' => array( 'type' => 'changepassword_link' ),
'adminarea_link' => array( 'type' => 'adminarea_link' ),
'loginform_login' => array( 'type' => 'loginform_login',
'popup' => false ),
'userinfo_link' => array( 'type' => 'userinfo_link' ),
'logout_link' => array( 'type' => 'logout_link' ),
'edit_field_tooltip1' => array( 'type' => 'edit_field_tooltip',
'field' => 'Data_cad',
'separated' => true ),
'edit_field_label2' => array( 'type' => 'edit_field_label',
'field' => 'status',
'separated' => true,
'color' => '#ffffff' ),
'edit_field_tooltip2' => array( 'type' => 'edit_field_tooltip',
'field' => 'status',
'separated' => true ),
'integrated_edit_field3' => array( 'field' => 'Exercicio',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'notifications' => array( 'type' => 'notifications' ),
'expand_button' => array( 'type' => 'expand_button' ) ),
'dbProps' => array(  ),
'version' => 11,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right' );
		?>