<?php
			$optionsArray = array( 'totals' => array( 'cod' => array( 'totalsType' => '' ),
'status' => array( 'totalsType' => '' ),
'Data_cad' => array( 'totalsType' => '' ),
'Nome' => array( 'totalsType' => '' ),
'Execício' => array( 'totalsType' => '' ),
'cnpj_fornecedor' => array( 'totalsType' => '' ),
'Num_NP' => array( 'totalsType' => '' ),
'Parcela' => array( 'totalsType' => '' ),
'Drae' => array( 'totalsType' => '' ),
'Municipio' => array( 'totalsType' => '' ),
'Bairro' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'Nome',
'Parcela',
'cod',
'status',
'Data_cad',
'Execício',
'cnpj_fornecedor',
'Num_NP',
'Drae',
'Municipio',
'Bairro' ),
'exportFields' => array( 'Parcela',
'Nome',
'cod',
'status',
'Data_cad',
'Execício',
'cnpj_fornecedor',
'Num_NP',
'Drae',
'Municipio',
'Bairro' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'Nome' => array( 'export_field2' ),
'Parcela' => array( 'export_field9' ),
'cod' => array( 'export_field' ),
'status' => array( 'export_field1' ),
'Data_cad' => array( 'export_field3' ),
'Execício' => array( 'export_field4' ),
'cnpj_fornecedor' => array( 'export_field5' ),
'Num_NP' => array( 'export_field6' ),
'Drae' => array( 'export_field7' ),
'Municipio' => array( 'export_field8' ),
'Bairro' => array( 'export_field10' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field9',
'export_field2',
'export_field',
'export_field1',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field10' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field9' => 'grid',
'export_field2' => 'grid',
'export_field' => 'grid',
'export_field1' => 'grid',
'export_field3' => 'grid',
'export_field4' => 'grid',
'export_field5' => 'grid',
'export_field6' => 'grid',
'export_field7' => 'grid',
'export_field8' => 'grid',
'export_field10' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field2',
'export_field9',
'export_field',
'export_field1',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field10' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field9',
'export_field2',
'export_field',
'export_field1',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field10' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field2' => array( 'field' => 'Nome',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 'Parcela',
'type' => 'export_field' ),
'export_field' => array( 'field' => 'cod',
'type' => 'export_field' ),
'export_field1' => array( 'field' => 'status',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'Data_cad',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 'Execício',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 'cnpj_fornecedor',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 'Num_NP',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 'Drae',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'Municipio',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 'Bairro',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 11,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>