<?php
			$optionsArray = array( 'pdf' => array( 'pdfView' => true,
'orientation' => 'portrait',
'scale' => 100 ),
'details' => array( 'itens' => array( 'displayPreview' => 1,
'previewPageId' => 'print' ) ),
'master' => array( 'np' => array( 'preview' => true ) ),
'totals' => array( 'cod' => array( 'totalsType' => '' ),
'Exercicio' => array( 'totalsType' => '' ),
'cnpj_escola' => array( 'totalsType' => '' ),
'cnpj_fornecedor' => array( 'totalsType' => '' ),
'Saldo' => array( 'totalsType' => 'TOTAL' ),
'status' => array( 'totalsType' => '' ),
'Data_cad' => array( 'totalsType' => '' ),
'usuario' => array( 'totalsType' => '' ),
'Cod_np' => array( 'totalsType' => '' ),
'Parcela' => array( 'totalsType' => '' ),
'Bairro' => array( 'totalsType' => '' ),
'Cidade' => array( 'totalsType' => '' ),
'Valor_np' => array( 'totalsType' => '' ),
'Nome' => array( 'totalsType' => '' ),
'Valor' => array( 'totalsType' => '' ),
'Debito' => array( 'totalsType' => '' ),
'valor - debito' => array( 'totalsType' => '' ),
'agf' => array( 'totalsType' => '' ),
'Num_NP' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'cnpj_fornecedor',
'Parcela',
'status',
'Data_cad',
'Exercicio',
'Num_NP' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'cnpj_fornecedor' => array( 'simple_grid_field3',
'simple_grid_field' ),
'Parcela' => array( 'grid_field',
'grid_field_label' ),
'status' => array( 'grid_field2',
'grid_field_label2' ),
'Data_cad' => array( 'grid_field4',
'grid_field_label4' ),
'Saldo' => array( 'grid_field_totals' ),
'Exercicio' => array( 'grid_field1',
'grid_field_label1' ),
'Num_NP' => array( 'grid_field3',
'grid_field_label3' ) ),
'hideEmptyFields' => array(  ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array( 'print_pages',
'grid_inline_cancel',
'inline_add' ),
'below-grid' => array(  ),
'top' => array( 'print_header',
'master_info',
'print_pdf',
'image',
'print_subheader' ),
'grid' => array( 'simple_grid_field',
'text',
'simple_grid_field3',
'grid_field_label3',
'grid_field3',
'grid_field_label4',
'grid_field4',
'grid_field_label2',
'grid_field2',
'grid_field_totals',
'details_preview',
'grid_field1',
'grid_field_label1',
'grid_field_label',
'grid_field',
'image1' ) ),
'formXtTags' => array( 'above-grid' => array( 'print_pages',
'inline_cancel',
'inlineadd_link' ),
'below-grid' => array(  ) ),
'itemForms' => array( 'print_pages' => 'above-grid',
'grid_inline_cancel' => 'above-grid',
'inline_add' => 'above-grid',
'print_header' => 'top',
'master_info' => 'top',
'print_pdf' => 'top',
'image' => 'top',
'print_subheader' => 'top',
'simple_grid_field' => 'grid',
'text' => 'grid',
'simple_grid_field3' => 'grid',
'grid_field_label3' => 'grid',
'grid_field3' => 'grid',
'grid_field_label4' => 'grid',
'grid_field4' => 'grid',
'grid_field_label2' => 'grid',
'grid_field2' => 'grid',
'grid_field_totals' => 'grid',
'details_preview' => 'grid',
'grid_field1' => 'grid',
'grid_field_label1' => 'grid',
'grid_field_label' => 'grid',
'grid_field' => 'grid',
'image1' => 'grid' ),
'itemLocations' => array( 'simple_grid_field' => array( 'location' => 'grid',
'cellId' => 'headcell_field' ),
'text' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'simple_grid_field3' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'grid_field_label3' => array( 'location' => 'grid',
'cellId' => 'headcell_field1' ),
'grid_field3' => array( 'location' => 'grid',
'cellId' => 'cell_field1' ),
'grid_field_label4' => array( 'location' => 'grid',
'cellId' => 'headcell_field3' ),
'grid_field4' => array( 'location' => 'grid',
'cellId' => 'cell_field3' ),
'grid_field_label2' => array( 'location' => 'grid',
'cellId' => 'headcell_field5' ),
'grid_field2' => array( 'location' => 'grid',
'cellId' => 'cell_field5' ),
'grid_field_totals' => array( 'location' => 'grid',
'cellId' => 'footcell_field5' ),
'details_preview' => array( 'location' => 'grid',
'cellId' => 'cell_dpreview14' ),
'grid_field1' => array( 'location' => 'grid',
'cellId' => 'cell_field8' ),
'grid_field_label1' => array( 'location' => 'grid',
'cellId' => 'headcell_field4' ),
'grid_field_label' => array( 'location' => 'grid',
'cellId' => 'headcell_field7' ),
'grid_field' => array( 'location' => 'grid',
'cellId' => 'cell_field13' ),
'image1' => array( 'location' => 'grid',
'cellId' => 'cell_dpreview' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'print_header' => array( 'print_header' ),
'print_subheader' => array( 'print_subheader' ),
'print_pages' => array( 'print_pages' ),
'grid_field' => array( 'simple_grid_field3',
'grid_field',
'grid_field2',
'grid_field4',
'grid_field1',
'grid_field3' ),
'master_info' => array( 'master_info' ),
'details_preview' => array( 'details_preview' ),
'grid_field_label' => array( 'simple_grid_field',
'grid_field_label',
'grid_field_label2',
'grid_field_label4',
'grid_field_label1',
'grid_field_label3' ),
'text' => array( 'text' ),
'image' => array( 'image',
'image1' ),
'grid_field_totals' => array( 'grid_field_totals' ),
'print_pdf' => array( 'print_pdf' ),
'inline_add' => array( 'inline_add' ),
'grid_inline_cancel' => array( 'grid_inline_cancel' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'headcell_field' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array( 'cnpj_fornecedor_fieldheadercolumn' ),
'items' => array( 'simple_grid_field' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field1' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array( 'Num_NP_fieldheadercolumn' ),
'items' => array( 'grid_field_label3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field7' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array( 'Parcela_fieldheadercolumn' ),
'items' => array( 'grid_field_label' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field4' => array( 'cols' => array( 3 ),
'rows' => array( 0 ),
'tags' => array( 'Exercicio_fieldheadercolumn' ),
'items' => array( 'grid_field_label1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field3' => array( 'cols' => array( 4 ),
'rows' => array( 0 ),
'tags' => array( 'Data_cad_fieldheadercolumn' ),
'items' => array( 'grid_field_label4' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field5' => array( 'cols' => array( 5 ),
'rows' => array( 0 ),
'tags' => array( 'status_fieldheadercolumn' ),
'items' => array( 'grid_field_label2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'text',
'simple_grid_field3' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'cell_field1' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array( 'Num_NP_fieldcolumn' ),
'items' => array( 'grid_field3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field13' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array( 'Parcela_fieldcolumn' ),
'items' => array( 'grid_field' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field8' => array( 'cols' => array( 3 ),
'rows' => array( 1 ),
'tags' => array( 'Exercicio_fieldcolumn' ),
'items' => array( 'grid_field1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field3' => array( 'cols' => array( 4 ),
'rows' => array( 1 ),
'tags' => array( 'Data_cad_fieldcolumn' ),
'items' => array( 'grid_field4' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field5' => array( 'cols' => array( 5 ),
'rows' => array( 1 ),
'tags' => array( 'status_fieldcolumn' ),
'items' => array( 'grid_field2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_dpreview14' => array( 'cols' => array( 0,
1,
2,
3,
4,
5 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'details_preview' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'cell_dpreview10' => array( 'cols' => array( 0,
1,
2 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_dpreview' => array( 'cols' => array( 3,
4,
5 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'image1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'footcell_field' => array( 'cols' => array( 0 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field1' => array( 'cols' => array( 1,
2,
3 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field3' => array( 'cols' => array( 4 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field5' => array( 'cols' => array( 5 ),
'rows' => array( 4 ),
'tags' => array( 'Saldo_fieldfootercolumn' ),
'items' => array( 'grid_field_totals' ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 6,
'height' => 5 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array( 'print_pages' => array( 'tag' => 'PRINT_PAGES',
'type' => 2 ) ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'gridType' => 0,
'recsPerRow' => 1,
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false ),
'misc' => array( 'type' => 'print',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'dataGrid' => array( 'groupFields' => array(  ) ) );
			$pageArray = array( 'id' => 'print1',
'type' => 'print',
'layoutId' => 'basic',
'disabled' => 0,
'default' => 0,
'forms' => array( 'above-grid' => array( 'modelId' => 'print-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'print_pages',
'grid_inline_cancel',
'inline_add' ),
'align' => 'right' ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'print-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'pageBreak' => '',
'background' => '#d4cbcb' ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'print-header',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c',
'colspan' => 1 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c5',
'colspan' => 1 ) ) ),
array( 'cells' => array( array( 'cell' => 'c2',
'colspan' => 1 ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c6',
'colspan' => 1 ) ) ),
array( 'cells' => array( array( 'cell' => 'c4',
'colspan' => 1 ) ),
'section' => '' ) ),
'cells' => array( 'c2' => array( 'model' => 'c2',
'items' => array( 'print_header' ),
'align' => 'center' ),
'c4' => array( 'model' => 'c4',
'items' => array( 'master_info' ) ),
'c' => array( 'model' => 'c1',
'items' => array( 'print_pdf' ),
'orientation' => 'horizontal' ),
'c5' => array( 'model' => 'c2',
'items' => array( 'image' ),
'align' => 'center' ),
'c6' => array( 'model' => 'c2',
'items' => array( 'print_subheader' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'horizontal-grid',
'grid' => array( array( 'section' => 'head',
'cells' => array( array( 'cell' => 'headcell_field' ),
array( 'cell' => 'headcell_field1' ),
array( 'cell' => 'headcell_field7' ),
array( 'cell' => 'headcell_field4' ),
array( 'cell' => 'headcell_field3' ),
array( 'cell' => 'headcell_field5' ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_field' ),
array( 'cell' => 'cell_field1' ),
array( 'cell' => 'cell_field13' ),
array( 'cell' => 'cell_field8' ),
array( 'cell' => 'cell_field3' ),
array( 'cell' => 'cell_field5' ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_dpreview14',
'colspan' => 6 ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_dpreview10',
'colspan' => 3 ),
array( 'cell' => 'cell_dpreview',
'colspan' => 3 ) ) ),
array( 'section' => 'foot',
'cells' => array( array( 'cell' => 'footcell_field' ),
array( 'cell' => 'footcell_field1',
'colspan' => 3 ),
array( 'cell' => 'footcell_field3' ),
array( 'cell' => 'footcell_field5' ) ) ) ),
'cells' => array( 'headcell_field' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field' ),
'field' => 'cnpj_fornecedor',
'columnName' => 'field' ),
'cell_field' => array( 'model' => 'cell_field',
'items' => array( 'text',
'simple_grid_field3' ),
'background' => '#ede7e7',
'field' => 'cnpj_fornecedor',
'columnName' => 'field' ),
'footcell_field' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field1' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label3' ),
'field' => 'Num_NP',
'columnName' => 'field' ),
'cell_field1' => array( 'model' => 'cell_field',
'items' => array( 'grid_field3' ),
'background' => '#ede7e7',
'field' => 'Num_NP',
'columnName' => 'field' ),
'footcell_field1' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field3' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label4' ),
'field' => 'Data_cad',
'columnName' => 'field' ),
'cell_field3' => array( 'model' => 'cell_field',
'items' => array( 'grid_field4' ),
'background' => '#ede7e7',
'field' => 'Data_cad',
'columnName' => 'field' ),
'footcell_field3' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field5' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label2' ),
'field' => 'status',
'columnName' => 'field' ),
'cell_field5' => array( 'model' => 'cell_field',
'items' => array( 'grid_field2' ),
'background' => '#ede7e7',
'field' => 'status',
'columnName' => 'field' ),
'footcell_field5' => array( 'model' => 'footcell_field',
'items' => array( 'grid_field_totals' ),
'field' => 'Saldo',
'columnName' => 'field' ),
'cell_dpreview10' => array( 'model' => 'cell_dpreview',
'items' => array(  ),
'align' => 'right' ),
'cell_dpreview14' => array( 'model' => 'cell_dpreview',
'items' => array( 'details_preview' ) ),
'cell_field8' => array( 'model' => 'cell_field',
'items' => array( 'grid_field1' ),
'background' => '#ede7e7',
'field' => 'Exercicio',
'columnName' => 'field' ),
'headcell_field4' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label1' ),
'field' => 'Exercicio',
'columnName' => 'field' ),
'headcell_field7' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label' ),
'field' => 'Parcela',
'columnName' => 'field' ),
'cell_field13' => array( 'model' => 'cell_field',
'items' => array( 'grid_field' ),
'background' => '#ede7e7',
'field' => 'Parcela',
'columnName' => 'field' ),
'cell_dpreview' => array( 'model' => 'cell_dpreview',
'items' => array( 'image1' ),
'align' => 'center' ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'print_header' => array( 'type' => 'print_header',
'title' => array( 'page' => 'print1',
'table' => 'pedidos',
'type' => 7 ) ),
'print_subheader' => array( 'type' => 'print_subheader' ),
'print_pages' => array( 'type' => 'print_pages' ),
'simple_grid_field3' => array( 'field' => 'cnpj_fornecedor',
'type' => 'grid_field' ),
'master_info' => array( 'type' => 'master_info',
'tables' => array( 'np' => 'true' ),
'background' => 'transparent' ),
'details_preview' => array( 'type' => 'details_preview',
'table' => 'itens',
'items' => array(  ),
'popup' => false,
'pageId' => 'print',
'caption' => array( 'page' => 'print',
'table' => 'itens',
'type' => 7 ) ),
'simple_grid_field' => array( 'type' => 'grid_field_label',
'field' => 'cnpj_fornecedor',
'label' => array( 'field' => 'cnpj_fornecedor',
'table' => 'pedidos',
'type' => 3 ) ),
'grid_field' => array( 'field' => 'Parcela',
'type' => 'grid_field' ),
'grid_field_label' => array( 'type' => 'grid_field_label',
'field' => 'Parcela' ),
'grid_field2' => array( 'field' => 'status',
'type' => 'grid_field' ),
'grid_field_label2' => array( 'type' => 'grid_field_label',
'field' => 'status' ),
'grid_field4' => array( 'field' => 'Data_cad',
'type' => 'grid_field' ),
'grid_field_label4' => array( 'type' => 'grid_field_label',
'field' => 'Data_cad' ),
'text' => array( 'type' => 'text',
'label' => array( 'text' => '                                                                ',
'type' => 0 ),
'editedByRte' => false ),
'image' => array( 'type' => 'image',
'image' => array( 'image' => 'logo_gov.png',
'source' => 2 ) ),
'image1' => array( 'type' => 'image',
'image' => array( 'image' => 'certifico2.png',
'source' => 2 ),
'width' => '',
'height' => '' ),
'grid_field_totals' => array( 'type' => 'grid_field_totals',
'field' => 'Saldo',
'totals' => 'TOTAL' ),
'grid_field1' => array( 'field' => 'Exercicio',
'type' => 'grid_field' ),
'grid_field_label1' => array( 'type' => 'grid_field_label',
'field' => 'Exercicio' ),
'grid_field3' => array( 'field' => 'Num_NP',
'type' => 'grid_field' ),
'grid_field_label3' => array( 'type' => 'grid_field_label',
'field' => 'Num_NP' ),
'print_pdf' => array( 'type' => 'print_pdf',
'targetPages' => array(  ),
'splitModes' => array(  ),
'scopes' => array(  ),
'label' => array( 'type' => 0,
'text' => 'Baixar PDF' ),
'pageSize' => 'A4' ),
'inline_add' => array( 'type' => 'inline_add',
'detailsOnly' => true ),
'grid_inline_cancel' => array( 'type' => 'grid_inline_cancel' ) ),
'dbProps' => array(  ),
'version' => 11,
'pageWidth' => 'standard',
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right' );
		?>