<?php
			$optionsArray = array( 'pdf' => array( 'pdfView' => true,
'orientation' => 'portrait',
'scale' => 100 ),
'details' => array( 'itens_escola' => array( 'displayPreview' => 1,
'previewPageId' => 'print' ) ),
'master' => array( 'NP_escola' => array( 'preview' => true ) ),
'totals' => array( 'cod' => array( 'totalsType' => '' ),
'Exercicio' => array( 'totalsType' => '' ),
'cnpj_escola' => array( 'totalsType' => '' ),
'cnpj_fornecedor' => array( 'totalsType' => '' ),
'Saldo' => array( 'totalsType' => 'TOTAL' ),
'status' => array( 'totalsType' => '' ),
'Data_cad' => array( 'totalsType' => '' ),
'usuario' => array( 'totalsType' => '' ),
'Cod_np' => array( 'totalsType' => '' ),
'Parcela' => array( 'totalsType' => '' ),
'Valor_np' => array( 'totalsType' => '' ),
'Nome' => array( 'totalsType' => '' ),
'Bairro' => array( 'totalsType' => '' ),
'Cidade' => array( 'totalsType' => '' ),
'Valor' => array( 'totalsType' => '' ),
'Num_NP' => array( 'totalsType' => '' ),
'Debito' => array( 'totalsType' => '' ),
'valor - debito' => array( 'totalsType' => '' ),
'agf' => array( 'totalsType' => '' ),
'rac_forn' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'cnpj_fornecedor',
'Data_cad',
'status',
'Exercicio',
'Parcela',
'cod' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'cnpj_fornecedor' => array( 'simple_grid_field',
'simple_grid_field3' ),
'Data_cad' => array( 'grid_field_label4',
'grid_field4' ),
'status' => array( 'grid_field_label2',
'grid_field2' ),
'Saldo' => array( 'grid_field_totals' ),
'Exercicio' => array( 'grid_field1',
'grid_field_label1' ),
'Parcela' => array( 'grid_field_label',
'grid_field' ),
'cod' => array( 'grid_field3',
'grid_field_label3' ) ),
'hideEmptyFields' => array(  ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array( 'print_pages' ),
'below-grid' => array(  ),
'top' => array( 'print_header',
'print_subheader',
'master_info',
'print_pdf',
'image',
'text1' ),
'grid' => array( 'simple_grid_field',
'text',
'simple_grid_field3',
'grid_field_label4',
'grid_field4',
'grid_field_label2',
'grid_field2',
'grid_field_totals',
'grid_field1',
'grid_field_label1',
'grid_field_label',
'grid_field',
'image1',
'details_preview',
'grid_field_label3',
'grid_field3' ) ),
'formXtTags' => array( 'above-grid' => array( 'print_pages' ),
'below-grid' => array(  ) ),
'itemForms' => array( 'print_pages' => 'above-grid',
'print_header' => 'top',
'print_subheader' => 'top',
'master_info' => 'top',
'print_pdf' => 'top',
'image' => 'top',
'text1' => 'top',
'simple_grid_field' => 'grid',
'text' => 'grid',
'simple_grid_field3' => 'grid',
'grid_field_label4' => 'grid',
'grid_field4' => 'grid',
'grid_field_label2' => 'grid',
'grid_field2' => 'grid',
'grid_field_totals' => 'grid',
'grid_field1' => 'grid',
'grid_field_label1' => 'grid',
'grid_field_label' => 'grid',
'grid_field' => 'grid',
'image1' => 'grid',
'details_preview' => 'grid',
'grid_field_label3' => 'grid',
'grid_field3' => 'grid' ),
'itemLocations' => array( 'simple_grid_field' => array( 'location' => 'grid',
'cellId' => 'headcell_field' ),
'text' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'simple_grid_field3' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'grid_field_label4' => array( 'location' => 'grid',
'cellId' => 'headcell_field3' ),
'grid_field4' => array( 'location' => 'grid',
'cellId' => 'cell_field3' ),
'grid_field_label2' => array( 'location' => 'grid',
'cellId' => 'headcell_field5' ),
'grid_field2' => array( 'location' => 'grid',
'cellId' => 'cell_field5' ),
'grid_field_totals' => array( 'location' => 'grid',
'cellId' => 'footcell_field5' ),
'grid_field1' => array( 'location' => 'grid',
'cellId' => 'cell_field8' ),
'grid_field_label1' => array( 'location' => 'grid',
'cellId' => 'headcell_field4' ),
'grid_field_label' => array( 'location' => 'grid',
'cellId' => 'headcell_field7' ),
'grid_field' => array( 'location' => 'grid',
'cellId' => 'cell_field13' ),
'image1' => array( 'location' => 'grid',
'cellId' => 'cell_dpreview' ),
'details_preview' => array( 'location' => 'grid',
'cellId' => 'cell_dpreview11' ),
'grid_field_label3' => array( 'location' => 'grid',
'cellId' => 'headcell_field1' ),
'grid_field3' => array( 'location' => 'grid',
'cellId' => 'cell_field1' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'print_header' => array( 'print_header' ),
'print_subheader' => array( 'print_subheader' ),
'print_pages' => array( 'print_pages' ),
'grid_field_label' => array( 'simple_grid_field',
'grid_field_label4',
'grid_field_label2',
'grid_field_label1',
'grid_field_label',
'grid_field_label3' ),
'grid_field' => array( 'simple_grid_field3',
'grid_field4',
'grid_field2',
'grid_field1',
'grid_field',
'grid_field3' ),
'master_info' => array( 'master_info' ),
'text' => array( 'text',
'text1' ),
'grid_field_totals' => array( 'grid_field_totals' ),
'image' => array( 'image1',
'image' ),
'print_pdf' => array( 'print_pdf' ),
'details_preview' => array( 'details_preview' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'headcell_field2' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array( 'cnpj_fornecedor_fieldheadercolumn' ),
'items' => array( 'simple_grid_field' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field7' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array( 'Parcela_fieldheadercolumn' ),
'items' => array( 'grid_field_label' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field4' => array( 'cols' => array( 3 ),
'rows' => array( 0 ),
'tags' => array( 'Exercicio_fieldheadercolumn' ),
'items' => array( 'grid_field_label1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field3' => array( 'cols' => array( 4 ),
'rows' => array( 0 ),
'tags' => array( 'Data_cad_fieldheadercolumn' ),
'items' => array( 'grid_field_label4' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field5' => array( 'cols' => array( 5 ),
'rows' => array( 0 ),
'tags' => array( 'status_fieldheadercolumn' ),
'items' => array( 'grid_field_label2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field1' => array( 'cols' => array( 6 ),
'rows' => array( 0 ),
'tags' => array( 'cod_fieldheadercolumn' ),
'items' => array( 'grid_field_label3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field6' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'text',
'simple_grid_field3' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'cell_field13' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array( 'Parcela_fieldcolumn' ),
'items' => array( 'grid_field' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field8' => array( 'cols' => array( 3 ),
'rows' => array( 1 ),
'tags' => array( 'Exercicio_fieldcolumn' ),
'items' => array( 'grid_field1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field3' => array( 'cols' => array( 4 ),
'rows' => array( 1 ),
'tags' => array( 'Data_cad_fieldcolumn' ),
'items' => array( 'grid_field4' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field5' => array( 'cols' => array( 5 ),
'rows' => array( 1 ),
'tags' => array( 'status_fieldcolumn' ),
'items' => array( 'grid_field2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field1' => array( 'cols' => array( 6 ),
'rows' => array( 1 ),
'tags' => array( 'cod_fieldcolumn' ),
'items' => array( 'grid_field3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field8' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field6' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field7' => array( 'cols' => array( 2 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field9' => array( 'cols' => array( 3 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field10' => array( 'cols' => array( 4 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field11' => array( 'cols' => array( 5 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field2' => array( 'cols' => array( 6 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field9' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_dpreview11' => array( 'cols' => array( 1,
2,
3,
4,
5,
6 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'details_preview' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'headcell_field10' => array( 'cols' => array( 0 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_dpreview10' => array( 'cols' => array( 1,
2 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_dpreview' => array( 'cols' => array( 3,
4,
5 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'image1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'cell_field4' => array( 'cols' => array( 6 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field11' => array( 'cols' => array( 0 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_dpreview6' => array( 'cols' => array( 1,
2,
3,
4,
5,
6 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field12' => array( 'cols' => array( 0 ),
'rows' => array( 6 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field' => array( 'cols' => array( 1 ),
'rows' => array( 6 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field1' => array( 'cols' => array( 2,
3 ),
'rows' => array( 6 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field3' => array( 'cols' => array( 4 ),
'rows' => array( 6 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field5' => array( 'cols' => array( 5 ),
'rows' => array( 6 ),
'tags' => array( 'Saldo_fieldfootercolumn' ),
'items' => array( 'grid_field_totals' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field2' => array( 'cols' => array( 6 ),
'rows' => array( 6 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 7,
'height' => 7 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array( 'print_pages' => array( 'tag' => 'PRINT_PAGES',
'type' => 2 ) ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'gridType' => 0,
'recsPerRow' => 1,
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false ),
'misc' => array( 'type' => 'print',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'dataGrid' => array( 'groupFields' => array(  ) ) );
			$pageArray = array( 'id' => 'print',
'type' => 'print',
'layoutId' => 'basic',
'disabled' => 0,
'default' => 0,
'forms' => array( 'above-grid' => array( 'modelId' => 'print-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'print_pages' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'print-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'print-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c' ) ) ),
array( 'cells' => array( array( 'cell' => 'c2' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c4' ) ),
'section' => '' ) ),
'cells' => array( 'c2' => array( 'model' => 'c2',
'items' => array( 'print_header',
'print_subheader' ),
'align' => 'center' ),
'c4' => array( 'model' => 'c4',
'items' => array( 'master_info' ) ),
'c1' => array( 'model' => 'c1',
'items' => array( 'print_pdf' ) ),
'c' => array( 'model' => 'c2',
'items' => array( 'image',
'text1' ),
'align' => 'center',
'orientation' => 'vertical' ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'horizontal-grid',
'grid' => array( array( 'section' => 'head',
'cells' => array( array( 'cell' => 'headcell_field2' ),
array( 'cell' => 'headcell_field' ),
array( 'cell' => 'headcell_field7' ),
array( 'cell' => 'headcell_field4' ),
array( 'cell' => 'headcell_field3' ),
array( 'cell' => 'headcell_field5' ),
array( 'cell' => 'headcell_field1' ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'headcell_field6' ),
array( 'cell' => 'cell_field' ),
array( 'cell' => 'cell_field13' ),
array( 'cell' => 'cell_field8' ),
array( 'cell' => 'cell_field3' ),
array( 'cell' => 'cell_field5' ),
array( 'cell' => 'cell_field1' ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'headcell_field8' ),
array( 'cell' => 'cell_field6' ),
array( 'cell' => 'cell_field7' ),
array( 'cell' => 'cell_field9' ),
array( 'cell' => 'cell_field10' ),
array( 'cell' => 'cell_field11' ),
array( 'cell' => 'cell_field2' ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'headcell_field9' ),
array( 'cell' => 'cell_dpreview11',
'colspan' => 6 ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'headcell_field10' ),
array( 'cell' => 'cell_dpreview10',
'colspan' => 2 ),
array( 'cell' => 'cell_dpreview',
'colspan' => 3 ),
array( 'cell' => 'cell_field4' ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'headcell_field11' ),
array( 'cell' => 'cell_dpreview6',
'colspan' => 6 ) ) ),
array( 'section' => 'foot',
'cells' => array( array( 'cell' => 'headcell_field12' ),
array( 'cell' => 'footcell_field' ),
array( 'cell' => 'footcell_field1',
'colspan' => 2 ),
array( 'cell' => 'footcell_field3' ),
array( 'cell' => 'footcell_field5' ),
array( 'cell' => 'footcell_field2' ) ) ) ),
'cells' => array( 'headcell_field' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field' ),
'field' => '',
'columnName' => '' ),
'cell_field' => array( 'model' => 'cell_field',
'items' => array( 'text',
'simple_grid_field3' ),
'field' => '',
'columnName' => '',
'background' => '#ede7e7' ),
'footcell_field' => array( 'model' => 'footcell_field',
'items' => array(  ),
'field' => '',
'columnName' => '' ),
'footcell_field1' => array( 'model' => 'footcell_field',
'items' => array(  ),
'field' => '',
'columnName' => '' ),
'headcell_field3' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label4' ),
'field' => '',
'columnName' => '',
'align' => 'center' ),
'cell_field3' => array( 'model' => 'cell_field',
'items' => array( 'grid_field4' ),
'field' => '',
'columnName' => '',
'background' => '#ede7e7',
'align' => 'center' ),
'footcell_field3' => array( 'model' => 'footcell_field',
'items' => array(  ),
'field' => '',
'columnName' => '' ),
'headcell_field5' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label2' ),
'field' => '',
'columnName' => '',
'align' => 'center' ),
'cell_field5' => array( 'model' => 'cell_field',
'items' => array( 'grid_field2' ),
'field' => '',
'columnName' => '',
'background' => '#ede7e7',
'align' => 'center' ),
'footcell_field5' => array( 'model' => 'footcell_field',
'items' => array( 'grid_field_totals' ),
'field' => '',
'columnName' => '' ),
'cell_dpreview6' => array( 'model' => 'cell_dpreview',
'items' => array(  ),
'field' => '',
'columnName' => '',
'background' => '#ccc4c4' ),
'cell_dpreview10' => array( 'model' => 'cell_dpreview',
'items' => array(  ),
'field' => '',
'columnName' => '',
'align' => 'right' ),
'cell_field8' => array( 'model' => 'cell_field',
'items' => array( 'grid_field1' ),
'field' => '',
'columnName' => '',
'background' => '#ede7e7',
'align' => 'center' ),
'headcell_field4' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label1' ),
'field' => '',
'columnName' => '',
'align' => 'center' ),
'headcell_field7' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label' ),
'field' => '',
'columnName' => '',
'align' => 'center' ),
'cell_field13' => array( 'model' => 'cell_field',
'items' => array( 'grid_field' ),
'field' => '',
'columnName' => '',
'background' => '#ede7e7',
'align' => 'center' ),
'cell_dpreview' => array( 'model' => 'cell_dpreview',
'items' => array( 'image1' ),
'field' => '',
'columnName' => '',
'align' => 'center' ),
'cell_dpreview11' => array( 'model' => 'cell_dpreview',
'items' => array( 'details_preview' ),
'field' => '',
'columnName' => '' ),
'cell_field6' => array( 'model' => 'cell_field',
'items' => array(  ),
'field' => '',
'columnName' => '' ),
'cell_field7' => array( 'model' => 'cell_field',
'items' => array(  ),
'field' => '',
'columnName' => '' ),
'cell_field9' => array( 'model' => 'cell_field',
'items' => array(  ),
'field' => '',
'columnName' => '' ),
'cell_field10' => array( 'model' => 'cell_field',
'items' => array(  ),
'field' => '',
'columnName' => '' ),
'cell_field11' => array( 'model' => 'cell_field',
'items' => array(  ),
'field' => '',
'columnName' => '' ),
'headcell_field1' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label3' ),
'field' => '',
'columnName' => '' ),
'cell_field1' => array( 'model' => 'cell_field',
'items' => array( 'grid_field3' ),
'field' => '',
'columnName' => '' ),
'cell_field2' => array( 'model' => 'cell_field',
'items' => array(  ),
'field' => '',
'columnName' => '' ),
'cell_field4' => array( 'model' => 'cell_field',
'items' => array(  ),
'field' => '',
'columnName' => '' ),
'footcell_field2' => array( 'model' => 'footcell_field',
'items' => array(  ),
'field' => '',
'columnName' => '' ),
'headcell_field2' => array( 'model' => 'headcell_field',
'items' => array(  ),
'columnName' => '',
'field' => '' ),
'headcell_field6' => array( 'model' => 'cell_field',
'items' => array(  ),
'columnName' => '',
'field' => '' ),
'headcell_field8' => array( 'model' => 'cell_field',
'items' => array(  ),
'columnName' => '',
'field' => '' ),
'headcell_field9' => array( 'model' => 'cell_dpreview',
'items' => array(  ),
'columnName' => '',
'field' => '' ),
'headcell_field10' => array( 'model' => 'cell_dpreview',
'items' => array(  ),
'columnName' => '',
'field' => '' ),
'headcell_field11' => array( 'model' => 'cell_dpreview',
'items' => array(  ),
'columnName' => '',
'field' => '' ),
'headcell_field12' => array( 'model' => 'footcell_field',
'items' => array(  ),
'columnName' => '',
'field' => '' ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'print_header' => array( 'type' => 'print_header',
'title' => array( 'page' => 'print',
'table' => 'Pedidos_escola',
'type' => 7 ) ),
'print_subheader' => array( 'type' => 'print_subheader' ),
'print_pages' => array( 'type' => 'print_pages' ),
'simple_grid_field' => array( 'type' => 'grid_field_label',
'field' => 'cnpj_fornecedor',
'label' => array( 'field' => 'cnpj_fornecedor',
'table' => 'pedidos',
'type' => 3 ) ),
'simple_grid_field3' => array( 'field' => 'cnpj_fornecedor',
'type' => 'grid_field' ),
'master_info' => array( 'type' => 'master_info',
'tables' => array( 'NP_escola' => 'true' ) ),
'text' => array( 'type' => 'text',
'label' => array( 'text' => '                                                                ',
'type' => 0 ),
'editedByRte' => false ),
'grid_field_label4' => array( 'type' => 'grid_field_label',
'field' => 'Data_cad' ),
'grid_field4' => array( 'field' => 'Data_cad',
'type' => 'grid_field' ),
'grid_field_label2' => array( 'type' => 'grid_field_label',
'field' => 'status' ),
'grid_field2' => array( 'field' => 'status',
'type' => 'grid_field' ),
'grid_field_totals' => array( 'type' => 'grid_field_totals',
'field' => 'Saldo',
'totals' => 'TOTAL' ),
'grid_field1' => array( 'field' => 'Exercicio',
'type' => 'grid_field' ),
'grid_field_label1' => array( 'type' => 'grid_field_label',
'field' => 'Exercicio' ),
'grid_field_label' => array( 'type' => 'grid_field_label',
'field' => 'Parcela' ),
'grid_field' => array( 'field' => 'Parcela',
'type' => 'grid_field' ),
'image1' => array( 'type' => 'image',
'image' => array( 'image' => 'certifico2.png',
'source' => 2 ),
'width' => '',
'height' => '' ),
'print_pdf' => array( 'type' => 'print_pdf',
'targetPages' => array(  ),
'splitModes' => array(  ),
'scopes' => array(  ),
'pageSize' => 'A4',
'label' => array( 'type' => 0,
'text' => 'Baixar PDF' ) ),
'details_preview' => array( 'type' => 'details_preview',
'table' => 'itens_escola',
'items' => array(  ),
'popup' => false,
'pageId' => 'print' ),
'image' => array( 'type' => 'image',
'image' => array( 'image' => 'logo_gov.png',
'source' => 2 ) ),
'text1' => array( 'type' => 'text',
'label' => array( 'text' => '                                                             ',
'type' => 0 ),
'editedByRte' => false ),
'grid_field3' => array( 'field' => 'cod',
'type' => 'grid_field' ),
'grid_field_label3' => array( 'type' => 'grid_field_label',
'field' => 'cod' ) ),
'dbProps' => array(  ),
'version' => 11,
'pageWidth' => 'full',
'pageAlign' => 'center',
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right' );
		?>