<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'Data_cad',
'Saldo',
'status',
'Parcela',
'Debito',
'valor - debito',
'agf',
'Num_NP',
'Exercicio' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'Data_cad' => array( 'simple_grid_field4',
'simple_grid_field11' ),
'Saldo' => array( 'simple_grid_field5',
'simple_grid_field8' ),
'status' => array( 'grid_field',
'grid_field_label' ),
'Parcela' => array( 'grid_field5',
'grid_field_label5' ),
'Debito' => array( 'grid_field3',
'grid_field_label3' ),
'valor - debito' => array( 'grid_field4',
'grid_field_label4' ),
'agf' => array( 'grid_field2',
'grid_field_label2' ),
'Num_NP' => array( 'grid_field6',
'grid_field_label6' ),
'Exercicio' => array( 'grid_field7',
'grid_field_label7' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array( 'inline_add' ),
'below-grid' => array(  ),
'top' => array( 'back_master',
'masterlist_header' ),
'grid' => array( 'grid_field_label5',
'grid_field5',
'simple_grid_field11',
'simple_grid_field4',
'grid_field_label',
'grid_field',
'grid_field_label2',
'grid_field2',
'grid_field_label3',
'grid_field3',
'grid_field_label4',
'grid_field4',
'simple_grid_field8',
'simple_grid_field5',
'grid_field_label6',
'grid_field6',
'grid_field_label7',
'grid_field7',
'grid_inline_cancel' ) ),
'formXtTags' => array( 'above-grid' => array( 'inlineadd_link' ),
'below-grid' => array(  ) ),
'itemForms' => array( 'inline_add' => 'above-grid',
'back_master' => 'top',
'masterlist_header' => 'top',
'grid_field_label5' => 'grid',
'grid_field5' => 'grid',
'simple_grid_field11' => 'grid',
'simple_grid_field4' => 'grid',
'grid_field_label' => 'grid',
'grid_field' => 'grid',
'grid_field_label2' => 'grid',
'grid_field2' => 'grid',
'grid_field_label3' => 'grid',
'grid_field3' => 'grid',
'grid_field_label4' => 'grid',
'grid_field4' => 'grid',
'simple_grid_field8' => 'grid',
'simple_grid_field5' => 'grid',
'grid_field_label6' => 'grid',
'grid_field6' => 'grid',
'grid_field_label7' => 'grid',
'grid_field7' => 'grid',
'grid_inline_cancel' => 'grid' ),
'itemLocations' => array( 'grid_field_label5' => array( 'location' => 'grid',
'cellId' => 'headcell_field2' ),
'grid_field5' => array( 'location' => 'grid',
'cellId' => 'cell_field2' ),
'simple_grid_field11' => array( 'location' => 'grid',
'cellId' => 'headcell_field5' ),
'simple_grid_field4' => array( 'location' => 'grid',
'cellId' => 'cell_field5' ),
'grid_field_label' => array( 'location' => 'grid',
'cellId' => 'headcell_field3' ),
'grid_field' => array( 'location' => 'grid',
'cellId' => 'cell_field3' ),
'grid_field_label2' => array( 'location' => 'grid',
'cellId' => 'headcell_field1' ),
'grid_field2' => array( 'location' => 'grid',
'cellId' => 'cell_field1' ),
'grid_field_label3' => array( 'location' => 'grid',
'cellId' => 'headcell_field4' ),
'grid_field3' => array( 'location' => 'grid',
'cellId' => 'cell_field4' ),
'grid_field_label4' => array( 'location' => 'grid',
'cellId' => 'headcell_field6' ),
'grid_field4' => array( 'location' => 'grid',
'cellId' => 'cell_field6' ),
'simple_grid_field8' => array( 'location' => 'grid',
'cellId' => 'cell_field8' ),
'simple_grid_field5' => array( 'location' => 'grid',
'cellId' => 'cell_field9' ),
'grid_field_label6' => array( 'location' => 'grid',
'cellId' => 'headcell_field8' ),
'grid_field6' => array( 'location' => 'grid',
'cellId' => 'cell_field12' ),
'grid_field_label7' => array( 'location' => 'grid',
'cellId' => 'headcell_field' ),
'grid_field7' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'grid_inline_cancel' => array( 'location' => 'grid',
'cellId' => 'cell_icons' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'masterlist_header' => array( 'masterlist_header' ),
'back_master' => array( 'back_master' ),
'grid_field' => array( 'simple_grid_field4',
'simple_grid_field5',
'grid_field',
'grid_field5',
'grid_field3',
'grid_field4',
'grid_field2',
'grid_field6',
'grid_field7' ),
'grid_field_label' => array( 'simple_grid_field8',
'simple_grid_field11',
'grid_field_label',
'grid_field_label5',
'grid_field_label3',
'grid_field_label4',
'grid_field_label2',
'grid_field_label6',
'grid_field_label7' ),
'inline_add' => array( 'inline_add' ),
'grid_inline_cancel' => array( 'grid_inline_cancel' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'headcell_icons' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field2' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array( 'Parcela_fieldheadercolumn' ),
'items' => array( 'grid_field_label5' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field5' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array( 'Data_cad_fieldheadercolumn' ),
'items' => array( 'simple_grid_field11' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field3' => array( 'cols' => array( 3 ),
'rows' => array( 0 ),
'tags' => array( 'status_fieldheadercolumn' ),
'items' => array( 'grid_field_label' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field1' => array( 'cols' => array( 4 ),
'rows' => array( 0 ),
'tags' => array( 'agf_fieldheadercolumn' ),
'items' => array( 'grid_field_label2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field8' => array( 'cols' => array( 5 ),
'rows' => array( 0 ),
'tags' => array( 'Saldo_fieldheadercolumn' ),
'items' => array( 'simple_grid_field8' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field4' => array( 'cols' => array( 6 ),
'rows' => array( 0 ),
'tags' => array( 'Debito_fieldheadercolumn' ),
'items' => array( 'grid_field_label3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field6' => array( 'cols' => array( 7 ),
'rows' => array( 0 ),
'tags' => array( 'valor___debito_fieldheadercolumn' ),
'items' => array( 'grid_field_label4' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field8' => array( 'cols' => array( 8 ),
'rows' => array( 0 ),
'tags' => array( 'Num_NP_fieldheadercolumn' ),
'items' => array( 'grid_field_label6' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field' => array( 'cols' => array( 9 ),
'rows' => array( 0 ),
'tags' => array( 'Exercicio_fieldheadercolumn' ),
'items' => array( 'grid_field_label7' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_icons' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array( 'inline_cancel' ),
'items' => array( 'grid_inline_cancel' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field2' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array( 'Parcela_fieldcolumn' ),
'items' => array( 'grid_field5' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field5' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array( 'Data_cad_fieldcolumn' ),
'items' => array( 'simple_grid_field4' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field3' => array( 'cols' => array( 3 ),
'rows' => array( 1 ),
'tags' => array( 'status_fieldcolumn' ),
'items' => array( 'grid_field' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field1' => array( 'cols' => array( 4 ),
'rows' => array( 1 ),
'tags' => array( 'agf_fieldcolumn' ),
'items' => array( 'grid_field2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field9' => array( 'cols' => array( 5 ),
'rows' => array( 1 ),
'tags' => array( 'Saldo_fieldcolumn' ),
'items' => array( 'simple_grid_field5' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field4' => array( 'cols' => array( 6 ),
'rows' => array( 1 ),
'tags' => array( 'Debito_fieldcolumn' ),
'items' => array( 'grid_field3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field6' => array( 'cols' => array( 7 ),
'rows' => array( 1 ),
'tags' => array( 'valor___debito_fieldcolumn' ),
'items' => array( 'grid_field4' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field12' => array( 'cols' => array( 8 ),
'rows' => array( 1 ),
'tags' => array( 'Num_NP_fieldcolumn' ),
'items' => array( 'grid_field6' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field' => array( 'cols' => array( 9 ),
'rows' => array( 1 ),
'tags' => array( 'Exercicio_fieldcolumn' ),
'items' => array( 'grid_field7' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_icons' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field2' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field5' => array( 'cols' => array( 2 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field3' => array( 'cols' => array( 3 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field1' => array( 'cols' => array( 4 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field11' => array( 'cols' => array( 5 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field4' => array( 'cols' => array( 6 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field6' => array( 'cols' => array( 7 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field8' => array( 'cols' => array( 8 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field' => array( 'cols' => array( 9 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 10,
'height' => 3 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'gridType' => 0,
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false ),
'misc' => array( 'type' => 'masterlist',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'masterlist',
'type' => 'masterlist',
'layoutId' => 'masterlist',
'disabled' => 0,
'default' => 0,
'forms' => array( 'above-grid' => array( 'modelId' => 'empty-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'inline_add' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'empty-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'masterlist-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'back_master' ) ),
'c' => array( 'model' => 'c1',
'items' => array( 'masterlist_header' ) ),
'c2' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'horizontal-grid',
'grid' => array( array( 'section' => 'head',
'cells' => array( array( 'cell' => 'headcell_icons' ),
array( 'cell' => 'headcell_field2' ),
array( 'cell' => 'headcell_field5' ),
array( 'cell' => 'headcell_field3' ),
array( 'cell' => 'headcell_field1' ),
array( 'cell' => 'cell_field8' ),
array( 'cell' => 'headcell_field4' ),
array( 'cell' => 'headcell_field6' ),
array( 'cell' => 'headcell_field8' ),
array( 'cell' => 'headcell_field' ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_icons' ),
array( 'cell' => 'cell_field2' ),
array( 'cell' => 'cell_field5' ),
array( 'cell' => 'cell_field3' ),
array( 'cell' => 'cell_field1' ),
array( 'cell' => 'cell_field9' ),
array( 'cell' => 'cell_field4' ),
array( 'cell' => 'cell_field6' ),
array( 'cell' => 'cell_field12' ),
array( 'cell' => 'cell_field' ) ) ),
array( 'section' => 'foot',
'cells' => array( array( 'cell' => 'footcell_icons' ),
array( 'cell' => 'footcell_field2' ),
array( 'cell' => 'footcell_field5' ),
array( 'cell' => 'footcell_field3' ),
array( 'cell' => 'footcell_field1' ),
array( 'cell' => 'cell_field11' ),
array( 'cell' => 'footcell_field4' ),
array( 'cell' => 'footcell_field6' ),
array( 'cell' => 'footcell_field8' ),
array( 'cell' => 'footcell_field' ) ) ) ),
'cells' => array( 'headcell_field2' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label5' ),
'field' => 'Parcela',
'columnName' => 'field' ),
'cell_field2' => array( 'model' => 'cell_field',
'items' => array( 'grid_field5' ),
'align' => 'center',
'field' => 'Parcela',
'columnName' => 'field' ),
'footcell_field2' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field5' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field11' ),
'field' => 'Data_cad',
'columnName' => 'field' ),
'cell_field5' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field4' ),
'field' => 'Data_cad',
'columnName' => 'field' ),
'footcell_field5' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field3' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label' ),
'field' => 'status',
'columnName' => 'field' ),
'cell_field3' => array( 'model' => 'cell_field',
'items' => array( 'grid_field' ),
'field' => 'status',
'columnName' => 'field' ),
'footcell_field3' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field1' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label2' ),
'align' => 'center',
'field' => 'agf',
'columnName' => 'field' ),
'cell_field1' => array( 'model' => 'cell_field',
'items' => array( 'grid_field2' ),
'align' => 'center',
'nowrap' => true,
'field' => 'agf',
'columnName' => 'field' ),
'footcell_field1' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field4' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label3' ),
'align' => 'center',
'field' => 'Debito',
'columnName' => 'field' ),
'cell_field4' => array( 'model' => 'cell_field',
'items' => array( 'grid_field3' ),
'align' => 'center',
'field' => 'Debito',
'columnName' => 'field' ),
'footcell_field4' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field6' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label4' ),
'align' => 'center',
'field' => 'valor - debito',
'columnName' => 'field' ),
'cell_field6' => array( 'model' => 'cell_field',
'items' => array( 'grid_field4' ),
'field' => 'valor - debito',
'columnName' => 'field' ),
'footcell_field6' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'cell_field8' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field8' ),
'align' => 'center',
'field' => 'Saldo',
'columnName' => 'field' ),
'cell_field9' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field5' ),
'align' => 'center',
'field' => 'Saldo',
'columnName' => 'field' ),
'cell_field11' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field8' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label6' ),
'field' => 'Num_NP',
'columnName' => 'field' ),
'cell_field12' => array( 'model' => 'cell_field',
'items' => array( 'grid_field6' ),
'field' => 'Num_NP',
'columnName' => 'field' ),
'footcell_field8' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label7' ),
'field' => 'Exercicio',
'columnName' => 'field' ),
'cell_field' => array( 'model' => 'cell_field',
'items' => array( 'grid_field7' ),
'field' => 'Exercicio',
'columnName' => 'field' ),
'footcell_field' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_icons' => array( 'model' => 'headcell_icons',
'items' => array(  ) ),
'cell_icons' => array( 'model' => 'cell_icons',
'items' => array( 'grid_inline_cancel' ) ),
'footcell_icons' => array( 'model' => 'footcell_icons',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'masterlist_header' => array( 'type' => 'masterlist_header',
'title' => array( 'page' => 'masterlist',
'table' => 'pedidos',
'type' => 7 ),
'bold' => true,
'nowrap' => true ),
'back_master' => array( 'type' => 'back_master',
'buttonSize' => 'normal',
'buttonStyle' => 'link-button',
'label' => array( 'type' => 0,
'text' => 'Voltar' ),
'icon' => array( 'fa' => 'arrow-circle-left' ),
'tooltip' => array( 'type' => 0,
'text' => 'Voltar para tela anterior' ) ),
'simple_grid_field4' => array( 'field' => 'Data_cad',
'type' => 'grid_field' ),
'simple_grid_field5' => array( 'field' => 'Saldo',
'type' => 'grid_field',
'nowrap' => true,
'bold' => true ),
'simple_grid_field8' => array( 'type' => 'grid_field_label',
'field' => 'Saldo',
'label' => array( 'field' => 'Saldo',
'table' => 'pedidos',
'type' => 3 ) ),
'simple_grid_field11' => array( 'type' => 'grid_field_label',
'field' => 'Data_cad' ),
'grid_field' => array( 'field' => 'status',
'type' => 'grid_field' ),
'grid_field_label' => array( 'type' => 'grid_field_label',
'field' => 'status' ),
'grid_field5' => array( 'field' => 'Parcela',
'type' => 'grid_field' ),
'grid_field_label5' => array( 'type' => 'grid_field_label',
'field' => 'Parcela' ),
'grid_field3' => array( 'field' => 'Debito',
'type' => 'grid_field',
'bold' => true,
'nowrap' => true ),
'grid_field_label3' => array( 'type' => 'grid_field_label',
'field' => 'Debito',
'label' => array( 'field' => 'Debito',
'table' => 'pedidos',
'type' => 3 ) ),
'grid_field4' => array( 'field' => 'valor - debito',
'type' => 'grid_field',
'nowrap' => true,
'bold' => true,
'color' => '#4cd644' ),
'grid_field_label4' => array( 'type' => 'grid_field_label',
'field' => 'valor - debito' ),
'grid_field2' => array( 'field' => 'agf',
'type' => 'grid_field',
'bold' => true,
'nowrap' => true ),
'grid_field_label2' => array( 'type' => 'grid_field_label',
'field' => 'agf',
'label' => array( 'field' => 'agf',
'table' => 'pedidos',
'type' => 3 ) ),
'grid_field6' => array( 'field' => 'Num_NP',
'type' => 'grid_field' ),
'grid_field_label6' => array( 'type' => 'grid_field_label',
'field' => 'Num_NP',
'label' => array( 'field' => 'Num_NP',
'table' => 'pedidos',
'type' => 3 ) ),
'grid_field7' => array( 'field' => 'Exercicio',
'type' => 'grid_field' ),
'grid_field_label7' => array( 'type' => 'grid_field_label',
'field' => 'Exercicio' ),
'inline_add' => array( 'type' => 'inline_add',
'detailsOnly' => true ),
'grid_inline_cancel' => array( 'type' => 'grid_inline_cancel' ) ),
'dbProps' => array(  ),
'version' => 11,
'pageWidth' => 'standard',
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right' );
		?>