<?php
			$optionsArray = array( 'pdf' => array( 'pdfView' => true,
'orientation' => 'portrait',
'scale' => 100 ),
'fields' => array( 'gridFields' => array(  ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'Direc' => array( 'grid_group_field1',
'group_summary_count1',
'grid_group_field_label1',
'group_summary_field_label1',
'group_summary_field_value1' ),
'Drae' => array( 'grid_group_field_label',
'group_summary_field_label',
'grid_group_field',
'group_summary_field_value',
'group_summary_count' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array( 'print_pages' ),
'below-grid' => array(  ),
'top' => array( 'print_header',
'print_subheader',
'print_pdf' ),
'grid' => array( 'grid_group_field_label',
'group_summary_label1',
'group_summary_field_label',
'group_summary_dash',
'group_summary_field_value',
'group_summary_label2',
'group_summary_dash3',
'group_summary_count',
'group_summary_dash4',
'grid_group_field',
'grid_group_field_label1',
'group_summary_label',
'group_summary_field_label1',
'group_summary_dash5',
'group_summary_field_value1',
'group_summary_dash1',
'group_summary_label3',
'group_summary_dash2',
'group_summary_count1',
'grid_group_field1',
'page_summary_label1',
'page_summary_dash',
'page_summary_count',
'page_summary_label2',
'global_summary_label1',
'global_summary_dash',
'global_summary_count',
'global_summary_label2',
'text' ) ),
'formXtTags' => array( 'above-grid' => array( 'print_pages' ),
'below-grid' => array(  ) ),
'itemForms' => array( 'print_pages' => 'above-grid',
'print_header' => 'top',
'print_subheader' => 'top',
'print_pdf' => 'top',
'grid_group_field_label' => 'grid',
'group_summary_label1' => 'grid',
'group_summary_field_label' => 'grid',
'group_summary_dash' => 'grid',
'group_summary_field_value' => 'grid',
'group_summary_label2' => 'grid',
'group_summary_dash3' => 'grid',
'group_summary_count' => 'grid',
'group_summary_dash4' => 'grid',
'grid_group_field' => 'grid',
'grid_group_field_label1' => 'grid',
'group_summary_label' => 'grid',
'group_summary_field_label1' => 'grid',
'group_summary_dash5' => 'grid',
'group_summary_field_value1' => 'grid',
'group_summary_dash1' => 'grid',
'group_summary_label3' => 'grid',
'group_summary_dash2' => 'grid',
'group_summary_count1' => 'grid',
'grid_group_field1' => 'grid',
'page_summary_label1' => 'grid',
'page_summary_dash' => 'grid',
'page_summary_count' => 'grid',
'page_summary_label2' => 'grid',
'global_summary_label1' => 'grid',
'global_summary_dash' => 'grid',
'global_summary_count' => 'grid',
'global_summary_label2' => 'grid',
'text' => 'grid' ),
'itemLocations' => array( 'grid_group_field_label' => array( 'location' => 'grid',
'cellId' => 'headcell_groupfield' ),
'group_summary_label1' => array( 'location' => 'grid',
'cellId' => 'cell_group_summary' ),
'group_summary_field_label' => array( 'location' => 'grid',
'cellId' => 'cell_group_summary' ),
'group_summary_dash' => array( 'location' => 'grid',
'cellId' => 'cell_group_summary' ),
'group_summary_field_value' => array( 'location' => 'grid',
'cellId' => 'cell_group_summary' ),
'group_summary_label2' => array( 'location' => 'grid',
'cellId' => 'cell_group_summary' ),
'group_summary_dash3' => array( 'location' => 'grid',
'cellId' => 'cell_group_summary' ),
'group_summary_count' => array( 'location' => 'grid',
'cellId' => 'cell_group_summary' ),
'group_summary_dash4' => array( 'location' => 'grid',
'cellId' => 'cell_group_summary' ),
'grid_group_field' => array( 'location' => 'grid',
'cellId' => 'cell_group_field' ),
'grid_group_field_label1' => array( 'location' => 'grid',
'cellId' => 'headcell_groupfield1' ),
'group_summary_label' => array( 'location' => 'grid',
'cellId' => 'cell_group_summary1' ),
'group_summary_field_label1' => array( 'location' => 'grid',
'cellId' => 'cell_group_summary1' ),
'group_summary_dash5' => array( 'location' => 'grid',
'cellId' => 'cell_group_summary1' ),
'group_summary_field_value1' => array( 'location' => 'grid',
'cellId' => 'cell_group_summary1' ),
'group_summary_dash1' => array( 'location' => 'grid',
'cellId' => 'cell_group_summary1' ),
'group_summary_label3' => array( 'location' => 'grid',
'cellId' => 'cell_group_summary1' ),
'group_summary_dash2' => array( 'location' => 'grid',
'cellId' => 'cell_group_summary1' ),
'group_summary_count1' => array( 'location' => 'grid',
'cellId' => 'cell_group_summary1' ),
'grid_group_field1' => array( 'location' => 'grid',
'cellId' => 'cell_group_field1' ),
'page_summary_label1' => array( 'location' => 'grid',
'cellId' => 'cell_page_summary' ),
'page_summary_dash' => array( 'location' => 'grid',
'cellId' => 'cell_page_summary' ),
'page_summary_count' => array( 'location' => 'grid',
'cellId' => 'cell_page_summary' ),
'page_summary_label2' => array( 'location' => 'grid',
'cellId' => 'cell_page_summary' ),
'global_summary_label1' => array( 'location' => 'grid',
'cellId' => 'cell_global_summary' ),
'global_summary_dash' => array( 'location' => 'grid',
'cellId' => 'cell_global_summary' ),
'global_summary_count' => array( 'location' => 'grid',
'cellId' => 'cell_global_summary' ),
'global_summary_label2' => array( 'location' => 'grid',
'cellId' => 'cell_global_summary' ),
'text' => array( 'location' => 'grid',
'cellId' => 'headcell_groupfield3' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'print_header' => array( 'print_header' ),
'print_subheader' => array( 'print_subheader' ),
'print_pages' => array( 'print_pages' ),
'print_pdf' => array( 'print_pdf' ),
'page_summary_count' => array( 'page_summary_count' ),
'page_summary_dash' => array( 'page_summary_dash' ),
'page_summary_label1' => array( 'page_summary_label1' ),
'grid_group_field' => array( 'grid_group_field1',
'grid_group_field' ),
'group_summary_count' => array( 'group_summary_count1',
'group_summary_count' ),
'text' => array( 'text' ),
'global_summary_label2' => array( 'global_summary_label2' ),
'global_summary_count' => array( 'global_summary_count' ),
'global_summary_dash' => array( 'global_summary_dash' ),
'global_summary_label1' => array( 'global_summary_label1' ),
'grid_group_field_label' => array( 'grid_group_field_label',
'grid_group_field_label1' ),
'group_summary_label1' => array( 'group_summary_label1',
'group_summary_label' ),
'group_summary_field_label' => array( 'group_summary_field_label',
'group_summary_field_label1' ),
'group_summary_dash' => array( 'group_summary_dash',
'group_summary_dash3',
'group_summary_dash1',
'group_summary_dash4',
'group_summary_dash2',
'group_summary_dash5' ),
'group_summary_field_value' => array( 'group_summary_field_value',
'group_summary_field_value1' ),
'group_summary_label2' => array( 'group_summary_label2',
'group_summary_label3' ),
'page_summary_label2' => array( 'page_summary_label2' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'headcell_groupfield3' => array( 'cols' => array( 0,
1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'text' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'headcell_groupfield2' => array( 'cols' => array( 0,
1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_groupfield' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'grid_group_field_label' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'headcell_groupfield1' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'grid_group_field_label1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'cell_group_field' => array( 'cols' => array( 0,
1 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'grid_group_field' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'cell_group_empty1' => array( 'cols' => array( 0 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_group_field1' => array( 'cols' => array( 1 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'grid_group_field1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'cell_group_empty' => array( 'cols' => array( 0 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_group_summary1' => array( 'cols' => array( 1 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array( 'group_summary_label',
'group_summary_field_label1',
'group_summary_dash5',
'group_summary_field_value1',
'group_summary_dash1',
'group_summary_label3',
'group_summary_dash2',
'group_summary_count1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'cell_group_summary' => array( 'cols' => array( 0,
1 ),
'rows' => array( 6 ),
'tags' => array(  ),
'items' => array( 'group_summary_label1',
'group_summary_field_label',
'group_summary_dash',
'group_summary_field_value',
'group_summary_label2',
'group_summary_dash3',
'group_summary_count',
'group_summary_dash4' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'cell_page_summary' => array( 'cols' => array( 0,
1 ),
'rows' => array( 7 ),
'tags' => array(  ),
'items' => array( 'page_summary_label1',
'page_summary_dash',
'page_summary_count',
'page_summary_label2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'cell_global_summary' => array( 'cols' => array( 0,
1 ),
'rows' => array( 8 ),
'tags' => array(  ),
'items' => array( 'global_summary_label1',
'global_summary_dash',
'global_summary_count',
'global_summary_label2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 9 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array( 'print_pages' => array( 'tag' => 'PRINT_PAGES',
'type' => 2 ) ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false ),
'misc' => array( 'type' => 'rprint',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'newreport' => array( 'reportInfo' => array( 'groupFields' => array( array( 'interval' => 0,
'summary' => true,
'field' => 'Drae',
'color' => array( 'header' => 'D8D8D8',
'summary' => 'FFFFFF' ) ),
array( 'interval' => 0,
'summary' => true,
'field' => 'Direc',
'color' => array( 'header' => 'D8D8D8',
'summary' => 'FFFFFF' ) ) ),
'fields' => array(  ),
'showData' => true,
'pageSummary' => true,
'globalSummary' => true,
'crosstab' => false,
'layout' => 'stepped' ) ) );
			$pageArray = array( 'id' => 'rprint',
'type' => 'rprint',
'layoutId' => 'basic',
'disabled' => 0,
'default' => 0,
'forms' => array( 'above-grid' => array( 'modelId' => 'print-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'print_pages' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'print-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'print-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c2' => array( 'model' => 'c2',
'items' => array( 'print_header',
'print_subheader' ) ),
'c1' => array( 'model' => 'c1',
'items' => array( 'print_pdf' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'report-stepped',
'grid' => array( array( 'section' => 'head',
'cells' => array( array( 'cell' => 'headcell_groupfield3',
'colspan' => 2 ) ) ),
array( 'section' => 'head',
'cells' => array( array( 'cell' => 'headcell_groupfield2',
'colspan' => 2 ) ) ),
array( 'section' => 'head',
'cells' => array( array( 'cell' => 'headcell_groupfield' ),
array( 'cell' => 'headcell_groupfield1' ) ) ),
array( 'cells' => array( array( 'cell' => 'cell_group_field',
'colspan' => 2 ) ),
'section' => 'group',
'group' => 'Drae' ),
array( 'cells' => array( array( 'cell' => 'cell_group_empty1' ),
array( 'cell' => 'cell_group_field1' ) ),
'section' => 'group',
'group' => 'Direc' ),
array( 'cells' => array( array( 'cell' => 'cell_group_empty' ),
array( 'cell' => 'cell_group_summary1' ) ),
'section' => 'group-summary',
'group' => 'Direc' ),
array( 'cells' => array( array( 'cell' => 'cell_group_summary',
'colspan' => 2 ) ),
'section' => 'group-summary',
'group' => 'Drae' ),
array( 'cells' => array( array( 'cell' => 'cell_page_summary',
'colspan' => 2 ) ),
'section' => 'page-summary' ),
array( 'cells' => array( array( 'cell' => 'cell_global_summary',
'colspan' => 2 ) ),
'section' => 'global-summary' ) ),
'cells' => array( 'headcell_groupfield' => array( 'model' => 'headcell_groupfield',
'items' => array( 'grid_group_field_label' ),
'field' => 'Drae' ),
'cell_group_summary' => array( 'model' => 'cell_group_summary',
'items' => array( 'group_summary_label1',
'group_summary_field_label',
'group_summary_dash',
'group_summary_field_value',
'group_summary_label2',
'group_summary_dash3',
'group_summary_count',
'group_summary_dash4' ),
'field' => 'Drae' ),
'cell_group_field' => array( 'model' => 'cell_group_field',
'items' => array( 'grid_group_field' ),
'field' => 'Drae' ),
'headcell_groupfield1' => array( 'model' => 'headcell_groupfield',
'items' => array( 'grid_group_field_label1' ),
'field' => 'Direc' ),
'cell_group_empty' => array( 'model' => 'cell_group_empty',
'items' => array(  ),
'field' => 'Drae' ),
'cell_group_summary1' => array( 'model' => 'cell_group_summary',
'items' => array( 'group_summary_label',
'group_summary_field_label1',
'group_summary_dash5',
'group_summary_field_value1',
'group_summary_dash1',
'group_summary_label3',
'group_summary_dash2',
'group_summary_count1' ),
'field' => 'Direc' ),
'cell_group_empty1' => array( 'model' => 'cell_group_empty',
'items' => array(  ),
'field' => 'Drae' ),
'cell_group_field1' => array( 'model' => 'cell_group_field',
'items' => array( 'grid_group_field1' ),
'field' => 'Direc' ),
'cell_page_summary' => array( 'model' => 'cell_page_summary',
'items' => array( 'page_summary_label1',
'page_summary_dash',
'page_summary_count',
'page_summary_label2' ),
'field' => 'Drae' ),
'cell_global_summary' => array( 'model' => 'cell_global_summary',
'items' => array( 'global_summary_label1',
'global_summary_dash',
'global_summary_count',
'global_summary_label2' ),
'field' => 'Drae' ),
'headcell_groupfield2' => array( 'model' => 'headcell_groupfield',
'items' => array(  ),
'field' => 'Drae' ),
'headcell_groupfield3' => array( 'model' => 'headcell_groupfield',
'items' => array( 'text' ),
'field' => 'Drae',
'align' => 'center' ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1,
'groupColors' => array( 'Drae' => array( 'header' => 'D8D8D8',
'summary' => 'FFFFFF' ),
'Direc' => array( 'header' => 'D8D8D8',
'summary' => 'FFFFFF' ) ) ) ),
'items' => array( 'print_header' => array( 'type' => 'print_header' ),
'print_subheader' => array( 'type' => 'print_subheader' ),
'print_pages' => array( 'type' => 'print_pages' ),
'print_pdf' => array( 'type' => 'print_pdf',
'targetPages' => array(  ),
'splitModes' => array(  ),
'scopes' => array(  ) ),
'page_summary_count' => array( 'type' => 'page_summary_count' ),
'page_summary_dash' => array( 'type' => 'page_summary_dash' ),
'page_summary_label1' => array( 'type' => 'page_summary_label1' ),
'grid_group_field1' => array( 'field' => 'Direc',
'type' => 'grid_group_field',
'summary' => true,
'interval' => 0 ),
'group_summary_count1' => array( 'type' => 'group_summary_count',
'field' => 'Direc' ),
'text' => array( 'type' => 'text',
'label' => array( 'type' => 0,
'text' => 'SISPED - Relatório Sintetido Escolas por DRAE / DIREC' ),
'editedByRte' => false,
'bold' => true,
'font-size' => '16px' ),
'global_summary_label2' => array( 'type' => 'global_summary_label2' ),
'global_summary_count' => array( 'type' => 'global_summary_count' ),
'global_summary_dash' => array( 'type' => 'global_summary_dash' ),
'global_summary_label1' => array( 'type' => 'global_summary_label1' ),
'grid_group_field_label' => array( 'type' => 'grid_group_field_label',
'field' => 'Drae' ),
'group_summary_label1' => array( 'type' => 'group_summary_label1',
'field' => 'Drae' ),
'group_summary_field_label' => array( 'type' => 'group_summary_field_label',
'field' => 'Drae' ),
'grid_group_field' => array( 'field' => 'Drae',
'type' => 'grid_group_field',
'summary' => true,
'interval' => 0 ),
'group_summary_dash' => array( 'type' => 'group_summary_dash',
'field' => 'Drae' ),
'group_summary_field_value' => array( 'type' => 'group_summary_field_value',
'field' => 'Drae',
'interval' => 0 ),
'group_summary_label2' => array( 'type' => 'group_summary_label2',
'field' => 'Drae',
'label' => array( 'type' => 0,
'text' => 'Total de Ecola(s)' ) ),
'group_summary_dash3' => array( 'type' => 'group_summary_dash',
'field' => 'Drae' ),
'group_summary_count' => array( 'type' => 'group_summary_count',
'field' => 'Drae' ),
'group_summary_dash1' => array( 'type' => 'group_summary_dash',
'field' => 'Direc' ),
'group_summary_dash4' => array( 'type' => 'group_summary_dash',
'field' => 'Drae' ),
'page_summary_label2' => array( 'type' => 'page_summary_label2' ),
'group_summary_dash2' => array( 'type' => 'group_summary_dash',
'field' => 'Direc' ),
'grid_group_field_label1' => array( 'type' => 'grid_group_field_label',
'field' => 'Direc' ),
'group_summary_label' => array( 'type' => 'group_summary_label1',
'field' => 'Direc' ),
'group_summary_field_label1' => array( 'type' => 'group_summary_field_label',
'field' => 'Direc' ),
'group_summary_label3' => array( 'type' => 'group_summary_label2',
'field' => 'Direc',
'label' => array( 'type' => 0,
'text' => 'Total de Escola(s)' ) ),
'group_summary_dash5' => array( 'type' => 'group_summary_dash',
'field' => 'Direc' ),
'group_summary_field_value1' => array( 'type' => 'group_summary_field_value',
'field' => 'Direc',
'interval' => 0 ) ),
'dbProps' => array(  ),
'version' => 11,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right' );
		?>