<?php
			$optionsArray = array( 'pdf' => array( 'pdfView' => true,
'orientation' => 'portrait',
'scale' => 100 ),
'listSearch' => array( 'alwaysOnPanelFields' => array(  ),
'searchPanel' => true,
'fixedSearchPanel' => false,
'simpleSearchOptions' => false,
'searchSaving' => false ),
'fields' => array( 'gridFields' => array( 'CNPJ',
'Municipio',
'Bairro',
'Endereço',
'Nome' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array( 'Nome',
'Endereço',
'Municipio',
'Drae',
'Direc',
'CNPJ',
'Bairro' ),
'filterFields' => array(  ),
'fieldItems' => array( 'Drae' => array( 'group_summary_field_label',
'group_summary_field_value',
'grid_group_field_label',
'grid_group_field',
'group_summary_count' ),
'CNPJ' => array( 'report_advanced_field_label5',
'report_advanced_field5' ),
'Municipio' => array( 'report_advanced_field_label4',
'report_advanced_field4' ),
'Bairro' => array( 'report_advanced_field_label2',
'report_advanced_field2' ),
'Endereço' => array( 'report_advanced_field_label1',
'report_advanced_field1' ),
'Nome' => array( 'report_advanced_field_label',
'report_advanced_field' ),
'Direc' => array( 'grid_group_field_label1',
'grid_group_field1',
'group_summary_count1',
'group_summary_field_value1',
'group_summary_field_label1' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array( 'details_found',
'page_size',
'print_panel',
'text' ),
'below-grid' => array( 'pagination' ),
'left' => array( 'logo',
'expand_button',
'menu',
'search_panel' ),
'supertop' => array( 'expand_menu_button',
'collapse_button',
'simple_search',
'list_options',
'notifications',
'loginform_login',
'username_button' ),
'grid' => array( 'grid_group_field_label',
'group_summary_label1',
'group_summary_field_label',
'group_summary_field_value',
'group_summary_dash',
'group_summary_count',
'group_summary_label2',
'grid_group_field',
'grid_group_field_label1',
'group_summary_label',
'group_summary_field_label1',
'group_summary_field_value1',
'group_summary_dash1',
'group_summary_count1',
'group_summary_label3',
'grid_group_field1',
'report_advanced_field_label5',
'report_advanced_field5',
'report_advanced_field_label',
'report_advanced_field',
'report_advanced_field_label1',
'report_advanced_field1',
'report_advanced_field_label2',
'report_advanced_field2',
'report_advanced_field_label4',
'report_advanced_field4',
'page_summary_label1',
'page_summary_dash',
'page_summary_count',
'page_summary_label2',
'global_summary_label1',
'global_summary_dash',
'global_summary_count',
'global_summary_label2' ),
'top' => array(  ) ),
'formXtTags' => array( 'below-grid' => array( 'pagination' ),
'top' => array(  ) ),
'itemForms' => array( 'details_found' => 'above-grid',
'page_size' => 'above-grid',
'print_panel' => 'above-grid',
'text' => 'above-grid',
'pagination' => 'below-grid',
'logo' => 'left',
'expand_button' => 'left',
'menu' => 'left',
'search_panel' => 'left',
'expand_menu_button' => 'supertop',
'collapse_button' => 'supertop',
'simple_search' => 'supertop',
'list_options' => 'supertop',
'notifications' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'grid_group_field_label' => 'grid',
'group_summary_label1' => 'grid',
'group_summary_field_label' => 'grid',
'group_summary_field_value' => 'grid',
'group_summary_dash' => 'grid',
'group_summary_count' => 'grid',
'group_summary_label2' => 'grid',
'grid_group_field' => 'grid',
'grid_group_field_label1' => 'grid',
'group_summary_label' => 'grid',
'group_summary_field_label1' => 'grid',
'group_summary_field_value1' => 'grid',
'group_summary_dash1' => 'grid',
'group_summary_count1' => 'grid',
'group_summary_label3' => 'grid',
'grid_group_field1' => 'grid',
'report_advanced_field_label5' => 'grid',
'report_advanced_field5' => 'grid',
'report_advanced_field_label' => 'grid',
'report_advanced_field' => 'grid',
'report_advanced_field_label1' => 'grid',
'report_advanced_field1' => 'grid',
'report_advanced_field_label2' => 'grid',
'report_advanced_field2' => 'grid',
'report_advanced_field_label4' => 'grid',
'report_advanced_field4' => 'grid',
'page_summary_label1' => 'grid',
'page_summary_dash' => 'grid',
'page_summary_count' => 'grid',
'page_summary_label2' => 'grid',
'global_summary_label1' => 'grid',
'global_summary_dash' => 'grid',
'global_summary_count' => 'grid',
'global_summary_label2' => 'grid' ),
'itemLocations' => array( 'grid_group_field_label' => array( 'location' => 'grid',
'cellId' => 'headcell_groupfield' ),
'group_summary_label1' => array( 'location' => 'grid',
'cellId' => 'cell_group_summary' ),
'group_summary_field_label' => array( 'location' => 'grid',
'cellId' => 'cell_group_summary' ),
'group_summary_field_value' => array( 'location' => 'grid',
'cellId' => 'cell_group_summary' ),
'group_summary_dash' => array( 'location' => 'grid',
'cellId' => 'cell_group_summary' ),
'group_summary_count' => array( 'location' => 'grid',
'cellId' => 'cell_group_summary' ),
'group_summary_label2' => array( 'location' => 'grid',
'cellId' => 'cell_group_summary' ),
'grid_group_field' => array( 'location' => 'grid',
'cellId' => 'cell_group_field' ),
'grid_group_field_label1' => array( 'location' => 'grid',
'cellId' => 'headcell_groupfield1' ),
'group_summary_label' => array( 'location' => 'grid',
'cellId' => 'cell_group_summary1' ),
'group_summary_field_label1' => array( 'location' => 'grid',
'cellId' => 'cell_group_summary1' ),
'group_summary_field_value1' => array( 'location' => 'grid',
'cellId' => 'cell_group_summary1' ),
'group_summary_dash1' => array( 'location' => 'grid',
'cellId' => 'cell_group_summary1' ),
'group_summary_count1' => array( 'location' => 'grid',
'cellId' => 'cell_group_summary1' ),
'group_summary_label3' => array( 'location' => 'grid',
'cellId' => 'cell_group_summary1' ),
'grid_group_field1' => array( 'location' => 'grid',
'cellId' => 'cell_group_field1' ),
'report_advanced_field_label5' => array( 'location' => 'grid',
'cellId' => 'headcell_field' ),
'report_advanced_field5' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'report_advanced_field_label' => array( 'location' => 'grid',
'cellId' => 'headcell_field1' ),
'report_advanced_field' => array( 'location' => 'grid',
'cellId' => 'cell_field1' ),
'report_advanced_field_label1' => array( 'location' => 'grid',
'cellId' => 'headcell_field2' ),
'report_advanced_field1' => array( 'location' => 'grid',
'cellId' => 'cell_field2' ),
'report_advanced_field_label2' => array( 'location' => 'grid',
'cellId' => 'headcell_field4' ),
'report_advanced_field2' => array( 'location' => 'grid',
'cellId' => 'cell_field4' ),
'report_advanced_field_label4' => array( 'location' => 'grid',
'cellId' => 'headcell_field5' ),
'report_advanced_field4' => array( 'location' => 'grid',
'cellId' => 'cell_field5' ),
'page_summary_label1' => array( 'location' => 'grid',
'cellId' => 'cell_page_summary' ),
'page_summary_dash' => array( 'location' => 'grid',
'cellId' => 'cell_page_summary' ),
'page_summary_count' => array( 'location' => 'grid',
'cellId' => 'cell_page_summary' ),
'page_summary_label2' => array( 'location' => 'grid',
'cellId' => 'cell_page_summary' ),
'global_summary_label1' => array( 'location' => 'grid',
'cellId' => 'cell_global_summary' ),
'global_summary_dash' => array( 'location' => 'grid',
'cellId' => 'cell_global_summary' ),
'global_summary_count' => array( 'location' => 'grid',
'cellId' => 'cell_global_summary' ),
'global_summary_label2' => array( 'location' => 'grid',
'cellId' => 'cell_global_summary' ) ),
'itemVisiblity' => array( 'expand_menu_button' => 2,
'print_panel' => 5,
'expand_button' => 5 ) ),
'itemsByType' => array( 'page_size' => array( 'page_size' ),
'details_found' => array( 'details_found' ),
'logo' => array( 'logo' ),
'menu' => array( 'menu' ),
'simple_search' => array( 'simple_search' ),
'pagination' => array( 'pagination' ),
'list_options' => array( 'list_options' ),
'export_report_excel' => array( 'export_report_excel' ),
'export_report_word' => array( 'export_report_word' ),
'search_panel' => array( 'search_panel' ),
'show_search_panel' => array( 'show_search_panel' ),
'-' => array( '-',
'-1' ),
'hide_search_panel' => array( 'hide_search_panel' ),
'search_panel_field' => array( 'search_panel_field1',
'search_panel_field2',
'search_panel_field6',
'search_panel_field7',
'search_panel_field15',
'search_panel_field3',
'search_panel_field' ),
'username_button' => array( 'username_button' ),
'loginform_login' => array( 'loginform_login' ),
'userinfo_link' => array( 'userinfo_link' ),
'logout_link' => array( 'logout_link' ),
'adminarea_link' => array( 'adminarea_link' ),
'changepassword_link' => array( 'changepassword_link' ),
'expand_menu_button' => array( 'expand_menu_button' ),
'collapse_button' => array( 'collapse_button' ),
'print_panel' => array( 'print_panel' ),
'print_scope' => array( 'print_scope' ),
'print_button' => array( 'print_button' ),
'print_records' => array( 'print_records' ),
'advsearch_link' => array( 'advsearch_link' ),
'export_report_pdf' => array( 'export_report_pdf' ),
'global_summary_dash' => array( 'global_summary_dash' ),
'global_summary_label1' => array( 'global_summary_label1' ),
'text' => array( 'text' ),
'group_summary_label1' => array( 'group_summary_label1',
'group_summary_label' ),
'group_summary_field_label' => array( 'group_summary_field_label',
'group_summary_field_label1' ),
'group_summary_field_value' => array( 'group_summary_field_value',
'group_summary_field_value1' ),
'page_summary_label2' => array( 'page_summary_label2' ),
'page_summary_count' => array( 'page_summary_count' ),
'page_summary_dash' => array( 'page_summary_dash' ),
'page_summary_label1' => array( 'page_summary_label1' ),
'report_advanced_field_label' => array( 'report_advanced_field_label5',
'report_advanced_field_label4',
'report_advanced_field_label2',
'report_advanced_field_label1',
'report_advanced_field_label' ),
'report_advanced_field' => array( 'report_advanced_field5',
'report_advanced_field4',
'report_advanced_field2',
'report_advanced_field1',
'report_advanced_field' ),
'grid_group_field_label' => array( 'grid_group_field_label1',
'grid_group_field_label' ),
'grid_group_field' => array( 'grid_group_field1',
'grid_group_field' ),
'group_summary_label2' => array( 'group_summary_label3',
'group_summary_label2' ),
'group_summary_count' => array( 'group_summary_count1',
'group_summary_count' ),
'group_summary_dash' => array( 'group_summary_dash1',
'group_summary_dash' ),
'global_summary_count' => array( 'global_summary_count' ),
'global_summary_label2' => array( 'global_summary_label2' ),
'notifications' => array( 'notifications' ),
'expand_button' => array( 'expand_button' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'headcell_groupfield' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'grid_group_field_label' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'headcell_groupfield1' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'grid_group_field_label1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'headcell_field' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'report_advanced_field_label5' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'headcell_field1' => array( 'cols' => array( 3 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'report_advanced_field_label' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'headcell_field2' => array( 'cols' => array( 4 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'report_advanced_field_label1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'headcell_field4' => array( 'cols' => array( 5 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'report_advanced_field_label2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'headcell_field5' => array( 'cols' => array( 6 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'report_advanced_field_label4' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'cell_group_field' => array( 'cols' => array( 0,
1,
2,
3,
4,
5,
6 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'grid_group_field' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'cell_group_empty1' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_group_field1' => array( 'cols' => array( 1,
2,
3,
4,
5,
6 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'grid_group_field1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'cell_group_empty2' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_group_empty3' => array( 'cols' => array( 1 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field' => array( 'cols' => array( 2 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'report_advanced_field5' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'cell_field1' => array( 'cols' => array( 3 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'report_advanced_field' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'cell_field2' => array( 'cols' => array( 4 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'report_advanced_field1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'cell_field4' => array( 'cols' => array( 5 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'report_advanced_field2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'cell_field5' => array( 'cols' => array( 6 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'report_advanced_field4' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'cell_group_empty' => array( 'cols' => array( 0 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_group_summary1' => array( 'cols' => array( 1,
2,
3,
4,
5,
6 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'group_summary_label',
'group_summary_field_label1',
'group_summary_field_value1',
'group_summary_dash1',
'group_summary_count1',
'group_summary_label3' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'cell_group_summary' => array( 'cols' => array( 0,
1,
2,
3,
4,
5,
6 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array( 'group_summary_label1',
'group_summary_field_label',
'group_summary_field_value',
'group_summary_dash',
'group_summary_count',
'group_summary_label2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'cell_page_summary' => array( 'cols' => array( 0,
1,
2,
3,
4,
5,
6 ),
'rows' => array( 6 ),
'tags' => array(  ),
'items' => array( 'page_summary_label1',
'page_summary_dash',
'page_summary_count',
'page_summary_label2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'cell_global_summary' => array( 'cols' => array( 0,
1,
2,
3,
4,
5,
6 ),
'rows' => array( 7 ),
'tags' => array(  ),
'items' => array( 'global_summary_label1',
'global_summary_dash',
'global_summary_count',
'global_summary_label2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 7,
'height' => 8 ) ) ),
'loginForm' => array( 'loginForm' => 0 ),
'page' => array( 'verticalBar' => true,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array( 'details_found' => array( 'tag' => 'DISPLAYING',
'type' => 2 ) ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => true ),
'misc' => array( 'type' => 'report',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'newreport' => array( 'reportInfo' => array( 'groupFields' => array( array( 'interval' => 0,
'summary' => true,
'field' => 'Drae',
'color' => array( 'header' => 'D8D8D8',
'summary' => 'FFFFFF' ) ),
array( 'interval' => 0,
'summary' => true,
'field' => 'Direc',
'color' => array( 'header' => 'D8D8D8',
'summary' => 'FFFFFF' ) ) ),
'fields' => array( array( 'field' => 'CNPJ',
'grid' => true ),
array( 'field' => 'Nome',
'grid' => true ),
array( 'field' => 'Endereço',
'grid' => true ),
array( 'field' => 'Bairro',
'grid' => true ),
array( 'field' => 'Municipio',
'grid' => true ) ),
'showData' => true,
'pageSummary' => true,
'globalSummary' => true,
'crosstab' => false,
'layout' => 'stepped' ) ) );
			$pageArray = array( 'id' => 'report',
'type' => 'report',
'layoutId' => 'leftbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'above-grid' => array( 'modelId' => 'report-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c' ),
array( 'cell' => 'c3' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c4',
'colspan' => 2 ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'details_found',
'page_size',
'print_panel' ) ),
'c' => array( 'model' => 'c1',
'items' => array(  ) ),
'c3' => array( 'model' => 'c2',
'items' => array(  ) ),
'c4' => array( 'model' => 'c1',
'items' => array( 'text' ),
'align' => 'center' ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'report-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'pagination' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'left' => array( 'modelId' => 'leftbar-menu',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c0' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c0' => array( 'model' => 'c0',
'items' => array( 'logo',
'expand_button' ) ),
'c1' => array( 'model' => 'c1',
'items' => array( 'menu',
'search_panel' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'supertop' => array( 'modelId' => 'leftbar-top-chart',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'expand_menu_button',
'collapse_button' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'simple_search',
'list_options',
'notifications',
'loginform_login',
'username_button' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'report-stepped',
'grid' => array( array( 'section' => 'head',
'cells' => array( array( 'cell' => 'headcell_groupfield' ),
array( 'cell' => 'headcell_groupfield1' ),
array( 'cell' => 'headcell_field' ),
array( 'cell' => 'headcell_field1' ),
array( 'cell' => 'headcell_field2' ),
array( 'cell' => 'headcell_field4' ),
array( 'cell' => 'headcell_field5' ) ) ),
array( 'cells' => array( array( 'cell' => 'cell_group_field',
'colspan' => 7 ) ),
'section' => 'group',
'group' => 'Drae' ),
array( 'cells' => array( array( 'cell' => 'cell_group_empty1' ),
array( 'cell' => 'cell_group_field1',
'colspan' => 6 ) ),
'section' => 'group',
'group' => 'Direc' ),
array( 'cells' => array( array( 'cell' => 'cell_group_empty2' ),
array( 'cell' => 'cell_group_empty3' ),
array( 'cell' => 'cell_field' ),
array( 'cell' => 'cell_field1' ),
array( 'cell' => 'cell_field2' ),
array( 'cell' => 'cell_field4' ),
array( 'cell' => 'cell_field5' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_group_empty' ),
array( 'cell' => 'cell_group_summary1',
'colspan' => 6 ) ),
'section' => 'group-summary',
'group' => 'Direc' ),
array( 'cells' => array( array( 'cell' => 'cell_group_summary',
'colspan' => 7 ) ),
'section' => 'group-summary',
'group' => 'Drae' ),
array( 'cells' => array( array( 'cell' => 'cell_page_summary',
'colspan' => 7 ) ),
'section' => 'page-summary' ),
array( 'cells' => array( array( 'cell' => 'cell_global_summary',
'colspan' => 7 ) ),
'section' => 'global-summary' ) ),
'cells' => array( 'headcell_groupfield' => array( 'model' => 'headcell_groupfield',
'items' => array( 'grid_group_field_label' ),
'field' => 'Drae' ),
'cell_group_summary' => array( 'model' => 'cell_group_summary',
'items' => array( 'group_summary_label1',
'group_summary_field_label',
'group_summary_field_value',
'group_summary_dash',
'group_summary_count',
'group_summary_label2' ),
'field' => 'Drae' ),
'cell_group_field' => array( 'model' => 'cell_group_field',
'items' => array( 'grid_group_field' ),
'field' => 'Drae' ),
'headcell_groupfield1' => array( 'model' => 'headcell_groupfield',
'items' => array( 'grid_group_field_label1' ),
'field' => 'Direc' ),
'cell_group_empty' => array( 'model' => 'cell_group_empty',
'items' => array(  ),
'field' => 'Drae' ),
'cell_group_summary1' => array( 'model' => 'cell_group_summary',
'items' => array( 'group_summary_label',
'group_summary_field_label1',
'group_summary_field_value1',
'group_summary_dash1',
'group_summary_count1',
'group_summary_label3' ),
'field' => 'Direc' ),
'cell_group_empty1' => array( 'model' => 'cell_group_empty',
'items' => array(  ),
'field' => 'Drae' ),
'cell_group_field1' => array( 'model' => 'cell_group_field',
'items' => array( 'grid_group_field1' ),
'field' => 'Direc' ),
'headcell_field' => array( 'model' => 'headcell_field',
'items' => array( 'report_advanced_field_label5' ),
'field' => 'Nome' ),
'cell_group_empty2' => array( 'model' => 'cell_group_empty',
'items' => array(  ),
'field' => 'Drae' ),
'cell_group_empty3' => array( 'model' => 'cell_group_empty',
'items' => array(  ),
'field' => 'Direc' ),
'cell_field' => array( 'model' => 'cell_field',
'items' => array( 'report_advanced_field5' ),
'field' => 'Nome' ),
'headcell_field1' => array( 'model' => 'headcell_field',
'items' => array( 'report_advanced_field_label' ),
'field' => 'Endereço' ),
'cell_field1' => array( 'model' => 'cell_field',
'items' => array( 'report_advanced_field' ),
'field' => 'Endereço' ),
'headcell_field2' => array( 'model' => 'headcell_field',
'items' => array( 'report_advanced_field_label1' ),
'field' => 'Bairro' ),
'cell_field2' => array( 'model' => 'cell_field',
'items' => array( 'report_advanced_field1' ),
'field' => 'Bairro' ),
'headcell_field4' => array( 'model' => 'headcell_field',
'items' => array( 'report_advanced_field_label2' ),
'field' => 'Municipio' ),
'cell_field4' => array( 'model' => 'cell_field',
'items' => array( 'report_advanced_field2' ),
'field' => 'Municipio' ),
'headcell_field5' => array( 'model' => 'headcell_field',
'items' => array( 'report_advanced_field_label4' ),
'field' => 'CNPJ' ),
'cell_field5' => array( 'model' => 'cell_field',
'items' => array( 'report_advanced_field4' ),
'field' => 'CNPJ' ),
'cell_page_summary' => array( 'model' => 'cell_page_summary',
'items' => array( 'page_summary_label1',
'page_summary_dash',
'page_summary_count',
'page_summary_label2' ),
'field' => 'Drae' ),
'cell_global_summary' => array( 'model' => 'cell_global_summary',
'items' => array( 'global_summary_label1',
'global_summary_dash',
'global_summary_count',
'global_summary_label2' ),
'field' => 'Drae' ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1,
'groupColors' => array( 'Drae' => array( 'header' => 'D8D8D8',
'summary' => 'FFFFFF' ),
'Direc' => array( 'header' => 'D8D8D8',
'summary' => 'FFFFFF' ) ) ),
'top' => array( 'modelId' => 'list-sidebar-top',
'grid' => array(  ),
'cells' => array(  ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'page_size' => array( 'type' => 'page_size' ),
'details_found' => array( 'type' => 'details_found' ),
'logo' => array( 'type' => 'logo' ),
'menu' => array( 'type' => 'menu',
'menuId' => 'main' ),
'simple_search' => array( 'type' => 'simple_search' ),
'pagination' => array( 'type' => 'pagination' ),
'list_options' => array( 'type' => 'list_options',
'items' => array( 'advsearch_link',
'show_search_panel',
'hide_search_panel',
'-1',
'export_report_excel',
'export_report_word',
'export_report_pdf' ) ),
'export_report_excel' => array( 'type' => 'export_report_excel' ),
'export_report_word' => array( 'type' => 'export_report_word' ),
'search_panel' => array( 'type' => 'search_panel',
'items' => array( 'search_panel_field15',
'search_panel_field3',
'search_panel_field',
'search_panel_field7',
'search_panel_field6',
'search_panel_field2',
'search_panel_field1' ) ),
'show_search_panel' => array( 'type' => 'show_search_panel' ),
'-' => array( 'type' => '-' ),
'hide_search_panel' => array( 'type' => 'hide_search_panel' ),
'search_panel_field1' => array( 'field' => 'Bairro',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field2' => array( 'field' => 'CNPJ',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field6' => array( 'field' => 'Direc',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field7' => array( 'field' => 'Drae',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field15' => array( 'field' => 'Nome',
'type' => 'search_panel_field',
'required' => false ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'userinfo_link',
'logout_link',
'adminarea_link',
'changepassword_link' ) ),
'loginform_login' => array( 'type' => 'loginform_login',
'popup' => false ),
'userinfo_link' => array( 'type' => 'userinfo_link' ),
'logout_link' => array( 'type' => 'logout_link' ),
'adminarea_link' => array( 'type' => 'adminarea_link' ),
'changepassword_link' => array( 'type' => 'changepassword_link' ),
'expand_menu_button' => array( 'type' => 'expand_menu_button' ),
'collapse_button' => array( 'type' => 'collapse_button' ),
'print_panel' => array( 'type' => 'print_panel',
'items' => array( 'print_scope',
'print_records',
'print_button' ) ),
'print_scope' => array( 'type' => 'print_scope' ),
'print_button' => array( 'type' => 'print_button' ),
'print_records' => array( 'type' => 'print_records' ),
'advsearch_link' => array( 'type' => 'advsearch_link' ),
'-1' => array( 'type' => '-' ),
'export_report_pdf' => array( 'type' => 'export_report_pdf',
'targetPages' => array(  ),
'splitModes' => array(  ),
'scopes' => array(  ) ),
'search_panel_field3' => array( 'field' => 'Endereço',
'type' => 'search_panel_field',
'required' => false ),
'global_summary_dash' => array( 'type' => 'global_summary_dash' ),
'global_summary_label1' => array( 'type' => 'global_summary_label1' ),
'text' => array( 'type' => 'text',
'label' => array( 'text' => 'SISPED - Relatório Analítico de Escolas por DRAE / DIREC',
'type' => 0 ),
'editedByRte' => false ),
'group_summary_label1' => array( 'type' => 'group_summary_label1',
'field' => 'Drae' ),
'group_summary_field_label' => array( 'type' => 'group_summary_field_label',
'field' => 'Drae' ),
'group_summary_field_value' => array( 'type' => 'group_summary_field_value',
'field' => 'Drae',
'interval' => 0 ),
'page_summary_label2' => array( 'type' => 'page_summary_label2' ),
'page_summary_count' => array( 'type' => 'page_summary_count' ),
'page_summary_dash' => array( 'type' => 'page_summary_dash' ),
'page_summary_label1' => array( 'type' => 'page_summary_label1' ),
'report_advanced_field_label5' => array( 'type' => 'report_advanced_field_label',
'field' => 'CNPJ' ),
'report_advanced_field5' => array( 'field' => 'CNPJ',
'type' => 'report_advanced_field' ),
'report_advanced_field_label4' => array( 'type' => 'report_advanced_field_label',
'field' => 'Municipio',
'nowrap' => true ),
'report_advanced_field4' => array( 'field' => 'Municipio',
'type' => 'report_advanced_field' ),
'report_advanced_field_label2' => array( 'type' => 'report_advanced_field_label',
'field' => 'Bairro' ),
'report_advanced_field2' => array( 'field' => 'Bairro',
'type' => 'report_advanced_field' ),
'report_advanced_field_label1' => array( 'type' => 'report_advanced_field_label',
'field' => 'Endereço',
'nowrap' => true ),
'report_advanced_field1' => array( 'field' => 'Endereço',
'type' => 'report_advanced_field' ),
'report_advanced_field_label' => array( 'type' => 'report_advanced_field_label',
'field' => 'Nome',
'nowrap' => false ),
'report_advanced_field' => array( 'field' => 'Nome',
'type' => 'report_advanced_field' ),
'grid_group_field_label1' => array( 'type' => 'grid_group_field_label',
'field' => 'Direc' ),
'grid_group_field1' => array( 'field' => 'Direc',
'type' => 'grid_group_field',
'summary' => true,
'interval' => 0 ),
'group_summary_label3' => array( 'type' => 'group_summary_label2',
'field' => 'Direc' ),
'search_panel_field' => array( 'field' => 'Municipio',
'type' => 'search_panel_field' ),
'group_summary_count1' => array( 'type' => 'group_summary_count',
'field' => 'Direc' ),
'group_summary_dash1' => array( 'type' => 'group_summary_dash',
'field' => 'Direc' ),
'group_summary_field_value1' => array( 'type' => 'group_summary_field_value',
'field' => 'Direc',
'interval' => 0 ),
'group_summary_field_label1' => array( 'type' => 'group_summary_field_label',
'field' => 'Direc' ),
'group_summary_label' => array( 'type' => 'group_summary_label1',
'field' => 'Direc' ),
'grid_group_field_label' => array( 'type' => 'grid_group_field_label',
'field' => 'Drae' ),
'grid_group_field' => array( 'field' => 'Drae',
'type' => 'grid_group_field',
'summary' => true,
'interval' => 0 ),
'group_summary_label2' => array( 'type' => 'group_summary_label2',
'field' => 'Drae' ),
'group_summary_count' => array( 'type' => 'group_summary_count',
'field' => 'Drae' ),
'group_summary_dash' => array( 'type' => 'group_summary_dash',
'field' => 'Drae' ),
'global_summary_count' => array( 'type' => 'global_summary_count' ),
'global_summary_label2' => array( 'type' => 'global_summary_label2' ),
'notifications' => array( 'type' => 'notifications' ),
'expand_button' => array( 'type' => 'expand_button' ) ),
'dbProps' => array(  ),
'version' => 11,
'pageWidth' => 'full',
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right' );
		?>