<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_pedidos_escola  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["BeforeDelete"]=true;

		$this->events["BeforeQueryPrint"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before record deleted
function BeforeDelete($where, &$deleted_values, &$message, $pageObject)
{

		
global $dal;
$tblPedidos = $dal->Table("Pedidos");  // Tabela mestre
$tblItens = $dal->Table("Itens");  // Tabela de detalhes

// Função para exibir mensagem usando alert
function showMessage($message) {
    echo "<script>
            alert('$message');
          </script>";
}

// Verifica se existem itens associados ao pedido
$rs = $tblItens->Query("cod_ped=".$deleted_values["cod"],"");
$data = db_fetch_array($rs);

if($data) {
    // Se houver dados, significa que existem itens associados ao pedido
    showMessage("O registro não pode ser excluído, pois existem gêneros associados a ele. Por favor, exclua os itens antes de continuar.");
    return false;
} else {
    // Se não houver dados, o pedido pode ser excluído
    $rsPedido = $tblPedidos->Query("cod=".$deleted_values["cod"],"");
    $dataPedido = db_fetch_array($rsPedido);
    
    if($dataPedido) {
        // Excluindo o pedido da tabela mestre se não houver itens associados
        // (Aqui, você pode colocar a lógica de exclusão do pedido, caso necessário)
        return true;
    } else {
        // Caso não exista o pedido para excluir
        showMessage("Pedido não encontrado.");
        return false;
    }
}


// Place event code here.
// Use "Add Action" button to add code snippets.

return true;
;
} // function BeforeDelete

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Print page: Before SQL query
function BeforeQueryPrint(&$strSQL, &$strWhereClause, &$strOrderBy, $pageObject)
{

		$strWhereClause = 'cod in ('.$_SESSION['PRINT_RECORDS'].') ';


// Place event code here.
// Use "Add Action" button to add code snippets.
;
} // function BeforeQueryPrint

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>